import type { Post } from '../../types';

/** Daily remembrances with their sources. */
export const adhkarPosts: Post[] = [
  {
    id: 'dh-best-dhikr',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'The best remembrance', ar: 'أفضل الذكر' },
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ',
    translation: 'There is no god but Allah. The Prophet ﷺ said it is the best remembrance.',
    source: { en: 'At-Tirmidhi 3383', ar: 'الترمذي ٣٣٨٣' },
    theme: 'emerald-night',
    decoration: 'crescent',
    font: 'reem-kufi',
  },
  {
    id: 'dh-four-words',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'Most beloved words', ar: 'أحب الكلام إلى الله' },
    arabic: 'سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ',
    translation:
      'Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest.',
    source: { en: 'Sahih Muslim 2137', ar: 'صحيح مسلم ٢١٣٧' },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'dh-hawqala',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'A treasure of Paradise', ar: 'كنز من كنوز الجنة' },
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    translation: 'There is no might nor power except with Allah.',
    source: { en: 'Sahih al-Bukhari 4205, Sahih Muslim 2704', ar: 'صحيح البخاري ٤٢٠٥، صحيح مسلم ٢٧٠٤' },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'aref-ruqaa',
  },
  {
    id: 'dh-istighfar-100',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'A hundred times a day', ar: 'مئة مرة في اليوم' },
    arabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
    translation: 'I seek the forgiveness of Allah and repent to Him.',
    source: { en: 'Sahih al-Bukhari 6307', ar: 'صحيح البخاري ٦٣٠٧' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'dh-hamd-salihat',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'When good comes', ar: 'عند الخير' },
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ',
    translation: 'Praise be to Allah, by whose favour good deeds are completed.',
    source: { en: 'Ibn Majah 3803', ar: 'ابن ماجه ٣٨٠٣' },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'wildflowers',
    font: 'aref-ruqaa',
  },
  {
    id: 'dh-palm-tree',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'A palm tree in Paradise', ar: 'نخلة في الجنة' },
    arabic: 'سُبْحَانَ اللَّهِ الْعَظِيمِ وَبِحَمْدِهِ',
    translation:
      'Glory be to Allah the Mighty, and praise Him. For each time, a palm tree is planted in Paradise.',
    source: { en: 'At-Tirmidhi 3464', ar: 'الترمذي ٣٤٦٤' },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'forest-light',
    font: 'amiri',
  },
  {
    id: 'dh-hasbi-allah',
    category: 'evening',
    kind: 'dhikr',
    headline: { en: 'Seven times, morning and evening', ar: 'سبع مرات صباحًا ومساءً' },
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    translation:
      'Allah is sufficient for me; there is no god but He. In Him I put my trust, and He is the Lord of the Mighty Throne.',
    source: { en: 'Abu Dawud 5081', ar: 'أبو داود ٥٠٨١' },
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'dh-bismillah-protect',
    category: 'morning',
    kind: 'dhikr',
    headline: { en: 'Three times, morning and evening', ar: 'ثلاث مرات صباحًا ومساءً' },
    arabic:
      'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    translation:
      'In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.',
    source: { en: 'Abu Dawud 5088, At-Tirmidhi 3388', ar: 'أبو داود ٥٠٨٨، الترمذي ٣٣٨٨' },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'dh-rabbi-ighfir',
    category: 'dua',
    kind: 'dhikr',
    arabic: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
    translation:
      'My Lord, forgive me and accept my repentance; You are the Accepter of repentance, the Merciful.',
    source: { en: 'Abu Dawud 1516, At-Tirmidhi 3434', ar: 'أبو داود ١٥١٦، الترمذي ٣٤٣٤' },
    theme: 'burgundy-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'dh-ibrahimiyya',
    category: 'friday',
    kind: 'dhikr',
    headline: { en: 'The Ibrahimi salawat', ar: 'الصلاة الإبراهيمية' },
    arabic:
      'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    translation:
      'O Allah, send blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim; You are Praiseworthy, Glorious.',
    source: { en: 'Sahih al-Bukhari 3370', ar: 'صحيح البخاري ٣٣٧٠' },
    theme: 'emerald-night',
    decoration: 'mosque',
    font: 'amiri',
  },
  {
    id: 'dh-malik-quddus',
    category: 'evening',
    kind: 'dhikr',
    headline: { en: 'After Witr', ar: 'بعد الوتر' },
    arabic: 'سُبْحَانَ الْمَلِكِ الْقُدُّوسِ',
    translation: 'Glory be to the King, the Most Holy.',
    source: { en: "An-Nasa'i 1732", ar: 'النسائي ١٧٣٢' },
    theme: 'royal-purple',
    decoration: 'stars',
    font: 'reem-kufi',
  },
  {
    id: 'dh-allahu-akbar-kabira',
    category: 'dua',
    kind: 'dhikr',
    arabic:
      'اللَّهُ أَكْبَرُ كَبِيرًا، وَالْحَمْدُ لِلَّهِ كَثِيرًا، وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلًا',
    translation:
      'Allah is the Greatest, abundant praise be to Allah, and glory be to Allah morning and evening.',
    source: { en: 'Sahih Muslim 601', ar: 'صحيح مسلم ٦٠١' },
    theme: 'ivory-gold',
    decoration: 'none',
    font: 'reem-kufi',
  },
  {
    id: 'dh-ya-hayyu',
    category: 'morning',
    kind: 'dhikr',
    arabic:
      'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
    translation:
      'O Ever-Living, O Sustainer, by Your mercy I seek help. Set right all my affairs and do not leave me to myself even for the blink of an eye.',
    source: { en: 'Al-Hakim 1/545 (authenticated by Al-Albani)', ar: 'الحاكم ١/٥٤٥، صححه الألباني' },
    theme: 'teal-lagoon',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'dh-ilm-nafi',
    category: 'morning',
    kind: 'dhikr',
    headline: { en: 'After Fajr', ar: 'بعد صلاة الفجر' },
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    translation: 'O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.',
    source: { en: 'Ibn Majah 925', ar: 'ابن ماجه ٩٢٥' },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'river-valley',
    font: 'amiri',
  },
  {
    id: 'dh-sleep',
    category: 'evening',
    kind: 'dhikr',
    headline: { en: 'Before sleeping', ar: 'قبل النوم' },
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    translation: 'In Your name, O Allah, I die and I live.',
    source: { en: 'Sahih al-Bukhari 6324', ar: 'صحيح البخاري ٦٣٢٤' },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'starry-night',
    font: 'aref-ruqaa',
  },
  {
    id: 'dh-waking',
    category: 'morning',
    kind: 'dhikr',
    headline: { en: 'On waking up', ar: 'عند الاستيقاظ' },
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    translation:
      'Praise be to Allah who gave us life after He caused us to die, and to Him is the resurrection.',
    source: { en: 'Sahih al-Bukhari 6312', ar: 'صحيح البخاري ٦٣١٢' },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'scheherazade',
  },
  {
    id: 'dh-sayyid-istighfar',
    category: 'dua',
    kind: 'dhikr',
    headline: { en: 'The master of seeking forgiveness', ar: 'سيد الاستغفار' },
    arabic:
      'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    translation:
      'O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I keep Your covenant and promise as much as I can. I seek refuge in You from the evil I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for none forgives sins but You.',
    source: { en: 'Sahih al-Bukhari 6306', ar: 'صحيح البخاري ٦٣٠٦' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'naskh',
  },
];
