import type { Post } from '../../types';

export const duaPosts: Post[] = [
  {
    id: 'dua-rabbana-atina',
    category: 'dua',
    kind: 'dua',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    translation:
      'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',
    source: { en: 'Surah Al-Baqarah 2:201', ar: 'سورة البقرة ٢:٢٠١' },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'dua-ishrah-sadri',
    category: 'dua',
    kind: 'dua',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي ۝ وَيَسِّرْ لِي أَمْرِي',
    translation: 'My Lord, expand for me my chest and ease for me my task.',
    source: { en: 'Surah Ta-Ha 20:25-26', ar: 'سورة طه ٢٠:٢٥-٢٦' },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'aref-ruqaa',
  },
  {
    id: 'dua-huda-tuqa',
    category: 'dua',
    kind: 'dua',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
    translation: 'O Allah, I ask You for guidance, piety, chastity and self-sufficiency.',
    source: { en: 'Sahih Muslim 2721', ar: 'صحيح مسلم ٢٧٢١' },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'naskh',
  },
  {
    id: 'dua-muqallib',
    category: 'dua',
    kind: 'dua',
    arabic: 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ',
    translation: 'O Turner of hearts, make my heart firm upon Your religion.',
    source: { en: 'At-Tirmidhi 2140', ar: 'الترمذي ٢١٤٠' },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'scheherazade',
  },
  {
    id: 'dua-hasbunallah',
    category: 'dua',
    kind: 'dhikr',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    translation: 'Allah is sufficient for us, and He is the best Disposer of affairs.',
    source: { en: 'Surah Al Imran 3:173', ar: 'سورة آل عمران ٣:١٧٣' },
    theme: 'charcoal-minimal',
    decoration: 'stars',
    font: 'reem-kufi',
  },
  {
    id: 'dua-parents',
    category: 'dua',
    kind: 'dua',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translation: 'My Lord, have mercy upon them as they brought me up when I was small.',
    source: { en: 'Surah Al-Isra 17:24', ar: 'سورة الإسراء ١٧:٢٤' },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'wildflowers',
    font: 'amiri',
  },
  {
    id: 'dua-istighfar',
    category: 'dua',
    kind: 'dhikr',
    arabic:
      'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
    translation:
      'I seek forgiveness from Allah the Mighty, whom there is no god but He, the Living, the Sustainer, and I repent to Him.',
    source: { en: 'Abu Dawud 1517, At-Tirmidhi 3577', ar: 'أبو داود ١٥١٧، الترمذي ٣٥٧٧' },
    theme: 'midnight-blue',
    decoration: 'mosque',
    font: 'naskh',
  },
];
