import type { Post } from '../../types';

/** More greetings for days, seasons and life events. */
export const greetingPosts2: Post[] = [
  {
    id: 'g2-friday-dhikr',
    category: 'friday',
    kind: 'greeting',
    headline: { en: "Jumu'ah Mubarak", ar: 'جمعة مباركة' },
    arabic: 'جُمعَتُكُم مُبارَكَةٌ بِذِكرِ اللهِ وَطاعَتِه',
    translation: 'A blessed Friday to you, filled with the remembrance and obedience of Allah.',
    translations: {
      fr: "Un vendredi béni, rempli du rappel et de l'obéissance d'Allah.",
      id: 'Jumat yang berkah untuk Anda, penuh zikir dan ketaatan kepada Allah.',
      ms: 'Jumaat yang berkat untuk anda, penuh zikir dan ketaatan kepada Allah.',
      th: 'วันศุกร์อันจำเริญแด่ท่าน เปี่ยมด้วยการรำลึกและการเชื่อฟังอัลลอฮฺ',
      ur: 'آپ کو بابرکت جمعہ، جو اللہ کے ذکر اور اطاعت سے بھرپور ہو۔',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-sea',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-friday-checklist',
    category: 'friday',
    kind: 'greeting',
    headline: { en: 'Friday reminders', ar: 'لا تنسَ يوم الجمعة' },
    arabic: 'سورَةُ الكَهف، الصَّلاةُ عَلى النَّبِيِّ ﷺ، وَساعَةُ الإِجابَة',
    translation: 'Surah Al-Kahf, blessings upon the Prophet ﷺ, and the hour of acceptance.',
    translations: {
      fr: "La sourate Al-Kahf, les prières sur le Prophète ﷺ, et l'heure de l'exaucement.",
      id: 'Surah Al-Kahfi, selawat untuk Nabi ﷺ, dan saat dikabulkannya doa.',
      ms: 'Surah Al-Kahfi, selawat ke atas Nabi ﷺ, dan saat mustajab doa.',
      th: 'ซูเราะฮฺอัลกะฮฺฟฺ การเศาะละวาตแด่ท่านนบี ﷺ และช่วงเวลาที่ดุอาอ์ถูกตอบรับ',
      ur: 'سورۂ کہف، نبی ﷺ پر درود، اور قبولیت کی گھڑی۔',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'cairo',
  },
  {
    id: 'g2-friday-light',
    category: 'friday',
    kind: 'greeting',
    headline: { en: 'Friday', ar: 'يوم الجمعة' },
    arabic: 'اللَّهُمَّ نَوِّر قُلوبَنا بِالقُرآن، وَاجعَل جُمعَتَنا رَحمَةً وَغُفران',
    translation: 'O Allah, illuminate our hearts with the Quran, and make our Friday mercy and forgiveness.',
    translations: {
      fr: 'Ô Allah, illumine nos cœurs par le Coran, et fais de notre vendredi miséricorde et pardon.',
      id: "Ya Allah, terangilah hati kami dengan Al-Qur'an, dan jadikanlah Jumat kami penuh rahmat dan ampunan.",
      ms: 'Ya Allah, sinarilah hati kami dengan Al-Quran, dan jadikanlah Jumaat kami penuh rahmat dan keampunan.',
      th: 'โอ้อัลลอฮฺ ขอทรงให้หัวใจของเราสว่างด้วยอัลกุรอาน และให้วันศุกร์ของเราเป็นความเมตตาและการอภัย',
      ur: 'اے اللہ، ہمارے دلوں کو قرآن سے روشن کر دے، اور ہمارے جمعہ کو رحمت و مغفرت بنا دے۔',
    },
    theme: 'teal-lagoon',
    decoration: 'mosque',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-morning-baraka',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'Good morning', ar: 'صباح الخير' },
    arabic: 'اللَّهُمَّ اجعَل هذا اليَومَ خَيرًا وَبَرَكَةً وَرِزقًا واسِعًا',
    translation: 'O Allah, make this day full of goodness, blessing and abundant provision.',
    translations: {
      fr: 'Ô Allah, fais de ce jour un jour de bien, de bénédiction et de subsistance abondante.',
      id: 'Ya Allah, jadikanlah hari ini penuh kebaikan, keberkahan, dan rezeki yang melimpah.',
      ms: 'Ya Allah, jadikanlah hari ini penuh kebaikan, keberkatan dan rezeki yang melimpah.',
      th: 'โอ้อัลลอฮฺ ขอทรงให้วันนี้เต็มไปด้วยความดี ความจำเริญ และปัจจัยยังชีพอันมากมาย',
      ur: 'اے اللہ، اس دن کو بھلائی، برکت اور فراخ رزق سے بھر دے۔',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'cairo',
  },
  {
    id: 'g2-morning-optimism',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'A hopeful morning', ar: 'صباح التفاؤل' },
    arabic: 'صَباحُ الرِّضا وَالتَّفاؤُل، وَقَلبٌ مُطمَئِنٌّ بِذِكرِ الله',
    translation: 'A morning of contentment and hope, and a heart at peace with the remembrance of Allah.',
    translations: {
      fr: "Un matin de contentement et d'espoir, et un cœur apaisé par le rappel d'Allah.",
      id: 'Pagi yang penuh rida dan harapan, serta hati yang tenteram dengan zikir kepada Allah.',
      ms: 'Pagi yang penuh reda dan harapan, serta hati yang tenteram dengan zikir kepada Allah.',
      th: 'เช้าแห่งความพอใจและความหวัง และหัวใจที่สงบด้วยการรำลึกถึงอัลลอฮฺ',
      ur: 'رضا اور امید والی صبح، اور اللہ کے ذکر سے مطمئن دل۔',
    },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-morning-happy-day',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'Have a blessed day', ar: 'يومكم سعيد' },
    arabic: 'يَومُكُم سَعيدٌ بِذِكرِ الله، وَمُبارَكٌ بِطاعَتِه',
    translation: 'May your day be happy with the remembrance of Allah and blessed with His obedience.',
    translations: {
      fr: "Que votre journée soit heureuse par le rappel d'Allah et bénie par Son obéissance.",
      id: 'Semoga hari Anda bahagia dengan zikir kepada Allah dan berkah dengan ketaatan kepada-Nya.',
      ms: 'Semoga hari anda bahagia dengan zikir kepada Allah dan berkat dengan ketaatan kepada-Nya.',
      th: 'ขอให้วันของท่านเป็นสุขด้วยการรำลึกถึงอัลลอฮฺ และจำเริญด้วยการเชื่อฟังพระองค์',
      ur: 'آپ کا دن اللہ کے ذکر سے خوشگوار اور اس کی اطاعت سے بابرکت ہو۔',
    },
    theme: 'olive-sage',
    decoration: 'sunrise',
    font: 'cairo',
  },
  {
    id: 'g2-evening-fitrah',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Good evening', ar: 'مساء الخير' },
    arabic: 'أَمسَينا عَلى فِطرَةِ الإِسلام، وَكَلِمَةِ الإِخلاص، وَدينِ نَبِيِّنا مُحَمَّدٍ ﷺ',
    translation:
      'We have reached the evening upon the natural way of Islam, the word of sincerity, and the religion of our Prophet Muhammad ﷺ.',
    translations: {
      fr: "Nous voici au soir sur la nature première de l'islam, la parole de sincérité, et la religion de notre Prophète Muhammad ﷺ.",
      id: 'Kami memasuki petang di atas fitrah Islam, kalimat ikhlas, dan agama Nabi kami Muhammad ﷺ.',
      ms: 'Kami memasuki petang di atas fitrah Islam, kalimah ikhlas, dan agama Nabi kami Muhammad ﷺ.',
      th: 'เราเข้าสู่ยามเย็นบนฟิฏเราะฮฺแห่งอิสลาม ถ้อยคำแห่งความบริสุทธิ์ใจ และศาสนาของนบีมุฮัมมัด ﷺ ของเรา',
      ur: 'ہم نے شام کی اسلام کی فطرت، کلمۂ اخلاص، اور اپنے نبی محمد ﷺ کے دین پر۔',
    },
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'g2-evening-rest',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Good night', ar: 'تصبحون على خير' },
    arabic: 'اللَّهُمَّ اجعَل لَيلَتَنا راحَةً وَسَكينَة، وَنَومَنا عِبادَةً وَطُمَأنينَة',
    translation: 'O Allah, make our night rest and tranquility, and our sleep worship and peace.',
    translations: {
      fr: 'Ô Allah, fais de notre nuit repos et quiétude, et de notre sommeil adoration et paix.',
      id: 'Ya Allah, jadikanlah malam kami istirahat dan ketenangan, dan tidur kami ibadah dan kedamaian.',
      ms: 'Ya Allah, jadikanlah malam kami rehat dan ketenangan, dan tidur kami ibadah dan kedamaian.',
      th: 'โอ้อัลลอฮฺ ขอทรงให้ค่ำคืนของเราเป็นการพักผ่อนและความสงบ และการนอนของเราเป็นอิบาดะฮฺและสันติ',
      ur: 'اے اللہ، ہماری رات کو آرام و سکون، اور ہماری نیند کو عبادت و اطمینان بنا دے۔',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'starry-night',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-evening-mercy',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Evening', ar: 'مساء الرحمة' },
    arabic: 'مَساءٌ يَملَؤُهُ الرِّضا، وَقَلبٌ يَسكُنُهُ الإيمان',
    translation: 'An evening filled with contentment, and a heart in which faith dwells.',
    translations: {
      fr: 'Une soirée emplie de contentement, et un cœur où demeure la foi.',
      id: 'Petang yang penuh keridaan, dan hati yang di dalamnya bersemayam iman.',
      ms: 'Petang yang penuh keredaan, dan hati yang di dalamnya bersemayam iman.',
      th: 'ยามเย็นที่เปี่ยมด้วยความพอใจ และหัวใจที่มีศรัทธาสถิตอยู่',
      ur: 'رضا سے بھری شام، اور وہ دل جس میں ایمان بسا ہو۔',
    },
    theme: 'charcoal-minimal',
    decoration: 'crescent',
    font: 'cairo',
  },
  {
    id: 'g2-ramadan-first',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan has arrived', ar: 'أول رمضان' },
    arabic: 'اللَّهُمَّ بَلِّغنا صِيامَهُ وَقِيامَه، وَاجعَلنا فيهِ مِنَ المَقبولين',
    translation: 'O Allah, let us reach its fasting and its night prayers, and make us among the accepted.',
    translations: {
      fr: 'Ô Allah, fais que nous atteignions son jeûne et ses veillées, et compte-nous parmi ceux qui sont agréés.',
      id: 'Ya Allah, sampaikanlah kami pada puasanya dan qiyamnya, dan jadikanlah kami termasuk yang diterima.',
      ms: 'Ya Allah, sampaikanlah kami kepada puasanya dan qiamnya, dan jadikanlah kami tergolong yang diterima.',
      th: 'โอ้อัลลอฮฺ ขอให้เราได้ถือศีลอดและละหมาดกิยามในเดือนนี้ และให้เราอยู่ในหมู่ผู้ที่ถูกตอบรับ',
      ur: 'اے اللہ، ہمیں اس کے روزے اور قیام تک پہنچا، اور ہمیں مقبول بندوں میں شامل فرما۔',
    },
    theme: 'emerald-night',
    decoration: 'lanterns',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-ramadan-family',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan Kareem', ar: 'رمضان كريم' },
    arabic: 'رَمَضانُ كَريمٌ لَكُم وَلِعائِلَتِكُم، وَكُلُّ عامٍ وَأَنتُم إِلى اللهِ أَقرَب',
    translation: 'Ramadan Kareem to you and your family. Every year may you be closer to Allah.',
    translations: {
      fr: "Ramadan Karim à vous et à votre famille. Que chaque année vous rapproche d'Allah.",
      id: 'Ramadan Karim untuk Anda dan keluarga. Setiap tahun semoga Anda semakin dekat kepada Allah.',
      ms: 'Ramadan Karim untuk anda dan keluarga. Setiap tahun semoga anda semakin dekat kepada Allah.',
      th: 'รอมฎอนกะรีมแด่ท่านและครอบครัว ขอให้ทุกปีท่านใกล้ชิดอัลลอฮฺยิ่งขึ้น',
      ur: 'آپ کو اور آپ کے گھر والوں کو رمضان کریم۔ ہر سال آپ اللہ کے اور قریب ہوں۔',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'cairo',
  },
  {
    id: 'g2-ramadan-last-ten',
    category: 'laylat-al-qadr',
    kind: 'greeting',
    headline: { en: 'The last ten nights', ar: 'العشر الأواخر' },
    arabic: 'اللَّهُمَّ اجعَلنا مِن عُتَقائِكَ مِنَ النّار، وَبَلِّغنا لَيلَةَ القَدر',
    translation: 'O Allah, make us among those You free from the Fire, and let us reach the Night of Decree.',
    translations: {
      fr: 'Ô Allah, compte-nous parmi ceux que Tu affranchis du Feu, et fais que nous atteignions la Nuit du Destin.',
      id: 'Ya Allah, jadikanlah kami termasuk orang yang Engkau bebaskan dari api neraka, dan sampaikanlah kami pada Lailatul Qadar.',
      ms: 'Ya Allah, jadikanlah kami tergolong orang yang Engkau bebaskan daripada api neraka, dan sampaikanlah kami kepada Lailatulqadar.',
      th: 'โอ้อัลลอฮฺ ขอทรงให้เราอยู่ในหมู่ผู้ที่พระองค์ทรงปลดปล่อยจากไฟนรก และให้เราได้พบค่ำคืนลัยละตุลก็อดรฺ',
      ur: 'اے اللہ، ہمیں ان میں شامل کر جنہیں تُو آگ سے آزاد کرتا ہے، اور ہمیں شبِ قدر نصیب فرما۔',
    },
    theme: 'midnight-blue',
    decoration: 'lanterns',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-ramadan-farewell',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Farewell Ramadan', ar: 'وداعًا رمضان' },
    arabic: 'اللَّهُمَّ لا تَجعَلهُ آخِرَ العَهدِ بِرَمَضان، وَتَقَبَّل مِنّا صِيامَهُ وَقِيامَه',
    translation: 'O Allah, do not let this be our last Ramadan, and accept from us its fasting and prayers.',
    translations: {
      fr: 'Ô Allah, ne fais pas de ce Ramadan notre dernier, et accepte de nous son jeûne et ses prières.',
      id: 'Ya Allah, jangan jadikan ini Ramadan terakhir kami, dan terimalah puasa serta salat kami.',
      ms: 'Ya Allah, jangan jadikan ini Ramadan terakhir kami, dan terimalah puasa serta solat kami.',
      th: 'โอ้อัลลอฮฺ ขออย่าให้นี่เป็นรอมฎอนสุดท้ายของเรา และขอทรงตอบรับการถือศีลอดและการละหมาดของเรา',
      ur: 'اے اللہ، یہ ہمارا آخری رمضان نہ بنانا، اور ہمارے روزے اور نمازیں قبول فرما۔',
    },
    theme: 'burgundy-gold',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'g2-fitr-happy',
    category: 'eid-al-fitr',
    kind: 'greeting',
    headline: { en: 'Happy Eid', ar: 'عيد سعيد' },
    arabic: 'عيدٌ سَعيدٌ وَأَيّامٌ مُبارَكَة، أَعادَهُ اللهُ عَلَيكُم بِالخَيرِ وَالبَرَكات',
    translation: 'A happy Eid and blessed days. May Allah bring it back to you with goodness and blessings.',
    translations: {
      fr: "Un joyeux Aïd et des jours bénis. Qu'Allah vous le ramène avec bien et bénédiction.",
      id: 'Selamat Idulfitri dan hari-hari yang berkah. Semoga Allah mengembalikannya kepada Anda dengan kebaikan dan keberkahan.',
      ms: 'Selamat Aidilfitri dan hari-hari yang berkat. Semoga Allah mengembalikannya kepada anda dengan kebaikan dan keberkatan.',
      th: 'อีดที่เปี่ยมสุขและวันคืนอันจำเริญ ขออัลลอฮฺทรงนำมันกลับมาสู่ท่านพร้อมความดีและความจำเริญ',
      ur: 'عید مبارک اور بابرکت دن۔ اللہ اسے آپ پر خیر و برکت کے ساتھ لوٹائے۔',
    },
    theme: 'teal-lagoon',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-fitr-morning',
    category: 'eid-al-fitr',
    kind: 'greeting',
    headline: { en: 'Eid morning', ar: 'صباح العيد' },
    arabic: 'صَباحُ العيد، صَباحُ الفَرَحِ وَالتَّكبير، عيدُكُم مُبارَك',
    translation: 'The morning of Eid, a morning of joy and takbeer. Eid Mubarak.',
    translations: {
      fr: "Le matin de l'Aïd, un matin de joie et de takbir. Aïd Moubarak.",
      id: 'Pagi Idulfitri, pagi yang penuh suka cita dan takbir. Selamat Idulfitri.',
      ms: 'Pagi Aidilfitri, pagi yang penuh kegembiraan dan takbir. Selamat Aidilfitri.',
      th: 'เช้าวันอีด เช้าแห่งความยินดีและเสียงตักบีร อีดมุบาร็อก',
      ur: 'عید کی صبح، خوشی اور تکبیر کی صبح۔ عید مبارک۔',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-adha-sacrifice',
    category: 'eid-al-adha',
    kind: 'greeting',
    headline: { en: 'Eid al-Adha', ar: 'عيد الأضحى' },
    arabic: 'أَضحى مُبارَك، تَقَبَّلَ اللهُ أَضاحِيَكُم وَطاعاتِكُم',
    translation: 'A blessed Eid al-Adha. May Allah accept your sacrifices and your worship.',
    translations: {
      fr: "Un Aïd al-Adha béni. Qu'Allah accepte vos sacrifices et vos adorations.",
      id: 'Iduladha yang berkah. Semoga Allah menerima kurban dan ibadah Anda.',
      ms: 'Aidiladha yang berkat. Semoga Allah menerima korban dan ibadah anda.',
      th: 'อีดิลอัฎฮาอันจำเริญ ขออัลลอฮฺทรงตอบรับการเชือดพลีและการอิบาดะฮฺของท่าน',
      ur: 'بابرکت عید الاضحیٰ۔ اللہ آپ کی قربانیاں اور عبادات قبول فرمائے۔',
    },
    theme: 'emerald-night',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-hajj-return',
    category: 'dhul-hijjah',
    kind: 'greeting',
    headline: { en: 'Welcome back, Hajji', ar: 'حجًا مبرورًا' },
    arabic: 'حَجًّا مَبرورًا وَعَودَةً سَعيدَة، تَقَبَّلَ اللهُ مِنكُم',
    translation: 'An accepted Hajj and a happy return. May Allah accept from you.',
    translations: {
      fr: "Un Hajj agréé et un heureux retour. Qu'Allah accepte de vous.",
      id: 'Haji yang mabrur dan kepulangan yang bahagia. Semoga Allah menerima amal Anda.',
      ms: 'Haji yang mabrur dan pulang dengan bahagia. Semoga Allah menerima amalan anda.',
      th: 'ฮัจญ์ที่ถูกตอบรับและการกลับมาอย่างเป็นสุข ขออัลลอฮฺทรงตอบรับจากท่าน',
      ur: 'حج مبرور اور خوشی سے واپسی۔ اللہ آپ سے قبول فرمائے۔',
    },
    theme: 'ivory-gold',
    decoration: 'kaaba',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-arafah-greeting',
    category: 'dhul-hijjah',
    kind: 'greeting',
    headline: { en: 'Day of Arafah', ar: 'يوم عرفة' },
    arabic: 'اللَّهُمَّ في يَومِ عَرَفَة اغفِر لَنا وَلِوالِدينا وَلِلمُسلِمين',
    translation: 'O Allah, on the Day of Arafah forgive us, our parents and all Muslims.',
    translations: {
      fr: "Ô Allah, au jour de Arafat, pardonne-nous, ainsi qu'à nos parents et à tous les musulmans.",
      id: 'Ya Allah, pada hari Arafah ampunilah kami, kedua orang tua kami, dan seluruh kaum muslimin.',
      ms: 'Ya Allah, pada hari Arafah ampunilah kami, kedua ibu bapa kami, dan seluruh kaum muslimin.',
      th: 'โอ้อัลลอฮฺ ในวันอะเราะฟะฮฺ ขอทรงอภัยแก่เรา บิดามารดาของเรา และมุสลิมทั้งมวล',
      ur: 'اے اللہ، یومِ عرفہ میں ہمیں، ہمارے والدین کو اور تمام مسلمانوں کو بخش دے۔',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'cairo',
  },
  {
    id: 'g2-hijri-year',
    category: 'muharram',
    kind: 'greeting',
    headline: { en: 'New Hijri year', ar: 'عام هجري سعيد' },
    arabic: 'عامٌ هِجرِيٌّ سَعيد، اللَّهُمَّ اجعَلهُ عامَ نَصرٍ وَعِزٍّ وَتَمكين',
    translation: 'A happy Hijri year. O Allah, make it a year of victory, honour and strength.',
    translations: {
      fr: "Bonne année hégirienne. Ô Allah, fais-en une année de victoire, d'honneur et de force.",
      id: 'Selamat tahun baru Hijriah. Ya Allah, jadikanlah tahun kemenangan, kemuliaan, dan kekuatan.',
      ms: 'Selamat tahun baharu Hijrah. Ya Allah, jadikanlah tahun kemenangan, kemuliaan dan kekuatan.',
      th: 'สวัสดีปีใหม่ฮิจเราะฮฺ โอ้อัลลอฮฺ ขอทรงให้เป็นปีแห่งชัยชนะ เกียรติยศ และความเข้มแข็ง',
      ur: 'نیا ہجری سال مبارک۔ اے اللہ، اسے فتح، عزت اور قوت کا سال بنا دے۔',
    },
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'cairo',
  },
  {
    id: 'g2-isra-greeting',
    category: 'isra-miraj',
    kind: 'greeting',
    headline: { en: "Isra and Mi'raj", ar: 'ذكرى الإسراء والمعراج' },
    arabic: 'في ذِكرى الإِسراءِ وَالمِعراج، اللَّهُمَّ ارزُقنا الصَّلاةَ في المَسجِدِ الأَقصى',
    translation: "On the anniversary of the Isra and Mi'raj: O Allah, grant us prayer in Al-Aqsa Mosque.",
    theme: 'royal-purple',
    decoration: 'mosque',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-newborn-girl',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'A baby girl', ar: 'مولودة جديدة' },
    arabic: 'بارَكَ اللهُ لَكُم فِي المَوهوبَة، وَجَعَلَها مِنَ الصّالِحات',
    translation: 'May Allah bless you in the girl He has given you, and make her among the righteous.',
    translations: {
      fr: "Qu'Allah vous bénisse dans la fille qu'Il vous a donnée, et qu'Il la compte parmi les vertueux.",
      id: 'Semoga Allah memberkahi Anda dengan putri yang dianugerahkan-Nya, dan menjadikannya termasuk orang salih.',
      ms: 'Semoga Allah memberkati anda dengan puteri yang dikurniakan-Nya, dan menjadikannya tergolong orang soleh.',
      th: 'ขออัลลอฮฺทรงประทานความจำเริญแก่ท่านในบุตรสาวที่พระองค์ประทานให้ และทรงให้นางอยู่ในหมู่คนดี',
      ur: 'اللہ آپ کو عطا کی ہوئی بیٹی میں برکت دے، اور اسے نیک بندوں میں شامل کرے۔',
    },
    theme: 'rose-gold',
    decoration: 'stars',
    font: 'cairo',
  },
  {
    id: 'g2-new-home',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'New home', ar: 'بيت جديد' },
    arabic: 'مُبارَكٌ البَيتُ الجَديد، اللَّهُمَّ بارِك لَهُم فيهِ وَاملَأهُ سَكينَةً وَرِزقًا',
    translation:
      'Congratulations on the new home. O Allah, bless them in it and fill it with tranquility and provision.',
    translations: {
      fr: 'Félicitations pour la nouvelle maison. Ô Allah, bénis-les en elle et emplis-la de quiétude et de subsistance.',
      id: 'Selamat atas rumah baru. Ya Allah, berkahilah mereka di dalamnya dan penuhilah dengan ketenangan dan rezeki.',
      ms: 'Tahniah atas rumah baharu. Ya Allah, berkatilah mereka di dalamnya dan penuhilah dengan ketenangan dan rezeki.',
      th: 'ยินดีกับบ้านหลังใหม่ โอ้อัลลอฮฺ ขอทรงประทานความจำเริญแก่พวกเขาในบ้านนี้ และเติมเต็มด้วยความสงบและปัจจัยยังชีพ',
      ur: 'نئے گھر کی مبارکباد۔ اے اللہ، انہیں اس میں برکت دے اور اسے سکون اور رزق سے بھر دے۔',
    },
    theme: 'olive-sage',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-graduation',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Graduation', ar: 'مبارك التخرج' },
    arabic: 'أَلفُ مَبروكٍ التَّخَرُّج، اللَّهُمَّ وَفِّقهُ لِما تُحِبُّ وَتَرضى',
    translation:
      'Congratulations on graduating. O Allah, grant success in what You love and are pleased with.',
    translations: {
      fr: 'Félicitations pour votre diplôme. Ô Allah, accorde la réussite en ce que Tu aimes et agrées.',
      id: 'Selamat atas kelulusan Anda. Ya Allah, berikanlah taufik pada apa yang Engkau cintai dan ridai.',
      ms: 'Tahniah atas kelulusan anda. Ya Allah, berikanlah taufik pada apa yang Engkau cintai dan redai.',
      th: 'ยินดีกับการสำเร็จการศึกษา โอ้อัลลอฮฺ ขอทรงประทานความสำเร็จในสิ่งที่พระองค์ทรงรักและพอพระทัย',
      ur: 'فراغت کی مبارکباد۔ اے اللہ، اُس کام میں توفیق دے جو تجھے محبوب اور پسندیدہ ہو۔',
    },
    theme: 'teal-lagoon',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-new-job',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'New job', ar: 'عمل جديد' },
    arabic: 'مُبارَكٌ العَمَلُ الجَديد، اللَّهُمَّ ارزُقهُ الإِخلاصَ وَالتَّوفيقَ وَالبَرَكَة',
    translation: 'Congratulations on the new job. O Allah, grant sincerity, success and blessing.',
    translations: {
      fr: 'Félicitations pour le nouveau travail. Ô Allah, accorde sincérité, réussite et bénédiction.',
      id: 'Selamat atas pekerjaan baru. Ya Allah, berikanlah keikhlasan, keberhasilan, dan keberkahan.',
      ms: 'Tahniah atas pekerjaan baharu. Ya Allah, berikanlah keikhlasan, kejayaan dan keberkatan.',
      th: 'ยินดีกับงานใหม่ โอ้อัลลอฮฺ ขอทรงประทานความบริสุทธิ์ใจ ความสำเร็จ และความจำเริญ',
      ur: 'نئی ملازمت مبارک ہو۔ اے اللہ، اخلاص، کامیابی اور برکت عطا فرما۔',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'cairo',
  },
  {
    id: 'g2-engagement',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Engagement', ar: 'مبارك الخطوبة' },
    arabic: 'مُبارَكٌ لَكُما، اللَّهُمَّ أَتمِم لَهُما عَلى خَير',
    translation: 'Congratulations to you both. O Allah, bring it to completion with goodness.',
    translations: {
      fr: 'Félicitations à vous deux. Ô Allah, mène cela à son terme dans le bien.',
      id: 'Selamat untuk kalian berdua. Ya Allah, sempurnakanlah dengan kebaikan.',
      ms: 'Tahniah kepada anda berdua. Ya Allah, sempurnakanlah dengan kebaikan.',
      th: 'ยินดีกับทั้งสองท่าน โอ้อัลลอฮฺ ขอทรงให้สำเร็จลุล่วงด้วยความดีงาม',
      ur: 'آپ دونوں کو مبارک ہو۔ اے اللہ، اسے خیر کے ساتھ پایۂ تکمیل تک پہنچا۔',
    },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'lavender-field',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-safe-return',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Welcome home', ar: 'الحمد لله على السلامة' },
    arabic: 'الحَمدُ لِلهِ عَلى السَّلامَة، وَحَمدًا لِلهِ عَلى عَودَتِكَ بِخَير',
    translation: 'Praise be to Allah for your safety, and praise be to Allah for your safe return.',
    translations: {
      fr: 'Louange à Allah pour votre sécurité, et louange à Allah pour votre retour sain et sauf.',
      id: 'Segala puji bagi Allah atas keselamatan Anda, dan segala puji bagi Allah atas kepulangan Anda dengan selamat.',
      ms: 'Segala puji bagi Allah atas keselamatan anda, dan segala puji bagi Allah atas kepulangan anda dengan selamat.',
      th: 'การสรรเสริญเป็นของอัลลอฮฺที่ท่านปลอดภัย และการสรรเสริญเป็นของอัลลอฮฺที่ท่านกลับมาโดยสวัสดิภาพ',
      ur: 'آپ کی سلامتی پر اللہ کا شکر، اور آپ کی بخیریت واپسی پر اللہ کا شکر۔',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'river-valley',
    font: 'cairo',
  },
  {
    id: 'g2-recovery-2',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Get well soon', ar: 'شفاك الله' },
    arabic: 'شَفاكَ اللهُ وَعافاك، وَأَلبَسَكَ ثَوبَ الصِّحَّةِ وَالعافِيَة',
    translation: 'May Allah heal you and grant you well-being, and clothe you in health.',
    translations: {
      fr: "Qu'Allah vous guérisse, vous accorde la santé et vous revête de bien-être.",
      id: 'Semoga Allah menyembuhkan Anda, memberi Anda kesehatan, dan menganugerahkan afiat.',
      ms: 'Semoga Allah menyembuhkan anda, memberi anda kesihatan, dan menganugerahkan afiat.',
      th: 'ขออัลลอฮฺทรงบำบัดท่าน ประทานสุขภาพและความปลอดภัยแก่ท่าน',
      ur: 'اللہ آپ کو شفا دے، عافیت عطا کرے اور صحت سے نوازے۔',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'forest-light',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-condolence-2',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Condolences', ar: 'عظم الله أجركم' },
    arabic: 'عَظَّمَ اللهُ أَجرَكُم، وَأَحسَنَ عَزاءَكُم، وَغَفَرَ لِمَيِّتِكُم',
    translation: 'May Allah magnify your reward, grant you good consolation, and forgive your deceased.',
    translations: {
      fr: "Qu'Allah augmente votre récompense, vous accorde un beau réconfort et pardonne à votre défunt.",
      id: 'Semoga Allah membesarkan pahala Anda, memberi penghiburan yang baik, dan mengampuni almarhum Anda.',
      ms: 'Semoga Allah membesarkan pahala anda, memberi ketenangan yang baik, dan mengampuni arwah anda.',
      th: 'ขออัลลอฮฺทรงเพิ่มพูนผลบุญแก่ท่าน ประทานการปลอบประโลมที่ดี และทรงอภัยแก่ผู้วายชนม์ของท่าน',
      ur: 'اللہ آپ کا اجر بڑھائے، اچھی تسلی دے، اور آپ کے مرحوم کو بخش دے۔',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'naskh',
  },
];
