import type { Post } from '../../types';

/** More greetings for days, seasons and life events. */
export const greetingPosts2: Post[] = [
  {
    id: 'g2-friday-dhikr',
    category: 'friday',
    kind: 'greeting',
    headline: { en: "Jumu'ah Mubarak", ar: 'جمعة مباركة' },
    arabic: 'جُمعَتُكُم مُبارَكَةٌ بِذِكرِ اللهِ وَطاعَتِه',
    translation: 'A blessed Friday to you, filled with the remembrance and obedience of Allah.',
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-sea',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-friday-checklist',
    category: 'friday',
    kind: 'greeting',
    headline: { en: 'Friday reminders', ar: 'لا تنسَ يوم الجمعة' },
    arabic: 'سورَةُ الكَهف، الصَّلاةُ عَلى النَّبِيِّ ﷺ، وَساعَةُ الإِجابَة',
    translation: 'Surah Al-Kahf, blessings upon the Prophet ﷺ, and the hour of acceptance.',
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'cairo',
  },
  {
    id: 'g2-friday-light',
    category: 'friday',
    kind: 'greeting',
    headline: { en: 'Friday', ar: 'يوم الجمعة' },
    arabic: 'اللَّهُمَّ نَوِّر قُلوبَنا بِالقُرآن، وَاجعَل جُمعَتَنا رَحمَةً وَغُفران',
    translation: 'O Allah, illuminate our hearts with the Quran, and make our Friday mercy and forgiveness.',
    theme: 'teal-lagoon',
    decoration: 'mosque',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-morning-baraka',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'Good morning', ar: 'صباح الخير' },
    arabic: 'اللَّهُمَّ اجعَل هذا اليَومَ خَيرًا وَبَرَكَةً وَرِزقًا واسِعًا',
    translation: 'O Allah, make this day full of goodness, blessing and abundant provision.',
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'cairo',
  },
  {
    id: 'g2-morning-optimism',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'A hopeful morning', ar: 'صباح التفاؤل' },
    arabic: 'صَباحُ الرِّضا وَالتَّفاؤُل، وَقَلبٌ مُطمَئِنٌّ بِذِكرِ الله',
    translation: 'A morning of contentment and hope, and a heart at peace with the remembrance of Allah.',
    theme: 'rose-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-morning-happy-day',
    category: 'morning',
    kind: 'greeting',
    headline: { en: 'Have a blessed day', ar: 'يومكم سعيد' },
    arabic: 'يَومُكُم سَعيدٌ بِذِكرِ الله، وَمُبارَكٌ بِطاعَتِه',
    translation: 'May your day be happy with the remembrance of Allah and blessed with His obedience.',
    theme: 'olive-sage',
    decoration: 'sunrise',
    font: 'cairo',
  },
  {
    id: 'g2-evening-fitrah',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Good evening', ar: 'مساء الخير' },
    arabic: 'أَمسَينا عَلى فِطرَةِ الإِسلام، وَكَلِمَةِ الإِخلاص، وَدينِ نَبِيِّنا مُحَمَّدٍ ﷺ',
    translation:
      'We have reached the evening upon the natural way of Islam, the word of sincerity, and the religion of our Prophet Muhammad ﷺ.',
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'g2-evening-rest',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Good night', ar: 'تصبحون على خير' },
    arabic: 'اللَّهُمَّ اجعَل لَيلَتَنا راحَةً وَسَكينَة، وَنَومَنا عِبادَةً وَطُمَأنينَة',
    translation: 'O Allah, make our night rest and tranquility, and our sleep worship and peace.',
    theme: 'royal-purple',
    decoration: 'none',
    background: 'starry-night',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-evening-mercy',
    category: 'evening',
    kind: 'greeting',
    headline: { en: 'Evening', ar: 'مساء الرحمة' },
    arabic: 'مَساءٌ يَملَؤُهُ الرِّضا، وَقَلبٌ يَسكُنُهُ الإيمان',
    translation: 'An evening filled with contentment, and a heart in which faith dwells.',
    theme: 'charcoal-minimal',
    decoration: 'crescent',
    font: 'cairo',
  },
  {
    id: 'g2-ramadan-first',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan has arrived', ar: 'أول رمضان' },
    arabic: 'اللَّهُمَّ بَلِّغنا صِيامَهُ وَقِيامَه، وَاجعَلنا فيهِ مِنَ المَقبولين',
    translation: 'O Allah, let us reach its fasting and its night prayers, and make us among the accepted.',
    theme: 'emerald-night',
    decoration: 'lanterns',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-ramadan-family',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan Kareem', ar: 'رمضان كريم' },
    arabic: 'رَمَضانُ كَريمٌ لَكُم وَلِعائِلَتِكُم، وَكُلُّ عامٍ وَأَنتُم إِلى اللهِ أَقرَب',
    translation: 'Ramadan Kareem to you and your family. Every year may you be closer to Allah.',
    theme: 'royal-purple',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'cairo',
  },
  {
    id: 'g2-ramadan-last-ten',
    category: 'laylat-al-qadr',
    kind: 'greeting',
    headline: { en: 'The last ten nights', ar: 'العشر الأواخر' },
    arabic: 'اللَّهُمَّ اجعَلنا مِن عُتَقائِكَ مِنَ النّار، وَبَلِّغنا لَيلَةَ القَدر',
    translation: 'O Allah, make us among those You free from the Fire, and let us reach the Night of Decree.',
    theme: 'midnight-blue',
    decoration: 'lanterns',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-ramadan-farewell',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Farewell Ramadan', ar: 'وداعًا رمضان' },
    arabic: 'اللَّهُمَّ لا تَجعَلهُ آخِرَ العَهدِ بِرَمَضان، وَتَقَبَّل مِنّا صِيامَهُ وَقِيامَه',
    translation: 'O Allah, do not let this be our last Ramadan, and accept from us its fasting and prayers.',
    theme: 'burgundy-gold',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'g2-fitr-happy',
    category: 'eid-al-fitr',
    kind: 'greeting',
    headline: { en: 'Happy Eid', ar: 'عيد سعيد' },
    arabic: 'عيدٌ سَعيدٌ وَأَيّامٌ مُبارَكَة، أَعادَهُ اللهُ عَلَيكُم بِالخَيرِ وَالبَرَكات',
    translation: 'A happy Eid and blessed days. May Allah bring it back to you with goodness and blessings.',
    theme: 'teal-lagoon',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-fitr-morning',
    category: 'eid-al-fitr',
    kind: 'greeting',
    headline: { en: 'Eid morning', ar: 'صباح العيد' },
    arabic: 'صَباحُ العيد، صَباحُ الفَرَحِ وَالتَّكبير، عيدُكُم مُبارَك',
    translation: 'The morning of Eid, a morning of joy and takbeer. Eid Mubarak.',
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-adha-sacrifice',
    category: 'eid-al-adha',
    kind: 'greeting',
    headline: { en: 'Eid al-Adha', ar: 'عيد الأضحى' },
    arabic: 'أَضحى مُبارَك، تَقَبَّلَ اللهُ أَضاحِيَكُم وَطاعاتِكُم',
    translation: 'A blessed Eid al-Adha. May Allah accept your sacrifices and your worship.',
    theme: 'emerald-night',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-hajj-return',
    category: 'dhul-hijjah',
    kind: 'greeting',
    headline: { en: 'Welcome back, Hajji', ar: 'حجًا مبرورًا' },
    arabic: 'حَجًّا مَبرورًا وَعَودَةً سَعيدَة، تَقَبَّلَ اللهُ مِنكُم',
    translation: 'An accepted Hajj and a happy return. May Allah accept from you.',
    theme: 'ivory-gold',
    decoration: 'kaaba',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-arafah-greeting',
    category: 'dhul-hijjah',
    kind: 'greeting',
    headline: { en: 'Day of Arafah', ar: 'يوم عرفة' },
    arabic: 'اللَّهُمَّ في يَومِ عَرَفَة اغفِر لَنا وَلِوالِدينا وَلِلمُسلِمين',
    translation: 'O Allah, on the Day of Arafah forgive us, our parents and all Muslims.',
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'cairo',
  },
  {
    id: 'g2-hijri-year',
    category: 'muharram',
    kind: 'greeting',
    headline: { en: 'New Hijri year', ar: 'عام هجري سعيد' },
    arabic: 'عامٌ هِجرِيٌّ سَعيد، اللَّهُمَّ اجعَلهُ عامَ نَصرٍ وَعِزٍّ وَتَمكين',
    translation: 'A happy Hijri year. O Allah, make it a year of victory, honour and strength.',
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'cairo',
  },
  {
    id: 'g2-isra-greeting',
    category: 'isra-miraj',
    kind: 'greeting',
    headline: { en: "Isra and Mi'raj", ar: 'ذكرى الإسراء والمعراج' },
    arabic: 'في ذِكرى الإِسراءِ وَالمِعراج، اللَّهُمَّ ارزُقنا الصَّلاةَ في المَسجِدِ الأَقصى',
    translation: "On the anniversary of the Isra and Mi'raj: O Allah, grant us prayer in Al-Aqsa Mosque.",
    theme: 'royal-purple',
    decoration: 'mosque',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-newborn-girl',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'A baby girl', ar: 'مولودة جديدة' },
    arabic: 'بارَكَ اللهُ لَكُم فِي المَوهوبَة، وَجَعَلَها مِنَ الصّالِحات',
    translation: 'May Allah bless you in the girl He has given you, and make her among the righteous.',
    theme: 'rose-gold',
    decoration: 'stars',
    font: 'cairo',
  },
  {
    id: 'g2-new-home',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'New home', ar: 'بيت جديد' },
    arabic: 'مُبارَكٌ البَيتُ الجَديد، اللَّهُمَّ بارِك لَهُم فيهِ وَاملَأهُ سَكينَةً وَرِزقًا',
    translation:
      'Congratulations on the new home. O Allah, bless them in it and fill it with tranquility and provision.',
    theme: 'olive-sage',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-graduation',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Graduation', ar: 'مبارك التخرج' },
    arabic: 'أَلفُ مَبروكٍ التَّخَرُّج، اللَّهُمَّ وَفِّقهُ لِما تُحِبُّ وَتَرضى',
    translation:
      'Congratulations on graduating. O Allah, grant success in what You love and are pleased with.',
    theme: 'teal-lagoon',
    decoration: 'lights',
    font: 'cairo',
  },
  {
    id: 'g2-new-job',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'New job', ar: 'عمل جديد' },
    arabic: 'مُبارَكٌ العَمَلُ الجَديد، اللَّهُمَّ ارزُقهُ الإِخلاصَ وَالتَّوفيقَ وَالبَرَكَة',
    translation: 'Congratulations on the new job. O Allah, grant sincerity, success and blessing.',
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'cairo',
  },
  {
    id: 'g2-engagement',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Engagement', ar: 'مبارك الخطوبة' },
    arabic: 'مُبارَكٌ لَكُما، اللَّهُمَّ أَتمِم لَهُما عَلى خَير',
    translation: 'Congratulations to you both. O Allah, bring it to completion with goodness.',
    theme: 'rose-gold',
    decoration: 'none',
    background: 'lavender-field',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-safe-return',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Welcome home', ar: 'الحمد لله على السلامة' },
    arabic: 'الحَمدُ لِلهِ عَلى السَّلامَة، وَحَمدًا لِلهِ عَلى عَودَتِكَ بِخَير',
    translation: 'Praise be to Allah for your safety, and praise be to Allah for your safe return.',
    theme: 'olive-sage',
    decoration: 'none',
    background: 'river-valley',
    font: 'cairo',
  },
  {
    id: 'g2-recovery-2',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Get well soon', ar: 'شفاك الله' },
    arabic: 'شَفاكَ اللهُ وَعافاك، وَأَلبَسَكَ ثَوبَ الصِّحَّةِ وَالعافِيَة',
    translation: 'May Allah heal you and grant you well-being, and clothe you in health.',
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'forest-light',
    font: 'aref-ruqaa',
  },
  {
    id: 'g2-condolence-2',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Condolences', ar: 'عظم الله أجركم' },
    arabic: 'عَظَّمَ اللهُ أَجرَكُم، وَأَحسَنَ عَزاءَكُم، وَغَفَرَ لِمَيِّتِكُم',
    translation: 'May Allah magnify your reward, grant you good consolation, and forgive your deceased.',
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'naskh',
  },
];
