import type { Post } from '../../types';

/** Short, well-known authentic hadith for cards. */
export const hadithPosts2: Post[] = [
  {
    id: 'h2-dua-worship',
    category: 'dua',
    kind: 'hadith',
    arabic: 'الدُّعَاءُ هُوَ الْعِبَادَةُ',
    translation: 'Supplication is worship itself.',
    source: { en: 'At-Tirmidhi 2969, Abu Dawud 1479', ar: 'الترمذي ٢٩٦٩، أبو داود ١٤٧٩' },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-speak-good',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    translation: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    source: { en: 'Sahih al-Bukhari 6018, Sahih Muslim 47', ar: 'صحيح البخاري ٦٠١٨، صحيح مسلم ٤٧' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'naskh',
  },
  {
    id: 'h2-muslim-safe',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
    translation: 'The Muslim is the one from whose tongue and hand the Muslims are safe.',
    source: { en: 'Sahih al-Bukhari 10, Sahih Muslim 40', ar: 'صحيح البخاري ١٠، صحيح مسلم ٤٠' },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'amiri',
  },
  {
    id: 'h2-love-brother',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    translation: 'None of you truly believes until he loves for his brother what he loves for himself.',
    source: { en: 'Sahih al-Bukhari 13, Sahih Muslim 45', ar: 'صحيح البخاري ١٣، صحيح مسلم ٤٥' },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'h2-gentleness',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ',
    translation: 'Indeed Allah is gentle and loves gentleness.',
    source: { en: 'Sahih al-Bukhari 6927, Sahih Muslim 2593', ar: 'صحيح البخاري ٦٩٢٧، صحيح مسلم ٢٥٩٣' },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'wildflowers',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-charity-wealth',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ',
    translation: 'Charity does not decrease wealth.',
    source: { en: 'Sahih Muslim 2588', ar: 'صحيح مسلم ٢٥٨٨' },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'reem-kufi',
  },
  {
    id: 'h2-birr',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'الْبِرُّ حُسْنُ الْخُلُقِ',
    translation: 'Righteousness is good character.',
    source: { en: 'Sahih Muslim 2553', ar: 'صحيح مسلم ٢٥٥٣' },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-consistent-deeds',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
    translation: 'The most beloved deeds to Allah are the most consistent, even if small.',
    source: { en: 'Sahih al-Bukhari 6464, Sahih Muslim 783', ar: 'صحيح البخاري ٦٤٦٤، صحيح مسلم ٧٨٣' },
    theme: 'burgundy-gold',
    decoration: 'none',
    font: 'naskh',
  },
  {
    id: 'h2-hearts-deeds',
    category: 'hadith',
    kind: 'hadith',
    arabic:
      'إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ، وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
    translation:
      'Allah does not look at your appearance or wealth, but He looks at your hearts and your deeds.',
    source: { en: 'Sahih Muslim 2564', ar: 'صحيح مسلم ٢٥٦٤' },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'starry-night',
    font: 'amiri',
  },
  {
    id: 'h2-taqwa-wherever',
    category: 'hadith',
    kind: 'hadith',
    arabic:
      'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
    translation:
      'Fear Allah wherever you are, follow a bad deed with a good one to wipe it out, and treat people with good character.',
    source: { en: 'At-Tirmidhi 1987', ar: 'الترمذي ١٩٨٧' },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'naskh',
  },
  {
    id: 'h2-religion-ease',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'إِنَّ الدِّينَ يُسْرٌ',
    translation: 'Indeed, the religion is ease.',
    source: { en: 'Sahih al-Bukhari 39', ar: 'صحيح البخاري ٣٩' },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-salawat-ten',
    category: 'friday',
    kind: 'hadith',
    arabic: 'مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا',
    translation: 'Whoever sends one blessing upon me, Allah sends ten blessings upon him.',
    source: { en: 'Sahih Muslim 408', ar: 'صحيح مسلم ٤٠٨' },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-sunset',
    font: 'scheherazade',
  },
  {
    id: 'h2-two-words',
    category: 'hadith',
    kind: 'hadith',
    arabic:
      'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    translation:
      'Two words light on the tongue, heavy on the scale, beloved to the Most Merciful: Glory be to Allah and praise Him; glory be to Allah the Mighty.',
    source: { en: 'Sahih al-Bukhari 6406, Sahih Muslim 2694', ar: 'صحيح البخاري ٦٤٠٦، صحيح مسلم ٢٦٩٤' },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'h2-closest-sujud',
    category: 'dua',
    kind: 'hadith',
    arabic: 'أَقْرَبُ مَا يَكُونُ الْعَبْدُ مِنْ رَبِّهِ وَهُوَ سَاجِدٌ، فَأَكْثِرُوا الدُّعَاءَ',
    translation: 'The closest a servant is to his Lord is when he is prostrating, so make much supplication.',
    source: { en: 'Sahih Muslim 482', ar: 'صحيح مسلم ٤٨٢' },
    theme: 'charcoal-minimal',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'h2-friday-expiation',
    category: 'friday',
    kind: 'hadith',
    arabic:
      'الصَّلَوَاتُ الْخَمْسُ، وَالْجُمُعَةُ إِلَى الْجُمُعَةِ، وَرَمَضَانُ إِلَى رَمَضَانَ، مُكَفِّرَاتٌ مَا بَيْنَهُنَّ إِذَا اجْتَنَبَ الْكَبَائِرَ',
    translation:
      'The five prayers, Friday to Friday, and Ramadan to Ramadan expiate what is between them, as long as major sins are avoided.',
    source: { en: 'Sahih Muslim 233', ar: 'صحيح مسلم ٢٣٣' },
    theme: 'midnight-blue',
    decoration: 'mosque',
    font: 'naskh',
  },
  {
    id: 'h2-qiyam-ramadan',
    category: 'ramadan',
    kind: 'hadith',
    arabic: 'مَنْ قَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    translation:
      'Whoever stands in prayer during Ramadan out of faith and seeking reward, his previous sins will be forgiven.',
    source: { en: 'Sahih al-Bukhari 37, Sahih Muslim 759', ar: 'صحيح البخاري ٣٧، صحيح مسلم ٧٥٩' },
    theme: 'royal-purple',
    decoration: 'lanterns',
    font: 'scheherazade',
  },
  {
    id: 'h2-qiyam-qadr',
    category: 'laylat-al-qadr',
    kind: 'hadith',
    arabic: 'مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    translation:
      'Whoever stands in prayer on the Night of Decree out of faith and seeking reward, his previous sins will be forgiven.',
    source: { en: 'Sahih al-Bukhari 1901', ar: 'صحيح البخاري ١٩٠١' },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'amiri',
  },
  {
    id: 'h2-suhoor',
    category: 'ramadan',
    kind: 'hadith',
    arabic: 'تَسَحَّرُوا فَإِنَّ فِي السَّحُورِ بَرَكَةً',
    translation: 'Take the pre-dawn meal, for there is blessing in it.',
    source: { en: 'Sahih al-Bukhari 1923, Sahih Muslim 1095', ar: 'صحيح البخاري ١٩٢٣، صحيح مسلم ١٠٩٥' },
    theme: 'desert-dawn',
    decoration: 'lanterns',
    font: 'reem-kufi',
  },
  {
    id: 'h2-hasten-iftar',
    category: 'ramadan',
    kind: 'hadith',
    arabic: 'لَا يَزَالُ النَّاسُ بِخَيْرٍ مَا عَجَّلُوا الْفِطْرَ',
    translation: 'People will remain upon goodness as long as they hasten to break the fast.',
    source: { en: 'Sahih al-Bukhari 1957, Sahih Muslim 1098', ar: 'صحيح البخاري ١٩٥٧، صحيح مسلم ١٠٩٨' },
    theme: 'emerald-night',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'h2-fast-fisabilillah',
    category: 'ramadan',
    kind: 'hadith',
    arabic:
      'مَنْ صَامَ يَوْمًا فِي سَبِيلِ اللَّهِ بَاعَدَ اللَّهُ وَجْهَهُ عَنِ النَّارِ سَبْعِينَ خَرِيفًا',
    translation:
      'Whoever fasts a day for the sake of Allah, Allah distances his face from the Fire by seventy years.',
    source: { en: 'Sahih al-Bukhari 2840, Sahih Muslim 1153', ar: 'صحيح البخاري ٢٨٤٠، صحيح مسلم ١١٥٣' },
    theme: 'burgundy-gold',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'amiri',
  },
  {
    id: 'h2-hajj-mabrur',
    category: 'dhul-hijjah',
    kind: 'hadith',
    arabic: 'الْحَجُّ الْمَبْرُورُ لَيْسَ لَهُ جَزَاءٌ إِلَّا الْجَنَّةُ',
    translation: 'An accepted Hajj has no reward other than Paradise.',
    source: { en: 'Sahih al-Bukhari 1773, Sahih Muslim 1349', ar: 'صحيح البخاري ١٧٧٣، صحيح مسلم ١٣٤٩' },
    theme: 'ivory-gold',
    decoration: 'kaaba',
    font: 'amiri',
  },
  {
    id: 'h2-umrah-expiation',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'Umrah', ar: 'العمرة' },
    arabic: 'الْعُمْرَةُ إِلَى الْعُمْرَةِ كَفَّارَةٌ لِمَا بَيْنَهُمَا',
    translation: 'One Umrah to the next is an expiation for what is between them.',
    source: { en: 'Sahih al-Bukhari 1773, Sahih Muslim 1349', ar: 'صحيح البخاري ١٧٧٣، صحيح مسلم ١٣٤٩' },
    theme: 'charcoal-minimal',
    decoration: 'kaaba',
    font: 'naskh',
  },
  {
    id: 'h2-thank-people',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'مَنْ لَمْ يَشْكُرِ النَّاسَ لَمْ يَشْكُرِ اللَّهَ',
    translation: 'Whoever does not thank people has not thanked Allah.',
    source: { en: 'At-Tirmidhi 1954, Abu Dawud 4811', ar: 'الترمذي ١٩٥٤، أبو داود ٤٨١١' },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-seeking-knowledge',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    translation: 'Seeking knowledge is an obligation upon every Muslim.',
    source: { en: 'Ibn Majah 224 (authenticated by Al-Albani)', ar: 'ابن ماجه ٢٢٤، صححه الألباني' },
    theme: 'teal-lagoon',
    decoration: 'arch',
    font: 'reem-kufi',
  },
  {
    id: 'h2-building',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا',
    translation: 'The believer to the believer is like a building, each part strengthening the other.',
    source: { en: 'Sahih al-Bukhari 481, Sahih Muslim 2585', ar: 'صحيح البخاري ٤٨١، صحيح مسلم ٢٥٨٥' },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'naskh',
  },
  {
    id: 'h2-best-to-family',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'For the family', ar: 'للأسرة' },
    arabic: 'خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ',
    translation: 'The best of you are those who are best to their families.',
    source: { en: 'At-Tirmidhi 3895', ar: 'الترمذي ٣٨٩٥' },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-understanding-deen',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ',
    translation: 'When Allah wishes good for someone, He gives him understanding of the religion.',
    source: { en: 'Sahih al-Bukhari 71, Sahih Muslim 1037', ar: 'صحيح البخاري ٧١، صحيح مسلم ١٠٣٧' },
    theme: 'midnight-blue',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'h2-parents-pleasure',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'Parents', ar: 'الوالدان' },
    arabic: 'رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ، وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ',
    translation:
      "The Lord's pleasure is in the parent's pleasure, and the Lord's displeasure is in the parent's displeasure.",
    source: { en: 'At-Tirmidhi 1899', ar: 'الترمذي ١٨٩٩' },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'h2-allah-beautiful',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
    translation: 'Indeed Allah is beautiful and loves beauty.',
    source: { en: 'Sahih Muslim 91', ar: 'صحيح مسلم ٩١' },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'lavender-field',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-modesty',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'الْحَيَاءُ لَا يَأْتِي إِلَّا بِخَيْرٍ',
    translation: 'Modesty brings nothing but good.',
    source: { en: 'Sahih al-Bukhari 6117, Sahih Muslim 37', ar: 'صحيح البخاري ٦١١٧، صحيح مسلم ٣٧' },
    theme: 'ivory-gold',
    decoration: 'none',
    font: 'reem-kufi',
  },
  {
    id: 'h2-sick-tahur',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'For the sick', ar: 'للمريض' },
    arabic: 'لَا بَأْسَ، طَهُورٌ إِنْ شَاءَ اللَّهُ',
    translation: 'No harm; it is a purification, if Allah wills.',
    source: { en: 'Sahih al-Bukhari 3616', ar: 'صحيح البخاري ٣٦١٦' },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'forest-light',
    font: 'naskh',
  },
  {
    id: 'h2-rain-dua',
    category: 'dua',
    kind: 'hadith',
    headline: { en: 'When it rains', ar: 'عند نزول المطر' },
    arabic: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
    translation: 'O Allah, make it a beneficial rain.',
    source: { en: 'Sahih al-Bukhari 1032', ar: 'صحيح البخاري ١٠٣٢' },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'river-valley',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-distress-dua',
    category: 'dua',
    kind: 'hadith',
    headline: { en: 'In distress', ar: 'دعاء الكرب' },
    arabic:
      'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
    translation:
      'There is no god but Allah, the Mighty, the Forbearing. There is no god but Allah, Lord of the Mighty Throne. There is no god but Allah, Lord of the heavens, Lord of the earth and Lord of the Noble Throne.',
    source: { en: 'Sahih al-Bukhari 6346', ar: 'صحيح البخاري ٦٣٤٦' },
    theme: 'charcoal-minimal',
    decoration: 'stars',
    font: 'amiri',
  },
  {
    id: 'h2-guidance-dua',
    category: 'dua',
    kind: 'hadith',
    arabic: 'اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي',
    translation: 'O Allah, guide me and keep me on the right path.',
    source: { en: 'Sahih Muslim 2725', ar: 'صحيح مسلم ٢٧٢٥' },
    theme: 'emerald-night',
    decoration: 'crescent',
    font: 'aref-ruqaa',
  },
  {
    id: 'h2-jazakallah',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'Thank you', ar: 'شكرًا' },
    arabic: 'جَزَاكَ اللَّهُ خَيْرًا',
    translation:
      'May Allah reward you with good. The Prophet ﷺ said whoever says this has done his utmost in thanks.',
    source: { en: 'At-Tirmidhi 2035', ar: 'الترمذي ٢٠٣٥' },
    theme: 'ivory-gold',
    decoration: 'none',
    font: 'cairo',
  },
  {
    id: 'h2-travel-farewell',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'Farewell to a traveller', ar: 'توديع المسافر' },
    arabic: 'أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ',
    translation: 'I entrust to Allah your religion, your trust, and the conclusion of your deeds.',
    source: { en: 'At-Tirmidhi 3443, Abu Dawud 2600', ar: 'الترمذي ٣٤٤٣، أبو داود ٢٦٠٠' },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'naskh',
  },
  {
    id: 'h2-leaving-home',
    category: 'morning',
    kind: 'hadith',
    headline: { en: 'Leaving the house', ar: 'دعاء الخروج من المنزل' },
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    translation:
      'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    source: { en: 'Abu Dawud 5095, At-Tirmidhi 3426', ar: 'أبو داود ٥٠٩٥، الترمذي ٣٤٢٦' },
    theme: 'olive-sage',
    decoration: 'sunrise',
    font: 'reem-kufi',
  },
  {
    id: 'h2-after-food',
    category: 'dua',
    kind: 'hadith',
    headline: { en: 'After eating', ar: 'بعد الطعام' },
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    translation: 'Praise be to Allah who fed us, gave us drink, and made us Muslims.',
    source: { en: 'Abu Dawud 3850, At-Tirmidhi 3457', ar: 'أبو داود ٣٨٥٠، الترمذي ٣٤٥٧' },
    theme: 'burgundy-gold',
    decoration: 'none',
    font: 'naskh',
  },
  {
    id: 'h2-janazah-dua',
    category: 'occasions',
    kind: 'hadith',
    headline: { en: 'For the deceased', ar: 'دعاء للميت' },
    arabic:
      'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ، وَعَافِهِ وَاعْفُ عَنْهُ، وَأَكْرِمْ نُزُلَهُ، وَوَسِّعْ مُدْخَلَهُ',
    translation:
      'O Allah, forgive him and have mercy on him, grant him well-being and pardon him, honour his reception and widen his entrance.',
    source: { en: 'Sahih Muslim 963', ar: 'صحيح مسلم ٩٦٣' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'amiri',
  },
];
