import type { Post } from '../../types';

/** Additional posts across categories to widen the gallery. */
export const morePosts: Post[] = [
  // ---- Friday ----
  {
    id: 'friday-salawat-hadith',
    category: 'friday',
    kind: 'hadith',
    headline: { en: 'Send blessings on Friday', ar: 'أكثروا من الصلاة عليه' },
    arabic: 'إِنَّ مِنْ أَفْضَلِ أَيَّامِكُمْ يَوْمَ الْجُمُعَةِ، فَأَكْثِرُوا عَلَيَّ مِنَ الصَّلَاةِ فِيهِ',
    translation: 'Among the best of your days is Friday, so send many blessings upon me on that day.',
    source: { en: 'Abu Dawud 1047', ar: 'أبو داود ١٠٤٧' },
    theme: 'emerald-night',
    decoration: 'lights',
    font: 'naskh',
  },
  {
    id: 'friday-greeting-2',
    category: 'friday',
    kind: 'greeting',
    headline: { en: 'Blessed Friday', ar: 'جمعة مباركة' },
    arabic: 'اللَّهُمَّ اجعَلها جُمعَةَ خَيرٍ وَبَرَكَةٍ وَرِضا، وَاغفِر لَنا وَلِوالِدينا',
    translation:
      'O Allah, make it a Friday of goodness, blessing and contentment, and forgive us and our parents.',
    translations: {
      fr: "Ô Allah, fais-en un vendredi de bien, de bénédiction et de contentement, et pardonne-nous ainsi qu'à nos parents.",
      id: 'Ya Allah, jadikanlah Jumat yang penuh kebaikan, keberkahan, dan keridaan, dan ampunilah kami serta kedua orang tua kami.',
      ms: 'Ya Allah, jadikanlah Jumaat yang penuh kebaikan, keberkatan dan keredaan, dan ampunilah kami serta kedua ibu bapa kami.',
      th: 'โอ้อัลลอฮฺ ขอทรงให้เป็นวันศุกร์แห่งความดี ความจำเริญ และความพอใจ และทรงอภัยแก่เราและบิดามารดาของเรา',
      ur: 'اے اللہ، اسے خیر، برکت اور رضا کا جمعہ بنا، اور ہمیں اور ہمارے والدین کو بخش دے۔',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'aref-ruqaa',
  },
  // ---- Morning ----
  {
    id: 'morning-radeetu',
    category: 'morning',
    kind: 'dhikr',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا',
    translation:
      'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
    source: { en: 'Abu Dawud 5072, At-Tirmidhi 3389', ar: 'أبو داود ٥٠٧٢، الترمذي ٣٣٨٩' },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'forest-light',
    font: 'scheherazade',
  },
  {
    id: 'morning-nimah',
    category: 'morning',
    kind: 'dua',
    arabic:
      'اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ',
    translation:
      'O Allah, whatever blessing I or any of Your creation have this morning is from You alone, without partner. So to You belongs all praise and thanks.',
    source: { en: 'Abu Dawud 5073', ar: 'أبو داود ٥٠٧٣' },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'morning-sidq',
    category: 'morning',
    kind: 'quran',
    arabic:
      'وَقُل رَّبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا',
    translation:
      'And say: My Lord, let me enter with truth and let me leave with truth, and grant me from Yourself a supporting authority.',
    source: { en: 'Surah Al-Isra 17:80', ar: 'سورة الإسراء ١٧:٨٠' },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  // ---- Evening ----
  {
    id: 'evening-afini',
    category: 'evening',
    kind: 'dua',
    arabic:
      'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَهَ إِلَّا أَنْتَ',
    translation:
      'O Allah, grant my body health. O Allah, grant my hearing health. O Allah, grant my sight health. There is no god but You.',
    source: { en: 'Abu Dawud 5090', ar: 'أبو داود ٥٠٩٠' },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'amiri',
  },
  {
    id: 'evening-night-verse',
    category: 'evening',
    kind: 'quran',
    arabic:
      'وَهُوَ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِبَاسًا وَالنَّوْمَ سُبَاتًا وَجَعَلَ النَّهَارَ نُشُورًا',
    translation:
      'And it is He who has made the night a covering for you and sleep a rest, and has made the day a resurrection.',
    source: { en: 'Surah Al-Furqan 25:47', ar: 'سورة الفرقان ٢٥:٤٧' },
    theme: 'charcoal-minimal',
    decoration: 'crescent',
    font: 'scheherazade',
  },
  // ---- Ramadan ----
  {
    id: 'ramadan-two-joys',
    category: 'ramadan',
    kind: 'hadith',
    arabic:
      'لِلصَّائِمِ فَرْحَتَانِ يَفْرَحُهُمَا: إِذَا أَفْطَرَ فَرِحَ، وَإِذَا لَقِيَ رَبَّهُ فَرِحَ بِصَوْمِهِ',
    translation:
      'The fasting person has two joys: when he breaks his fast he rejoices, and when he meets his Lord he rejoices in his fasting.',
    source: { en: 'Sahih al-Bukhari 1904, Sahih Muslim 1151', ar: 'صحيح البخاري ١٩٠٤، صحيح مسلم ١١٥١' },
    theme: 'royal-purple',
    decoration: 'lanterns',
    font: 'naskh',
  },
  {
    id: 'ramadan-feed-fasting',
    category: 'ramadan',
    kind: 'hadith',
    arabic: 'مَنْ فَطَّرَ صَائِمًا كَانَ لَهُ مِثْلُ أَجْرِهِ',
    translation: 'Whoever provides food for a fasting person to break his fast will have a reward like his.',
    source: { en: 'At-Tirmidhi 807', ar: 'الترمذي ٨٠٧' },
    theme: 'burgundy-gold',
    decoration: 'lights',
    font: 'reem-kufi',
  },
  // ---- Laylat al-Qadr ----
  {
    id: 'qadr-peace',
    category: 'laylat-al-qadr',
    kind: 'quran',
    arabic:
      'تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ ۝ سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ',
    translation:
      'The angels and the Spirit descend therein by permission of their Lord for every matter. Peace it is until the emergence of dawn.',
    source: { en: 'Surah Al-Qadr 97:4-5', ar: 'سورة القدر ٩٧:٤-٥' },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'starry-night',
    font: 'amiri',
  },
  // ---- Eid al-Fitr ----
  {
    id: 'fitr-awwada',
    category: 'eid-al-fitr',
    kind: 'greeting',
    headline: { en: 'Eid Mubarak', ar: 'عيدكم مبارك' },
    arabic: 'عيدُكُم مُبارَك وَعَساكُم مِن عُوّادِه',
    translation: 'Eid Mubarak, and may you live to see many more.',
    translations: {
      fr: "Aïd Moubarak, et puissiez-vous en connaître beaucoup d'autres.",
      id: 'Selamat Idulfitri, semoga Anda menjumpainya berkali-kali lagi.',
      ms: 'Selamat Aidilfitri, semoga anda menemuinya berkali-kali lagi.',
      th: 'อีดมุบาร็อก ขอให้ท่านได้พบอีกหลายครั้ง',
      ur: 'عید مبارک، اور آپ اسے بار بار پائیں۔',
    },
    theme: 'desert-dawn',
    decoration: 'lights',
    font: 'cairo',
  },
  // ---- Dhul Hijjah ----
  {
    id: 'hijjah-provision',
    category: 'dhul-hijjah',
    kind: 'quran',
    arabic: 'وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ',
    translation: 'And take provisions, but indeed the best provision is piety.',
    source: { en: 'Surah Al-Baqarah 2:197', ar: 'سورة البقرة ٢:١٩٧' },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'aref-ruqaa',
  },
  // ---- Eid al-Adha ----
  {
    id: 'adha-greeting-2',
    category: 'eid-al-adha',
    kind: 'greeting',
    headline: { en: 'Adha Mubarak', ar: 'أضحى مبارك' },
    arabic: 'تَقَبَّلَ اللهُ مِنّا وَمِنكُم صالِحَ الأَعمال، وَكُلُّ عامٍ وَأَنتُم بِخَير',
    translation: 'May Allah accept our good deeds and yours, and may you be well every year.',
    translations: {
      fr: "Qu'Allah accepte nos bonnes œuvres et les vôtres, et que chaque année vous trouve en bonne santé.",
      id: 'Semoga Allah menerima amal saleh kami dan Anda, dan semoga Anda selalu dalam kebaikan setiap tahun.',
      ms: 'Semoga Allah menerima amal soleh kami dan anda, dan semoga anda sentiasa dalam kebaikan setiap tahun.',
      th: 'ขออัลลอฮฺทรงตอบรับความดีของเราและของท่าน และขอให้ท่านมีสุขทุกปี',
      ur: 'اللہ ہماری اور آپ کی نیکیاں قبول فرمائے، اور ہر سال آپ خیریت سے رہیں۔',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'aref-ruqaa',
  },
  // ---- Muharram ----
  {
    id: 'ashura-musa',
    category: 'muharram',
    kind: 'hadith',
    headline: { en: 'Why Ashura is fasted', ar: 'صيام عاشوراء' },
    arabic:
      'هَذَا يَوْمٌ صَالِحٌ، هَذَا يَوْمٌ نَجَّى اللَّهُ بَنِي إِسْرَائِيلَ مِنْ عَدُوِّهِمْ فَصَامَهُ مُوسَى',
    translation:
      'This is a righteous day. This is the day on which Allah saved the Children of Israel from their enemy, so Musa fasted it.',
    source: { en: 'Sahih al-Bukhari 2004', ar: 'صحيح البخاري ٢٠٠٤' },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  // ---- Quran ----
  {
    id: 'quran-near',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ',
    translation:
      'And when My servants ask you concerning Me, indeed I am near. I respond to the call of the caller when he calls upon Me.',
    source: { en: 'Surah Al-Baqarah 2:186', ar: 'سورة البقرة ٢:١٨٦' },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'river-valley',
    font: 'amiri',
  },
  {
    id: 'quran-strive',
    category: 'quran',
    kind: 'quran',
    arabic: 'فَإِذَا فَرَغْتَ فَانصَبْ ۝ وَإِلَىٰ رَبِّكَ فَارْغَب',
    translation:
      'So when you have finished, then stand up for worship. And to your Lord direct your longing.',
    source: { en: 'Surah Ash-Sharh 94:7-8', ar: 'سورة الشرح ٩٤:٧-٨' },
    theme: 'ivory-gold',
    decoration: 'none',
    font: 'aref-ruqaa',
  },
  {
    id: 'quran-no-despair',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ',
    translation: 'And do not despair of relief from Allah.',
    source: { en: 'Surah Yusuf 12:87', ar: 'سورة يوسف ١٢:٨٧' },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'aref-ruqaa',
  },
  {
    id: 'quran-gratitude',
    category: 'quran',
    kind: 'quran',
    arabic: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
    translation: 'If you are grateful, I will surely increase you.',
    source: { en: 'Surah Ibrahim 14:7', ar: 'سورة إبراهيم ١٤:٧' },
    theme: 'olive-sage',
    decoration: 'sunrise',
    font: 'reem-kufi',
  },
  {
    id: 'quran-decree',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا هُوَ مَوْلَانَا ۚ وَعَلَى اللَّهِ فَلْيَتَوَكَّلِ الْمُؤْمِنُونَ',
    translation:
      'Say: Nothing will befall us except what Allah has decreed for us; He is our protector. And upon Allah let the believers rely.',
    source: { en: 'Surah At-Tawbah 9:51', ar: 'سورة التوبة ٩:٥١' },
    theme: 'charcoal-minimal',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'quran-pleased',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ',
    translation: 'And your Lord is going to give you, and you will be satisfied.',
    source: { en: 'Surah Ad-Duha 93:5', ar: 'سورة الضحى ٩٣:٥' },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'aref-ruqaa',
  },
  // ---- Hadith ----
  {
    id: 'hadith-no-mercy',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'مَنْ لَا يَرْحَمُ لَا يُرْحَمُ',
    translation: 'Whoever does not show mercy will not be shown mercy.',
    source: { en: 'Sahih al-Bukhari 5997, Sahih Muslim 2318', ar: 'صحيح البخاري ٥٩٩٧، صحيح مسلم ٢٣١٨' },
    theme: 'teal-lagoon',
    decoration: 'arch',
    font: 'aref-ruqaa',
  },
  {
    id: 'hadith-anger',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',
    translation:
      'The strong one is not the one who overcomes others; the strong one is the one who controls himself when angry.',
    source: { en: 'Sahih al-Bukhari 6114, Sahih Muslim 2609', ar: 'صحيح البخاري ٦١١٤، صحيح مسلم ٢٦٠٩' },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'naskh',
  },
  {
    id: 'hadith-best-people',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ',
    translation: 'The best of people are those who are most beneficial to people.',
    source: {
      en: "Al-Mu'jam al-Awsat 5787 (graded hasan by Al-Albani)",
      ar: 'المعجم الأوسط ٥٧٨٧، حسنه الألباني',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'wildflowers',
    font: 'reem-kufi',
  },
  {
    id: 'hadith-purity',
    category: 'hadith',
    kind: 'hadith',
    arabic: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
    translation: 'Purity is half of faith.',
    source: { en: 'Sahih Muslim 223', ar: 'صحيح مسلم ٢٢٣' },
    theme: 'ivory-gold',
    decoration: 'none',
    font: 'aref-ruqaa',
  },
  {
    id: 'hadith-seek-knowledge',
    category: 'hadith',
    kind: 'hadith',
    arabic:
      'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
    translation:
      'Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise.',
    source: { en: 'Sahih Muslim 2699', ar: 'صحيح مسلم ٢٦٩٩' },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  // ---- Duaa ----
  {
    id: 'dua-hearts-steadfast',
    category: 'dua',
    kind: 'dua',
    arabic:
      'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ',
    translation:
      'Our Lord, let not our hearts deviate after You have guided us, and grant us from Yourself mercy. Indeed, You are the Bestower.',
    source: { en: 'Surah Al Imran 3:8', ar: 'سورة آل عمران ٣:٨' },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'lavender-field',
    font: 'amiri',
  },
  {
    id: 'dua-establish-prayer',
    category: 'dua',
    kind: 'dua',
    arabic: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
    translation:
      'My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication.',
    source: { en: 'Surah Ibrahim 14:40', ar: 'سورة إبراهيم ١٤:٤٠' },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-sea',
    font: 'scheherazade',
  },
  {
    id: 'dua-anxiety',
    category: 'dua',
    kind: 'dua',
    arabic:
      'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    translation:
      'O Allah, I seek refuge in You from anxiety and sorrow, weakness and laziness, miserliness and cowardice, the burden of debt and being overpowered by men.',
    source: { en: 'Sahih al-Bukhari 6369', ar: 'صحيح البخاري ٦٣٦٩' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'naskh',
  },
  {
    id: 'dua-help-remember',
    category: 'dua',
    kind: 'dua',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    translation: 'O Allah, help me to remember You, to thank You, and to worship You well.',
    source: { en: "Abu Dawud 1522, An-Nasa'i 1303", ar: 'أبو داود ١٥٢٢، النسائي ١٣٠٣' },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'aref-ruqaa',
  },
  // ---- Occasions ----
  {
    id: 'occasion-exam',
    category: 'occasions',
    kind: 'dua',
    headline: { en: 'Before an exam', ar: 'دعاء قبل الامتحان' },
    arabic: 'رَبِّ يَسِّر وَلا تُعَسِّر، وَتَمِّم بِالخَير',
    translation: 'My Lord, make it easy and not difficult, and bring it to a good end.',
    source: { en: 'Popular supplication', ar: 'دعاء شائع' },
    theme: 'olive-sage',
    decoration: 'sunrise',
    font: 'cairo',
  },
  {
    id: 'occasion-umrah',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Umrah accepted', ar: 'عمرة مقبولة' },
    arabic: 'عُمرَةٌ مَقبولَة، وَسَعيٌ مَشكور، وَذَنبٌ مَغفور',
    translation: 'An accepted Umrah, a rewarded effort, and forgiven sins.',
    translations: {
      fr: 'Une Omra agréée, un effort récompensé et des péchés pardonnés.',
      id: 'Umrah yang diterima, usaha yang berpahala, dan dosa yang diampuni.',
      ms: 'Umrah yang diterima, usaha yang berpahala, dan dosa yang diampuni.',
      th: 'อุมเราะฮฺที่ถูกตอบรับ ความเพียรที่ได้รับผลบุญ และบาปที่ถูกอภัย',
      ur: 'عمرہ مقبول، سعی مشکور اور گناہ معاف۔',
    },
    theme: 'ivory-gold',
    decoration: 'kaaba',
    font: 'aref-ruqaa',
  },
  {
    id: 'occasion-success',
    category: 'occasions',
    kind: 'greeting',
    headline: { en: 'Congratulations', ar: 'مبارك النجاح' },
    arabic: 'بارَكَ اللهُ لَكَ وَوَفَّقَكَ، وَجَعَلَ ما هُوَ آتٍ خَيرًا مِمّا مَضى',
    translation:
      'May Allah bless you and grant you success, and make what is coming better than what has passed.',
    translations: {
      fr: "Qu'Allah vous bénisse et vous accorde la réussite, et que ce qui vient soit meilleur que ce qui est passé.",
      id: 'Semoga Allah memberkahi dan memberi Anda keberhasilan, dan menjadikan yang akan datang lebih baik dari yang telah lalu.',
      ms: 'Semoga Allah memberkati dan memberi anda kejayaan, dan menjadikan yang akan datang lebih baik daripada yang telah lalu.',
      th: 'ขออัลลอฮฺทรงประทานความจำเริญและความสำเร็จแก่ท่าน และให้สิ่งที่จะมาถึงดีกว่าสิ่งที่ผ่านไป',
      ur: 'اللہ آپ کو برکت اور کامیابی دے، اور آنے والا وقت گزرے ہوئے سے بہتر بنائے۔',
    },
    theme: 'rose-gold',
    decoration: 'lights',
    font: 'cairo',
  },
];
