// GENERATED by scripts/gen-quran-posts.mjs from packages/assets/quran. Do not edit by hand.
import type { Post } from '../../types';

export const quranVersePosts: Post[] = [
  {
    id: 'qv-2-45',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَٱسۡتَعِينُواْ بِٱلصَّبۡرِ وَٱلصَّلَوٰةِۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى ٱلۡخَٰشِعِينَ',
    translation:
      'And seek help through patience and prayer, and indeed, it is difficult except for the humbly submissive [to Allah]',
    source: {
      en: 'Surah Al-Baqarah 2:45',
      ar: 'سورة البقرة ٢:٤٥',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'wildflowers',
    font: 'amiri',
  },
  {
    id: 'qv-2-153',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱسۡتَعِينُواْ بِٱلصَّبۡرِ وَٱلصَّلَوٰةِۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ',
    translation:
      'O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient',
    source: {
      en: 'Surah Al-Baqarah 2:153',
      ar: 'سورة البقرة ٢:١٥٣',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-2-216',
    category: 'quran',
    kind: 'quran',
    arabic:
      'كُتِبَ عَلَيۡكُمُ ٱلۡقِتَالُ وَهُوَ كُرۡهٞ لَّكُمۡۖ وَعَسَىٰٓ أَن تَكۡرَهُواْ شَيۡـٔٗا وَهُوَ خَيۡرٞ لَّكُمۡۖ وَعَسَىٰٓ أَن تُحِبُّواْ شَيۡـٔٗا وَهُوَ شَرّٞ لَّكُمۡۚ وَٱللَّهُ يَعۡلَمُ وَأَنتُمۡ لَا تَعۡلَمُونَ',
    translation:
      'Fighting has been enjoined upon you while it is hateful to you. But perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allah Knows, while you know not',
    source: {
      en: 'Surah Al-Baqarah 2:216',
      ar: 'سورة البقرة ٢:٢١٦',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-2-257',
    category: 'quran',
    kind: 'quran',
    arabic:
      'ٱللَّهُ وَلِيُّ ٱلَّذِينَ ءَامَنُواْ يُخۡرِجُهُم مِّنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِۖ وَٱلَّذِينَ كَفَرُوٓاْ أَوۡلِيَآؤُهُمُ ٱلطَّـٰغُوتُ يُخۡرِجُونَهُم مِّنَ ٱلنُّورِ إِلَى ٱلظُّلُمَٰتِۗ أُوْلَـٰٓئِكَ أَصۡحَٰبُ ٱلنَّارِۖ هُمۡ فِيهَا خَٰلِدُونَ',
    translation:
      'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve - their allies are Taghut. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein',
    source: {
      en: 'Surah Al-Baqarah 2:257',
      ar: 'سورة البقرة ٢:٢٥٧',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'river-valley',
    font: 'naskh',
  },
  {
    id: 'qv-3-26',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلِ ٱللَّهُمَّ مَٰلِكَ ٱلۡمُلۡكِ تُؤۡتِي ٱلۡمُلۡكَ مَن تَشَآءُ وَتَنزِعُ ٱلۡمُلۡكَ مِمَّن تَشَآءُ وَتُعِزُّ مَن تَشَآءُ وَتُذِلُّ مَن تَشَآءُۖ بِيَدِكَ ٱلۡخَيۡرُۖ إِنَّكَ عَلَىٰ كُلِّ شَيۡءٖ قَدِيرٞ',
    translation:
      'Say, "O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honor whom You will and You humble whom You will. In Your hand is [all] good. Indeed, You are over all things competent',
    source: {
      en: "Surah Ali 'Imran 3:26",
      ar: 'سورة آل عمران ٣:٢٦',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-3-31',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلۡ إِن كُنتُمۡ تُحِبُّونَ ٱللَّهَ فَٱتَّبِعُونِي يُحۡبِبۡكُمُ ٱللَّهُ وَيَغۡفِرۡ لَكُمۡ ذُنُوبَكُمۡۚ وَٱللَّهُ غَفُورٞ رَّحِيمٞ',
    translation:
      'Say, [O Muhammad], "If you should love Allah, then follow me, [so] Allah will love you and forgive you your sins. And Allah is Forgiving and Merciful',
    source: {
      en: "Surah Ali 'Imran 3:31",
      ar: 'سورة آل عمران ٣:٣١',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-3-159',
    category: 'quran',
    kind: 'quran',
    arabic:
      'فَبِمَا رَحۡمَةٖ مِّنَ ٱللَّهِ لِنتَ لَهُمۡۖ وَلَوۡ كُنتَ فَظًّا غَلِيظَ ٱلۡقَلۡبِ لَٱنفَضُّواْ مِنۡ حَوۡلِكَۖ فَٱعۡفُ عَنۡهُمۡ وَٱسۡتَغۡفِرۡ لَهُمۡ وَشَاوِرۡهُمۡ فِي ٱلۡأَمۡرِۖ فَإِذَا عَزَمۡتَ فَتَوَكَّلۡ عَلَى ٱللَّهِۚ إِنَّ ٱللَّهَ يُحِبُّ ٱلۡمُتَوَكِّلِينَ',
    translation:
      'So by mercy from Allah, [O Muhammad], you were lenient with them. And if you had been rude [in speech] and harsh in heart, they would have disbanded from about you. So pardon them and ask forgiveness for them and consult them in the matter. And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely [upon Him]',
    source: {
      en: "Surah Ali 'Imran 3:159",
      ar: 'سورة آل عمران ٣:١٥٩',
    },
    theme: 'burgundy-gold',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'naskh',
  },
  {
    id: 'qv-3-185',
    category: 'quran',
    kind: 'quran',
    arabic:
      'كُلُّ نَفۡسٖ ذَآئِقَةُ ٱلۡمَوۡتِۗ وَإِنَّمَا تُوَفَّوۡنَ أُجُورَكُمۡ يَوۡمَ ٱلۡقِيَٰمَةِۖ فَمَن زُحۡزِحَ عَنِ ٱلنَّارِ وَأُدۡخِلَ ٱلۡجَنَّةَ فَقَدۡ فَازَۗ وَمَا ٱلۡحَيَوٰةُ ٱلدُّنۡيَآ إِلَّا مَتَٰعُ ٱلۡغُرُورِ',
    translation:
      'Every soul will taste death, and you will only be given your [full] compensation on the Day of Resurrection. So he who is drawn away from the Fire and admitted to Paradise has attained [his desire]. And what is the life of this world except the enjoyment of delusion',
    source: {
      en: "Surah Ali 'Imran 3:185",
      ar: 'سورة آل عمران ٣:١٨٥',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-3-200',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱصۡبِرُواْ وَصَابِرُواْ وَرَابِطُواْ وَٱتَّقُواْ ٱللَّهَ لَعَلَّكُمۡ تُفۡلِحُونَ',
    translation:
      'O you who have believed, persevere and endure and remain stationed and fear Allah that you may be successful',
    source: {
      en: "Surah Ali 'Imran 3:200",
      ar: 'سورة آل عمران ٣:٢٠٠',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-6-17',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَإِن يَمۡسَسۡكَ ٱللَّهُ بِضُرّٖ فَلَا كَاشِفَ لَهُۥٓ إِلَّا هُوَۖ وَإِن يَمۡسَسۡكَ بِخَيۡرٖ فَهُوَ عَلَىٰ كُلِّ شَيۡءٖ قَدِيرٞ',
    translation:
      'And if Allah should touch you with adversity, there is no remover of it except Him. And if He touches you with good - then He is over all things competent',
    source: {
      en: "Surah Al-An'am 6:17",
      ar: 'سورة الأنعام ٦:١٧',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-6-162',
    category: 'quran',
    kind: 'quran',
    arabic: 'قُلۡ إِنَّ صَلَاتِي وَنُسُكِي وَمَحۡيَايَ وَمَمَاتِي لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ',
    translation:
      'Say, "Indeed, my prayer, my rites of sacrifice, my living and my dying are for Allah, Lord of the worlds',
    source: {
      en: "Surah Al-An'am 6:162",
      ar: 'سورة الأنعام ٦:١٦٢',
    },
    theme: 'ivory-gold',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'amiri',
  },
  {
    id: 'qv-7-55',
    category: 'quran',
    kind: 'quran',
    arabic: 'ٱدۡعُواْ رَبَّكُمۡ تَضَرُّعٗا وَخُفۡيَةًۚ إِنَّهُۥ لَا يُحِبُّ ٱلۡمُعۡتَدِينَ',
    translation: 'Call upon your Lord in humility and privately; indeed, He does not like transgressors',
    source: {
      en: "Surah Al-A'raf 7:55",
      ar: 'سورة الأعراف ٧:٥٥',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-7-199',
    category: 'quran',
    kind: 'quran',
    arabic: 'خُذِ ٱلۡعَفۡوَ وَأۡمُرۡ بِٱلۡعُرۡفِ وَأَعۡرِضۡ عَنِ ٱلۡجَٰهِلِينَ',
    translation: 'Take what is given freely, enjoin what is good, and turn away from the ignorant',
    source: {
      en: "Surah Al-A'raf 7:199",
      ar: 'سورة الأعراف ٧:١٩٩',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-8-2',
    category: 'quran',
    kind: 'quran',
    arabic:
      'إِنَّمَا ٱلۡمُؤۡمِنُونَ ٱلَّذِينَ إِذَا ذُكِرَ ٱللَّهُ وَجِلَتۡ قُلُوبُهُمۡ وَإِذَا تُلِيَتۡ عَلَيۡهِمۡ ءَايَٰتُهُۥ زَادَتۡهُمۡ إِيمَٰنٗا وَعَلَىٰ رَبِّهِمۡ يَتَوَكَّلُونَ',
    translation:
      'The believers are only those who, when Allah is mentioned, their hearts become fearful, and when His verses are recited to them, it increases them in faith; and upon their Lord they rely',
    source: {
      en: 'Surah Al-Anfal 8:2',
      ar: 'سورة الأنفال ٨:٢',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'scheherazade',
  },
  {
    id: 'qv-9-129',
    category: 'quran',
    kind: 'quran',
    arabic:
      'فَإِن تَوَلَّوۡاْ فَقُلۡ حَسۡبِيَ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَۖ عَلَيۡهِ تَوَكَّلۡتُۖ وَهُوَ رَبُّ ٱلۡعَرۡشِ ٱلۡعَظِيمِ',
    translation:
      'But if they turn away, [O Muhammad], say, "Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne',
    source: {
      en: 'Surah At-Tawbah 9:129',
      ar: 'سورة التوبة ٩:١٢٩',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-10-57',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلنَّاسُ قَدۡ جَآءَتۡكُم مَّوۡعِظَةٞ مِّن رَّبِّكُمۡ وَشِفَآءٞ لِّمَا فِي ٱلصُّدُورِ وَهُدٗى وَرَحۡمَةٞ لِّلۡمُؤۡمِنِينَ',
    translation:
      'O mankind, there has to come to you instruction from your Lord and healing for what is in the breasts and guidance and mercy for the believers',
    source: {
      en: 'Surah Yunus 10:57',
      ar: 'سورة يونس ١٠:٥٧',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-10-58',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلۡ بِفَضۡلِ ٱللَّهِ وَبِرَحۡمَتِهِۦ فَبِذَٰلِكَ فَلۡيَفۡرَحُواْ هُوَ خَيۡرٞ مِّمَّا يَجۡمَعُونَ',
    translation:
      'Say, "In the bounty of Allah and in His mercy - in that let them rejoice; it is better than what they accumulate',
    source: {
      en: 'Surah Yunus 10:58',
      ar: 'سورة يونس ١٠:٥٨',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'starry-night',
    font: 'naskh',
  },
  {
    id: 'qv-11-88',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قَالَ يَٰقَوۡمِ أَرَءَيۡتُمۡ إِن كُنتُ عَلَىٰ بَيِّنَةٖ مِّن رَّبِّي وَرَزَقَنِي مِنۡهُ رِزۡقًا حَسَنٗاۚ وَمَآ أُرِيدُ أَنۡ أُخَالِفَكُمۡ إِلَىٰ مَآ أَنۡهَىٰكُمۡ عَنۡهُۚ إِنۡ أُرِيدُ إِلَّا ٱلۡإِصۡلَٰحَ مَا ٱسۡتَطَعۡتُۚ وَمَا تَوۡفِيقِيٓ إِلَّا بِٱللَّهِۚ عَلَيۡهِ تَوَكَّلۡتُ وَإِلَيۡهِ أُنِيبُ',
    translation:
      'He said, "O my people, have you considered: if I am upon clear evidence from my Lord and He has provided me with a good provision from Him...? And I do not intend to differ from you in that which I have forbidden you; I only intend reform as much as I am able. And my success is not but through Allah. Upon him I have relied, and to Him I return',
    source: {
      en: 'Surah Hud 11:88',
      ar: 'سورة هود ١١:٨٨',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-11-114',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَأَقِمِ ٱلصَّلَوٰةَ طَرَفَيِ ٱلنَّهَارِ وَزُلَفٗا مِّنَ ٱلَّيۡلِۚ إِنَّ ٱلۡحَسَنَٰتِ يُذۡهِبۡنَ ٱلسَّيِّـَٔاتِۚ ذَٰلِكَ ذِكۡرَىٰ لِلذَّـٰكِرِينَ',
    translation:
      'And establish prayer at the two ends of the day and at the approach of the night. Indeed, good deeds do away with misdeeds. That is a reminder for those who remember',
    source: {
      en: 'Surah Hud 11:114',
      ar: 'سورة هود ١١:١١٤',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-11-115',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَٱصۡبِرۡ فَإِنَّ ٱللَّهَ لَا يُضِيعُ أَجۡرَ ٱلۡمُحۡسِنِينَ',
    translation:
      'And be patient, for indeed, Allah does not allow to be lost the reward of those who do good',
    source: {
      en: 'Surah Hud 11:115',
      ar: 'سورة هود ١١:١١٥',
    },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'mosque-sunset',
    font: 'scheherazade',
  },
  {
    id: 'qv-13-11',
    category: 'quran',
    kind: 'quran',
    arabic:
      'لَهُۥ مُعَقِّبَٰتٞ مِّنۢ بَيۡنِ يَدَيۡهِ وَمِنۡ خَلۡفِهِۦ يَحۡفَظُونَهُۥ مِنۡ أَمۡرِ ٱللَّهِۗ إِنَّ ٱللَّهَ لَا يُغَيِّرُ مَا بِقَوۡمٍ حَتَّىٰ يُغَيِّرُواْ مَا بِأَنفُسِهِمۡۗ وَإِذَآ أَرَادَ ٱللَّهُ بِقَوۡمٖ سُوٓءٗا فَلَا مَرَدَّ لَهُۥۚ وَمَا لَهُم مِّن دُونِهِۦ مِن وَالٍ',
    translation:
      'For each one are successive [angels] before and behind him who protect him by the decree of Allah. Indeed, Allah will not change the condition of a people until they change what is in themselves. And when Allah intends for a people ill, there is no repelling it. And there is not for them besides Him any patron',
    source: {
      en: "Surah Ar-Ra'd 13:11",
      ar: 'سورة الرعد ١٣:١١',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-13-24',
    category: 'quran',
    kind: 'quran',
    arabic: 'سَلَٰمٌ عَلَيۡكُم بِمَا صَبَرۡتُمۡۚ فَنِعۡمَ عُقۡبَى ٱلدَّارِ',
    translation: 'Peace be upon you for what you patiently endured. And excellent is the final home',
    source: {
      en: "Surah Ar-Ra'd 13:24",
      ar: 'سورة الرعد ١٣:٢٤',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-15-9',
    category: 'quran',
    kind: 'quran',
    arabic: 'إِنَّا نَحۡنُ نَزَّلۡنَا ٱلذِّكۡرَ وَإِنَّا لَهُۥ لَحَٰفِظُونَ',
    translation: "Indeed, it is We who sent down the Qur'an and indeed, We will be its guardian",
    source: {
      en: 'Surah Al-Hijr 15:9',
      ar: 'سورة الحجر ١٥:٩',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'amiri',
  },
  {
    id: 'qv-16-18',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَإِن تَعُدُّواْ نِعۡمَةَ ٱللَّهِ لَا تُحۡصُوهَآۗ إِنَّ ٱللَّهَ لَغَفُورٞ رَّحِيمٞ',
    translation:
      'And if you should count the favors of Allah, you could not enumerate them. Indeed, Allah is Forgiving and Merciful',
    source: {
      en: 'Surah An-Nahl 16:18',
      ar: 'سورة النحل ١٦:١٨',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-16-90',
    category: 'quran',
    kind: 'quran',
    arabic:
      '۞إِنَّ ٱللَّهَ يَأۡمُرُ بِٱلۡعَدۡلِ وَٱلۡإِحۡسَٰنِ وَإِيتَآيِٕ ذِي ٱلۡقُرۡبَىٰ وَيَنۡهَىٰ عَنِ ٱلۡفَحۡشَآءِ وَٱلۡمُنكَرِ وَٱلۡبَغۡيِۚ يَعِظُكُمۡ لَعَلَّكُمۡ تَذَكَّرُونَ',
    translation:
      'Indeed, Allah orders justice and good conduct and giving to relatives and forbids immorality and bad conduct and oppression. He admonishes you that perhaps you will be reminded',
    source: {
      en: 'Surah An-Nahl 16:90',
      ar: 'سورة النحل ١٦:٩٠',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-16-97',
    category: 'quran',
    kind: 'quran',
    arabic:
      'مَنۡ عَمِلَ صَٰلِحٗا مِّن ذَكَرٍ أَوۡ أُنثَىٰ وَهُوَ مُؤۡمِنٞ فَلَنُحۡيِيَنَّهُۥ حَيَوٰةٗ طَيِّبَةٗۖ وَلَنَجۡزِيَنَّهُمۡ أَجۡرَهُم بِأَحۡسَنِ مَا كَانُواْ يَعۡمَلُونَ',
    translation:
      'Whoever does righteousness, whether male or female, while he is a believer - We will surely cause him to live a good life, and We will surely give them their reward [in the Hereafter] according to the best of what they used to do',
    source: {
      en: 'Surah An-Nahl 16:97',
      ar: 'سورة النحل ١٦:٩٧',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'mosque-sea',
    font: 'amiri',
  },
  {
    id: 'qv-17-37',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَلَا تَمۡشِ فِي ٱلۡأَرۡضِ مَرَحًاۖ إِنَّكَ لَن تَخۡرِقَ ٱلۡأَرۡضَ وَلَن تَبۡلُغَ ٱلۡجِبَالَ طُولٗا',
    translation:
      'And do not walk upon the earth exultantly. Indeed, you will never tear the earth [apart], and you will never reach the mountains in height',
    source: {
      en: 'Surah Al-Isra 17:37',
      ar: 'سورة الإسراء ١٧:٣٧',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-17-82',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَنُنَزِّلُ مِنَ ٱلۡقُرۡءَانِ مَا هُوَ شِفَآءٞ وَرَحۡمَةٞ لِّلۡمُؤۡمِنِينَ وَلَا يَزِيدُ ٱلظَّـٰلِمِينَ إِلَّا خَسَارٗا',
    translation:
      "And We send down of the Qur'an that which is healing and mercy for the believers, but it does not increase the wrongdoers except in loss",
    source: {
      en: 'Surah Al-Isra 17:82',
      ar: 'سورة الإسراء ١٧:٨٢',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-18-46',
    category: 'quran',
    kind: 'quran',
    arabic:
      'ٱلۡمَالُ وَٱلۡبَنُونَ زِينَةُ ٱلۡحَيَوٰةِ ٱلدُّنۡيَاۖ وَٱلۡبَٰقِيَٰتُ ٱلصَّـٰلِحَٰتُ خَيۡرٌ عِندَ رَبِّكَ ثَوَابٗا وَخَيۡرٌ أَمَلٗا',
    translation:
      "Wealth and children are [but] adornment of the worldly life. But the enduring good deeds are better to your Lord for reward and better for [one's] hope",
    source: {
      en: 'Surah Al-Kahf 18:46',
      ar: 'سورة الكهف ١٨:٤٦',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'amiri',
  },
  {
    id: 'qv-19-96',
    category: 'quran',
    kind: 'quran',
    arabic: 'إِنَّ ٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّـٰلِحَٰتِ سَيَجۡعَلُ لَهُمُ ٱلرَّحۡمَٰنُ وُدّٗا',
    translation:
      'Indeed, those who have believed and done righteous deeds - the Most Merciful will appoint for them affection',
    source: {
      en: 'Surah Maryam 19:96',
      ar: 'سورة مريم ١٩:٩٦',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-20-2-3',
    category: 'quran',
    kind: 'quran',
    arabic: 'مَآ أَنزَلۡنَا عَلَيۡكَ ٱلۡقُرۡءَانَ لِتَشۡقَىٰٓ ۝ إِلَّا تَذۡكِرَةٗ لِّمَن يَخۡشَىٰ',
    translation:
      "We have not sent down to you the Qur'an that you be distressed But only as a reminder for those who fear [Allah]",
    source: {
      en: 'Surah Taha 20:2-3',
      ar: 'سورة طه ٢٠:٢-٣',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-20-46',
    category: 'quran',
    kind: 'quran',
    arabic: 'قَالَ لَا تَخَافَآۖ إِنَّنِي مَعَكُمَآ أَسۡمَعُ وَأَرَىٰ',
    translation: '[Allah] said, "Fear not. Indeed, I am with you both; I hear and I see',
    source: {
      en: 'Surah Taha 20:46',
      ar: 'سورة طه ٢٠:٤٦',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'lavender-field',
    font: 'naskh',
  },
  {
    id: 'qv-21-107',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَمَآ أَرۡسَلۡنَٰكَ إِلَّا رَحۡمَةٗ لِّلۡعَٰلَمِينَ',
    translation: 'And We have not sent you, [O Muhammad], except as a mercy to the worlds',
    source: {
      en: 'Surah Al-Anbya 21:107',
      ar: 'سورة الأنبياء ٢١:١٠٧',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-25-63',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَعِبَادُ ٱلرَّحۡمَٰنِ ٱلَّذِينَ يَمۡشُونَ عَلَى ٱلۡأَرۡضِ هَوۡنٗا وَإِذَا خَاطَبَهُمُ ٱلۡجَٰهِلُونَ قَالُواْ سَلَٰمٗا',
    translation:
      'And the servants of the Most Merciful are those who walk upon the earth easily, and when the ignorant address them [harshly], they say [words of] peace',
    source: {
      en: 'Surah Al-Furqan 25:63',
      ar: 'سورة الفرقان ٢٥:٦٣',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-26-80',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَإِذَا مَرِضۡتُ فَهُوَ يَشۡفِينِ',
    translation: 'And when I am ill, it is He who cures me',
    source: {
      en: "Surah Ash-Shu'ara 26:80",
      ar: 'سورة الشعراء ٢٦:٨٠',
    },
    theme: 'burgundy-gold',
    decoration: 'none',
    background: 'wildflowers',
    font: 'naskh',
  },
  {
    id: 'qv-28-56',
    category: 'quran',
    kind: 'quran',
    arabic:
      'إِنَّكَ لَا تَهۡدِي مَنۡ أَحۡبَبۡتَ وَلَٰكِنَّ ٱللَّهَ يَهۡدِي مَن يَشَآءُۚ وَهُوَ أَعۡلَمُ بِٱلۡمُهۡتَدِينَ',
    translation:
      'Indeed, [O Muhammad], you do not guide whom you like, but Allah guides whom He wills. And He is most knowing of the [rightly] guided',
    source: {
      en: 'Surah Al-Qasas 28:56',
      ar: 'سورة القصص ٢٨:٥٦',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-29-2',
    category: 'quran',
    kind: 'quran',
    arabic: 'أَحَسِبَ ٱلنَّاسُ أَن يُتۡرَكُوٓاْ أَن يَقُولُوٓاْ ءَامَنَّا وَهُمۡ لَا يُفۡتَنُونَ',
    translation: 'Do the people think that they will be left to say, "We believe" and they will not be tried',
    source: {
      en: "Surah Al-'Ankabut 29:2",
      ar: 'سورة العنكبوت ٢٩:٢',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-29-45',
    category: 'quran',
    kind: 'quran',
    arabic:
      'ٱتۡلُ مَآ أُوحِيَ إِلَيۡكَ مِنَ ٱلۡكِتَٰبِ وَأَقِمِ ٱلصَّلَوٰةَۖ إِنَّ ٱلصَّلَوٰةَ تَنۡهَىٰ عَنِ ٱلۡفَحۡشَآءِ وَٱلۡمُنكَرِۗ وَلَذِكۡرُ ٱللَّهِ أَكۡبَرُۗ وَٱللَّهُ يَعۡلَمُ مَا تَصۡنَعُونَ',
    translation:
      'Recite, [O Muhammad], what has been revealed to you of the Book and establish prayer. Indeed, prayer prohibits immorality and wrongdoing, and the remembrance of Allah is greater. And Allah knows that which you do',
    source: {
      en: "Surah Al-'Ankabut 29:45",
      ar: 'سورة العنكبوت ٢٩:٤٥',
    },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'river-valley',
    font: 'amiri',
  },
  {
    id: 'qv-29-69',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَٱلَّذِينَ جَٰهَدُواْ فِينَا لَنَهۡدِيَنَّهُمۡ سُبُلَنَاۚ وَإِنَّ ٱللَّهَ لَمَعَ ٱلۡمُحۡسِنِينَ',
    translation:
      'And those who strive for Us - We will surely guide them to Our ways. And indeed, Allah is with the doers of good',
    source: {
      en: "Surah Al-'Ankabut 29:69",
      ar: 'سورة العنكبوت ٢٩:٦٩',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-31-17',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَٰبُنَيَّ أَقِمِ ٱلصَّلَوٰةَ وَأۡمُرۡ بِٱلۡمَعۡرُوفِ وَٱنۡهَ عَنِ ٱلۡمُنكَرِ وَٱصۡبِرۡ عَلَىٰ مَآ أَصَابَكَۖ إِنَّ ذَٰلِكَ مِنۡ عَزۡمِ ٱلۡأُمُورِ',
    translation:
      'O my son, establish prayer, enjoin what is right, forbid what is wrong, and be patient over what befalls you. Indeed, [all] that is of the matters [requiring] determination',
    source: {
      en: 'Surah Luqman 31:17',
      ar: 'سورة لقمان ٣١:١٧',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-31-18',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَلَا تُصَعِّرۡ خَدَّكَ لِلنَّاسِ وَلَا تَمۡشِ فِي ٱلۡأَرۡضِ مَرَحًاۖ إِنَّ ٱللَّهَ لَا يُحِبُّ كُلَّ مُخۡتَالٖ فَخُورٖ',
    translation:
      'And do not turn your cheek [in contempt] toward people and do not walk through the earth exultantly. Indeed, Allah does not like everyone self-deluded and boastful',
    source: {
      en: 'Surah Luqman 31:18',
      ar: 'سورة لقمان ٣١:١٨',
    },
    theme: 'ivory-gold',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'amiri',
  },
  {
    id: 'qv-33-41-42',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱذۡكُرُواْ ٱللَّهَ ذِكۡرٗا كَثِيرٗا ۝ وَسَبِّحُوهُ بُكۡرَةٗ وَأَصِيلًا',
    translation:
      'O you who have believed, remember Allah with much remembrance And exalt Him morning and afternoon',
    source: {
      en: 'Surah Al-Ahzab 33:41-42',
      ar: 'سورة الأحزاب ٣٣:٤١-٤٢',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-33-56',
    category: 'quran',
    kind: 'quran',
    arabic:
      'إِنَّ ٱللَّهَ وَمَلَـٰٓئِكَتَهُۥ يُصَلُّونَ عَلَى ٱلنَّبِيِّۚ يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ صَلُّواْ عَلَيۡهِ وَسَلِّمُواْ تَسۡلِيمًا',
    translation:
      'Indeed, Allah confers blessing upon the Prophet, and His angels [ask Him to do so]. O you who have believed, ask [Allah to confer] blessing upon him and ask [Allah to grant him] peace',
    source: {
      en: 'Surah Al-Ahzab 33:56',
      ar: 'سورة الأحزاب ٣٣:٥٦',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-33-70',
    category: 'quran',
    kind: 'quran',
    arabic: 'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱتَّقُواْ ٱللَّهَ وَقُولُواْ قَوۡلٗا سَدِيدٗا',
    translation: 'O you who have believed, fear Allah and speak words of appropriate justice',
    source: {
      en: 'Surah Al-Ahzab 33:70',
      ar: 'سورة الأحزاب ٣٣:٧٠',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    background: 'forest-light',
    font: 'scheherazade',
  },
  {
    id: 'qv-35-34',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَقَالُواْ ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِيٓ أَذۡهَبَ عَنَّا ٱلۡحَزَنَۖ إِنَّ رَبَّنَا لَغَفُورٞ شَكُورٌ',
    translation:
      'And they will say, "Praise to Allah, who has removed from us [all] sorrow. Indeed, our Lord is Forgiving and Appreciative',
    source: {
      en: 'Surah Fatir 35:34',
      ar: 'سورة فاطر ٣٥:٣٤',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-36-58',
    category: 'quran',
    kind: 'quran',
    arabic: 'سَلَٰمٞ قَوۡلٗا مِّن رَّبّٖ رَّحِيمٖ',
    translation: '[And] "Peace," a word from a Merciful Lord',
    source: {
      en: 'Surah Ya-Sin 36:58',
      ar: 'سورة يس ٣٦:٥٨',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-36-82',
    category: 'quran',
    kind: 'quran',
    arabic: 'إِنَّمَآ أَمۡرُهُۥٓ إِذَآ أَرَادَ شَيۡـًٔا أَن يَقُولَ لَهُۥ كُن فَيَكُونُ',
    translation: 'His command is only when He intends a thing that He says to it, "Be," and it is',
    source: {
      en: 'Surah Ya-Sin 36:82',
      ar: 'سورة يس ٣٦:٨٢',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-39-10',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلۡ يَٰعِبَادِ ٱلَّذِينَ ءَامَنُواْ ٱتَّقُواْ رَبَّكُمۡۚ لِلَّذِينَ أَحۡسَنُواْ فِي هَٰذِهِ ٱلدُّنۡيَا حَسَنَةٞۗ وَأَرۡضُ ٱللَّهِ وَٰسِعَةٌۗ إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجۡرَهُم بِغَيۡرِ حِسَابٖ',
    translation:
      'Say, "O My servants who have believed, fear your Lord. For those who do good in this world is good, and the earth of Allah is spacious. Indeed, the patient will be given their reward without account',
    source: {
      en: 'Surah Az-Zumar 39:10',
      ar: 'سورة الزمر ٣٩:١٠',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-39-36',
    category: 'quran',
    kind: 'quran',
    arabic:
      'أَلَيۡسَ ٱللَّهُ بِكَافٍ عَبۡدَهُۥۖ وَيُخَوِّفُونَكَ بِٱلَّذِينَ مِن دُونِهِۦۚ وَمَن يُضۡلِلِ ٱللَّهُ فَمَا لَهُۥ مِنۡ هَادٖ',
    translation:
      'Is not Allah sufficient for His Servant [Prophet Muhammad]? And [yet], they threaten you with those [they worship] other than Him. And whoever Allah leaves astray - for him there is no guide',
    source: {
      en: 'Surah Az-Zumar 39:36',
      ar: 'سورة الزمر ٣٩:٣٦',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-40-44',
    category: 'quran',
    kind: 'quran',
    arabic:
      'فَسَتَذۡكُرُونَ مَآ أَقُولُ لَكُمۡۚ وَأُفَوِّضُ أَمۡرِيٓ إِلَى ٱللَّهِۚ إِنَّ ٱللَّهَ بَصِيرُۢ بِٱلۡعِبَادِ',
    translation:
      'And you will remember what I [now] say to you, and I entrust my affair to Allah. Indeed, Allah is Seeing of [His] servants',
    source: {
      en: 'Surah Ghafir 40:44',
      ar: 'سورة غافر ٤٠:٤٤',
    },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'scheherazade',
  },
  {
    id: 'qv-41-30',
    category: 'quran',
    kind: 'quran',
    arabic:
      'إِنَّ ٱلَّذِينَ قَالُواْ رَبُّنَا ٱللَّهُ ثُمَّ ٱسۡتَقَٰمُواْ تَتَنَزَّلُ عَلَيۡهِمُ ٱلۡمَلَـٰٓئِكَةُ أَلَّا تَخَافُواْ وَلَا تَحۡزَنُواْ وَأَبۡشِرُواْ بِٱلۡجَنَّةِ ٱلَّتِي كُنتُمۡ تُوعَدُونَ',
    translation:
      'Indeed, those who have said, "Our Lord is Allah " and then remained on a right course - the angels will descend upon them, [saying], "Do not fear and do not grieve but receive good tidings of Paradise, which you were promised',
    source: {
      en: 'Surah Fussilat 41:30',
      ar: 'سورة فصلت ٤١:٣٠',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-41-34',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَلَا تَسۡتَوِي ٱلۡحَسَنَةُ وَلَا ٱلسَّيِّئَةُۚ ٱدۡفَعۡ بِٱلَّتِي هِيَ أَحۡسَنُ فَإِذَا ٱلَّذِي بَيۡنَكَ وَبَيۡنَهُۥ عَدَٰوَةٞ كَأَنَّهُۥ وَلِيٌّ حَمِيمٞ',
    translation:
      'And not equal are the good deed and the bad. Repel [evil] by that [deed] which is better; and thereupon the one whom between you and him is enmity [will become] as though he was a devoted friend',
    source: {
      en: 'Surah Fussilat 41:34',
      ar: 'سورة فصلت ٤١:٣٤',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-42-30',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَمَآ أَصَٰبَكُم مِّن مُّصِيبَةٖ فَبِمَا كَسَبَتۡ أَيۡدِيكُمۡ وَيَعۡفُواْ عَن كَثِيرٖ',
    translation:
      'And whatever strikes you of disaster - it is for what your hands have earned; but He pardons much',
    source: {
      en: 'Surah Ash-Shuraa 42:30',
      ar: 'سورة الشورى ٤٢:٣٠',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'starry-night',
    font: 'amiri',
  },
  {
    id: 'qv-49-13',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلنَّاسُ إِنَّا خَلَقۡنَٰكُم مِّن ذَكَرٖ وَأُنثَىٰ وَجَعَلۡنَٰكُمۡ شُعُوبٗا وَقَبَآئِلَ لِتَعَارَفُوٓاْۚ إِنَّ أَكۡرَمَكُمۡ عِندَ ٱللَّهِ أَتۡقَىٰكُمۡۚ إِنَّ ٱللَّهَ عَلِيمٌ خَبِيرٞ',
    translation:
      'O mankind, indeed We have created you from male and female and made you peoples and tribes that you may know one another. Indeed, the most noble of you in the sight of Allah is the most righteous of you. Indeed, Allah is Knowing and Acquainted',
    source: {
      en: 'Surah Al-Hujurat 49:13',
      ar: 'سورة الحجرات ٤٩:١٣',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-50-16',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَلَقَدۡ خَلَقۡنَا ٱلۡإِنسَٰنَ وَنَعۡلَمُ مَا تُوَسۡوِسُ بِهِۦ نَفۡسُهُۥۖ وَنَحۡنُ أَقۡرَبُ إِلَيۡهِ مِنۡ حَبۡلِ ٱلۡوَرِيدِ',
    translation:
      'And We have already created man and know what his soul whispers to him, and We are closer to him than [his] jugular vein',
    source: {
      en: 'Surah Qaf 50:16',
      ar: 'سورة ق ٥٠:١٦',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-51-56',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَمَا خَلَقۡتُ ٱلۡجِنَّ وَٱلۡإِنسَ إِلَّا لِيَعۡبُدُونِ',
    translation: 'And I did not create the jinn and mankind except to worship Me',
    source: {
      en: 'Surah Adh-Dhariyat 51:56',
      ar: 'سورة الذاريات ٥١:٥٦',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'mosque-sunset',
    font: 'amiri',
  },
  {
    id: 'qv-54-17',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَلَقَدۡ يَسَّرۡنَا ٱلۡقُرۡءَانَ لِلذِّكۡرِ فَهَلۡ مِن مُّدَّكِرٖ',
    translation:
      "And We have certainly made the Qur'an easy for remembrance, so is there any who will remember",
    source: {
      en: 'Surah Al-Qamar 54:17',
      ar: 'سورة القمر ٥٤:١٧',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-55-13',
    category: 'quran',
    kind: 'quran',
    arabic: 'فَبِأَيِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ',
    translation: 'So which of the favors of your Lord would you deny',
    source: {
      en: 'Surah Ar-Rahman 55:13',
      ar: 'سورة الرحمن ٥٥:١٣',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-57-4',
    category: 'quran',
    kind: 'quran',
    arabic:
      'هُوَ ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضَ فِي سِتَّةِ أَيَّامٖ ثُمَّ ٱسۡتَوَىٰ عَلَى ٱلۡعَرۡشِۖ يَعۡلَمُ مَا يَلِجُ فِي ٱلۡأَرۡضِ وَمَا يَخۡرُجُ مِنۡهَا وَمَا يَنزِلُ مِنَ ٱلسَّمَآءِ وَمَا يَعۡرُجُ فِيهَاۖ وَهُوَ مَعَكُمۡ أَيۡنَ مَا كُنتُمۡۚ وَٱللَّهُ بِمَا تَعۡمَلُونَ بَصِيرٞ',
    translation:
      'It is He who created the heavens and earth in six days and then established Himself above the Throne. He knows what penetrates into the earth and what emerges from it and what descends from the heaven and what ascends therein; and He is with you wherever you are. And Allah, of what you do, is Seeing',
    source: {
      en: 'Surah Al-Hadid 57:4',
      ar: 'سورة الحديد ٥٧:٤',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'amiri',
  },
  {
    id: 'qv-58-11',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓاْ إِذَا قِيلَ لَكُمۡ تَفَسَّحُواْ فِي ٱلۡمَجَٰلِسِ فَٱفۡسَحُواْ يَفۡسَحِ ٱللَّهُ لَكُمۡۖ وَإِذَا قِيلَ ٱنشُزُواْ فَٱنشُزُواْ يَرۡفَعِ ٱللَّهُ ٱلَّذِينَ ءَامَنُواْ مِنكُمۡ وَٱلَّذِينَ أُوتُواْ ٱلۡعِلۡمَ دَرَجَٰتٖۚ وَٱللَّهُ بِمَا تَعۡمَلُونَ خَبِيرٞ',
    translation:
      'O you who have believed, when you are told, "Space yourselves" in assemblies, then make space; Allah will make space for you. And when you are told, "Arise," then arise; Allah will raise those who have believed among you and those who were given knowledge, by degrees. And Allah is Acquainted with what you do',
    source: {
      en: 'Surah Al-Mujadila 58:11',
      ar: 'سورة المجادلة ٥٨:١١',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-64-11',
    category: 'quran',
    kind: 'quran',
    arabic:
      'مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذۡنِ ٱللَّهِۗ وَمَن يُؤۡمِنۢ بِٱللَّهِ يَهۡدِ قَلۡبَهُۥۚ وَٱللَّهُ بِكُلِّ شَيۡءٍ عَلِيمٞ',
    translation:
      'No disaster strikes except by permission of Allah. And whoever believes in Allah - He will guide his heart. And Allah is Knowing of all things',
    source: {
      en: 'Surah At-Taghabun 64:11',
      ar: 'سورة التغابن ٦٤:١١',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-67-2',
    category: 'quran',
    kind: 'quran',
    arabic:
      'ٱلَّذِي خَلَقَ ٱلۡمَوۡتَ وَٱلۡحَيَوٰةَ لِيَبۡلُوَكُمۡ أَيُّكُمۡ أَحۡسَنُ عَمَلٗاۚ وَهُوَ ٱلۡعَزِيزُ ٱلۡغَفُورُ',
    translation:
      '[He] who created death and life to test you [as to] which of you is best in deed - and He is the Exalted in Might, the Forgiving',
    source: {
      en: 'Surah Al-Mulk 67:2',
      ar: 'سورة الملك ٦٧:٢',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-68-4',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٖ',
    translation: 'And indeed, you are of a great moral character',
    source: {
      en: 'Surah Al-Qalam 68:4',
      ar: 'سورة القلم ٦٨:٤',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-73-8',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَٱذۡكُرِ ٱسۡمَ رَبِّكَ وَتَبَتَّلۡ إِلَيۡهِ تَبۡتِيلٗا',
    translation: 'And remember the name of your Lord and devote yourself to Him with [complete] devotion',
    source: {
      en: 'Surah Al-Muzzammil 73:8',
      ar: 'سورة المزمل ٧٣:٨',
    },
    theme: 'burgundy-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'naskh',
  },
  {
    id: 'qv-76-9',
    category: 'quran',
    kind: 'quran',
    arabic: 'إِنَّمَا نُطۡعِمُكُمۡ لِوَجۡهِ ٱللَّهِ لَا نُرِيدُ مِنكُمۡ جَزَآءٗ وَلَا شُكُورًا',
    translation:
      '[Saying], "We feed you only for the countenance of Allah. We wish not from you reward or gratitude',
    source: {
      en: 'Surah Al-Insan 76:9',
      ar: 'سورة الانسان ٧٦:٩',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-87-14-15',
    category: 'quran',
    kind: 'quran',
    arabic: 'قَدۡ أَفۡلَحَ مَن تَزَكَّىٰ ۝ وَذَكَرَ ٱسۡمَ رَبِّهِۦ فَصَلَّىٰ',
    translation:
      'He has certainly succeeded who purifies himself And mentions the name of his Lord and prays',
    source: {
      en: "Surah Al-A'la 87:14-15",
      ar: 'سورة الأعلى ٨٧:١٤-١٥',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-89-27-30',
    category: 'quran',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيَّتُهَا ٱلنَّفۡسُ ٱلۡمُطۡمَئِنَّةُ ۝ ٱرۡجِعِيٓ إِلَىٰ رَبِّكِ رَاضِيَةٗ مَّرۡضِيَّةٗ ۝ فَٱدۡخُلِي فِي عِبَٰدِي ۝ وَٱدۡخُلِي جَنَّتِي',
    translation:
      '[To the righteous it will be said], "O reassured soul Return to your Lord, well-pleased and pleasing [to Him] And enter among My [righteous] servants And enter My Paradise',
    source: {
      en: 'Surah Al-Fajr 89:27-30',
      ar: 'سورة الفجر ٨٩:٢٧-٣٠',
    },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'lavender-field',
    font: 'amiri',
  },
  {
    id: 'qv-91-9-10',
    category: 'quran',
    kind: 'quran',
    arabic: 'قَدۡ أَفۡلَحَ مَن زَكَّىٰهَا ۝ وَقَدۡ خَابَ مَن دَسَّىٰهَا',
    translation: 'He has succeeded who purifies it And he has failed who instills it [with corruption]',
    source: {
      en: 'Surah Ash-Shams 91:9-10',
      ar: 'سورة الشمس ٩١:٩-١٠',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-93-3',
    category: 'quran',
    kind: 'quran',
    arabic: 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ',
    translation: 'Your Lord has not taken leave of you, [O Muhammad], nor has He detested [you]',
    source: {
      en: 'Surah Ad-Duhaa 93:3',
      ar: 'سورة الضحى ٩٣:٣',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-93-4',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَلَلۡأٓخِرَةُ خَيۡرٞ لَّكَ مِنَ ٱلۡأُولَىٰ',
    translation: 'And the Hereafter is better for you than the first [life]',
    source: {
      en: 'Surah Ad-Duhaa 93:4',
      ar: 'سورة الضحى ٩٣:٤',
    },
    theme: 'ivory-gold',
    decoration: 'none',
    background: 'wildflowers',
    font: 'amiri',
  },
  {
    id: 'qv-93-7-8',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَوَجَدَكَ ضَآلّٗا فَهَدَىٰ ۝ وَوَجَدَكَ عَآئِلٗا فَأَغۡنَىٰ',
    translation:
      'And He found you lost and guided [you] And He found you poor and made [you] self-sufficient',
    source: {
      en: 'Surah Ad-Duhaa 93:7-8',
      ar: 'سورة الضحى ٩٣:٧-٨',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-93-11',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَأَمَّا بِنِعۡمَةِ رَبِّكَ فَحَدِّثۡ',
    translation: 'But as for the favor of your Lord, report [it]',
    source: {
      en: 'Surah Ad-Duhaa 93:11',
      ar: 'سورة الضحى ٩٣:١١',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-94-1-4',
    category: 'quran',
    kind: 'quran',
    arabic:
      'أَلَمۡ نَشۡرَحۡ لَكَ صَدۡرَكَ ۝ وَوَضَعۡنَا عَنكَ وِزۡرَكَ ۝ ٱلَّذِيٓ أَنقَضَ ظَهۡرَكَ ۝ وَرَفَعۡنَا لَكَ ذِكۡرَكَ',
    translation:
      'Did We not expand for you, [O Muhammad], your breast And We removed from you your burden Which had weighed upon your back And raised high for you your repute',
    source: {
      en: 'Surah Ash-Sharh 94:1-4',
      ar: 'سورة الشرح ٩٤:١-٤',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    background: 'river-valley',
    font: 'scheherazade',
  },
  {
    id: 'qv-96-1',
    category: 'quran',
    kind: 'quran',
    arabic: 'ٱقۡرَأۡ بِٱسۡمِ رَبِّكَ ٱلَّذِي خَلَقَ',
    translation: 'Recite in the name of your Lord who created',
    source: {
      en: "Surah Al-'Alaq 96:1",
      ar: 'سورة العلق ٩٦:١',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-103-1-3',
    category: 'quran',
    kind: 'quran',
    arabic:
      'وَٱلۡعَصۡرِ ۝ إِنَّ ٱلۡإِنسَٰنَ لَفِي خُسۡرٍ ۝ إِلَّا ٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّـٰلِحَٰتِ وَتَوَاصَوۡاْ بِٱلۡحَقِّ وَتَوَاصَوۡاْ بِٱلصَّبۡرِ',
    translation:
      'By time Indeed, mankind is in loss Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience',
    source: {
      en: "Surah Al-'Asr 103:1-3",
      ar: 'سورة العصر ١٠٣:١-٣',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-110-3',
    category: 'quran',
    kind: 'quran',
    arabic: 'فَسَبِّحۡ بِحَمۡدِ رَبِّكَ وَٱسۡتَغۡفِرۡهُۚ إِنَّهُۥ كَانَ تَوَّابَۢا',
    translation:
      'Then exalt [Him] with praise of your Lord and ask forgiveness of Him. Indeed, He is ever Accepting of repentance',
    source: {
      en: 'Surah An-Nasr 110:3',
      ar: 'سورة النصر ١١٠:٣',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'naskh',
  },
  {
    id: 'qv-112-1-4',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلۡ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمۡ يَلِدۡ وَلَمۡ يُولَدۡ ۝ وَلَمۡ يَكُن لَّهُۥ كُفُوًا أَحَدُۢ',
    translation:
      'Say, "He is Allah, [who is] One Allah, the Eternal Refuge He neither begets nor is born Nor is there to Him any equivalent',
    source: {
      en: 'Surah Al-Ikhlas 112:1-4',
      ar: 'سورة الإخلاص ١١٢:١-٤',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-62-10',
    category: 'friday',
    kind: 'quran',
    arabic:
      'فَإِذَا قُضِيَتِ ٱلصَّلَوٰةُ فَٱنتَشِرُواْ فِي ٱلۡأَرۡضِ وَٱبۡتَغُواْ مِن فَضۡلِ ٱللَّهِ وَٱذۡكُرُواْ ٱللَّهَ كَثِيرٗا لَّعَلَّكُمۡ تُفۡلِحُونَ',
    translation:
      'And when the prayer has been concluded, disperse within the land and seek from the bounty of Allah, and remember Allah often that you may succeed',
    source: {
      en: "Surah Al-Jumu'ah 62:10",
      ar: 'سورة الجمعة ٦٢:١٠',
    },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'forest-light',
    font: 'scheherazade',
  },
  {
    id: 'qv-2-183',
    category: 'ramadan',
    kind: 'quran',
    arabic:
      'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ كُتِبَ عَلَيۡكُمُ ٱلصِّيَامُ كَمَا كُتِبَ عَلَى ٱلَّذِينَ مِن قَبۡلِكُمۡ لَعَلَّكُمۡ تَتَّقُونَ',
    translation:
      'O you who have believed, decreed upon you is fasting as it was decreed upon those before you that you may become righteous',
    source: {
      en: 'Surah Al-Baqarah 2:183',
      ar: 'سورة البقرة ٢:١٨٣',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-2-184',
    category: 'ramadan',
    kind: 'quran',
    arabic:
      'أَيَّامٗا مَّعۡدُودَٰتٖۚ فَمَن كَانَ مِنكُم مَّرِيضًا أَوۡ عَلَىٰ سَفَرٖ فَعِدَّةٞ مِّنۡ أَيَّامٍ أُخَرَۚ وَعَلَى ٱلَّذِينَ يُطِيقُونَهُۥ فِدۡيَةٞ طَعَامُ مِسۡكِينٖۖ فَمَن تَطَوَّعَ خَيۡرٗا فَهُوَ خَيۡرٞ لَّهُۥۚ وَأَن تَصُومُواْ خَيۡرٞ لَّكُمۡ إِن كُنتُمۡ تَعۡلَمُونَ',
    translation:
      '[Fasting for] a limited number of days. So whoever among you is ill or on a journey [during them] - then an equal number of days [are to be made up]. And upon those who are able [to fast, but with hardship] - a ransom [as substitute] of feeding a poor person [each day]. And whoever volunteers excess - it is better for him. But to fast is best for you, if you only knew',
    source: {
      en: 'Surah Al-Baqarah 2:184',
      ar: 'سورة البقرة ٢:١٨٤',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-44-3-4',
    category: 'laylat-al-qadr',
    kind: 'quran',
    arabic:
      'إِنَّآ أَنزَلۡنَٰهُ فِي لَيۡلَةٖ مُّبَٰرَكَةٍۚ إِنَّا كُنَّا مُنذِرِينَ ۝ فِيهَا يُفۡرَقُ كُلُّ أَمۡرٍ حَكِيمٍ',
    translation:
      'Indeed, We sent it down during a blessed night. Indeed, We were to warn [mankind] On that night is made distinct every precise matter',
    source: {
      en: 'Surah Ad-Dukhan 44:3-4',
      ar: 'سورة الدخان ٤٤:٣-٤',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'amiri',
  },
  {
    id: 'qv-22-27',
    category: 'dhul-hijjah',
    kind: 'quran',
    arabic:
      'وَأَذِّن فِي ٱلنَّاسِ بِٱلۡحَجِّ يَأۡتُوكَ رِجَالٗا وَعَلَىٰ كُلِّ ضَامِرٖ يَأۡتِينَ مِن كُلِّ فَجٍّ عَمِيقٖ',
    translation:
      'And proclaim to the people the Hajj [pilgrimage]; they will come to you on foot and on every lean camel; they will come from every distant pass',
    source: {
      en: 'Surah Al-Hajj 22:27',
      ar: 'سورة الحج ٢٢:٢٧',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-22-28',
    category: 'dhul-hijjah',
    kind: 'quran',
    arabic:
      'لِّيَشۡهَدُواْ مَنَٰفِعَ لَهُمۡ وَيَذۡكُرُواْ ٱسۡمَ ٱللَّهِ فِيٓ أَيَّامٖ مَّعۡلُومَٰتٍ عَلَىٰ مَا رَزَقَهُم مِّنۢ بَهِيمَةِ ٱلۡأَنۡعَٰمِۖ فَكُلُواْ مِنۡهَا وَأَطۡعِمُواْ ٱلۡبَآئِسَ ٱلۡفَقِيرَ',
    translation:
      'That they may witness benefits for themselves and mention the name of Allah on known days over what He has provided for them of [sacrificial] animals. So eat of them and feed the miserable and poor',
    source: {
      en: 'Surah Al-Hajj 22:28',
      ar: 'سورة الحج ٢٢:٢٨',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-22-32',
    category: 'dhul-hijjah',
    kind: 'quran',
    arabic: 'ذَٰلِكَۖ وَمَن يُعَظِّمۡ شَعَـٰٓئِرَ ٱللَّهِ فَإِنَّهَا مِن تَقۡوَى ٱلۡقُلُوبِ',
    translation:
      'That [is so]. And whoever honors the symbols of Allah - indeed, it is from the piety of hearts',
    source: {
      en: 'Surah Al-Hajj 22:32',
      ar: 'سورة الحج ٢٢:٣٢',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'amiri',
  },
  {
    id: 'qv-22-26',
    category: 'dhul-hijjah',
    kind: 'quran',
    arabic:
      'وَإِذۡ بَوَّأۡنَا لِإِبۡرَٰهِيمَ مَكَانَ ٱلۡبَيۡتِ أَن لَّا تُشۡرِكۡ بِي شَيۡـٔٗا وَطَهِّرۡ بَيۡتِيَ لِلطَّآئِفِينَ وَٱلۡقَآئِمِينَ وَٱلرُّكَّعِ ٱلسُّجُودِ',
    translation:
      'And [mention, O Muhammad], when We designated for Abraham the site of the House, [saying], "Do not associate anything with Me and purify My House for those who perform Tawaf and those who stand [in prayer] and those who bow and prostrate',
    source: {
      en: 'Surah Al-Hajj 22:26',
      ar: 'سورة الحج ٢٢:٢٦',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-53-9-10',
    category: 'isra-miraj',
    kind: 'quran',
    arabic: 'فَكَانَ قَابَ قَوۡسَيۡنِ أَوۡ أَدۡنَىٰ ۝ فَأَوۡحَىٰٓ إِلَىٰ عَبۡدِهِۦ مَآ أَوۡحَىٰ',
    translation:
      'And was at a distance of two bow lengths or nearer And he revealed to His Servant what he revealed',
    source: {
      en: 'Surah An-Najm 53:9-10',
      ar: 'سورة النجم ٥٣:٩-١٠',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'starry-night',
    font: 'amiri',
  },
  {
    id: 'qv-17-79',
    category: 'evening',
    kind: 'quran',
    arabic:
      'وَمِنَ ٱلَّيۡلِ فَتَهَجَّدۡ بِهِۦ نَافِلَةٗ لَّكَ عَسَىٰٓ أَن يَبۡعَثَكَ رَبُّكَ مَقَامٗا مَّحۡمُودٗا',
    translation:
      'And from [part of] the night, pray with it as additional [worship] for you; it is expected that your Lord will resurrect you to a praised station',
    source: {
      en: 'Surah Al-Isra 17:79',
      ar: 'سورة الإسراء ١٧:٧٩',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-36-37-38',
    category: 'evening',
    kind: 'quran',
    arabic:
      'وَءَايَةٞ لَّهُمُ ٱلَّيۡلُ نَسۡلَخُ مِنۡهُ ٱلنَّهَارَ فَإِذَا هُم مُّظۡلِمُونَ ۝ وَٱلشَّمۡسُ تَجۡرِي لِمُسۡتَقَرّٖ لَّهَاۚ ذَٰلِكَ تَقۡدِيرُ ٱلۡعَزِيزِ ٱلۡعَلِيمِ',
    translation:
      'And a sign for them is the night. We remove from it [the light of] day, so they are [left] in darkness And the sun runs [on course] toward its stopping point. That is the determination of the Exalted in Might, the Knowing',
    source: {
      en: 'Surah Ya-Sin 36:37-38',
      ar: 'سورة يس ٣٦:٣٧-٣٨',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-73-6',
    category: 'evening',
    kind: 'quran',
    arabic: 'إِنَّ نَاشِئَةَ ٱلَّيۡلِ هِيَ أَشَدُّ وَطۡـٔٗا وَأَقۡوَمُ قِيلًا',
    translation:
      'Indeed, the hours of the night are more effective for concurrence [of heart and tongue] and more suitable for words',
    source: {
      en: 'Surah Al-Muzzammil 73:6',
      ar: 'سورة المزمل ٧٣:٦',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'mosque-sunset',
    font: 'naskh',
  },
  {
    id: 'qv-25-61-62',
    category: 'evening',
    kind: 'quran',
    arabic:
      'تَبَارَكَ ٱلَّذِي جَعَلَ فِي ٱلسَّمَآءِ بُرُوجٗا وَجَعَلَ فِيهَا سِرَٰجٗا وَقَمَرٗا مُّنِيرٗا ۝ وَهُوَ ٱلَّذِي جَعَلَ ٱلَّيۡلَ وَٱلنَّهَارَ خِلۡفَةٗ لِّمَنۡ أَرَادَ أَن يَذَّكَّرَ أَوۡ أَرَادَ شُكُورٗا',
    translation:
      'Blessed is He who has placed in the sky great stars and placed therein a [burning] lamp and luminous moon And it is He who has made the night and the day in succession for whoever desires to remember or desires gratitude',
    source: {
      en: 'Surah Al-Furqan 25:61-62',
      ar: 'سورة الفرقان ٢٥:٦١-٦٢',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-30-17-18',
    category: 'morning',
    kind: 'quran',
    arabic:
      'فَسُبۡحَٰنَ ٱللَّهِ حِينَ تُمۡسُونَ وَحِينَ تُصۡبِحُونَ ۝ وَلَهُ ٱلۡحَمۡدُ فِي ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ وَعَشِيّٗا وَحِينَ تُظۡهِرُونَ',
    translation:
      'So exalted is Allah when you reach the evening and when you reach the morning And to Him is [due all] praise throughout the heavens and the earth. And [exalted is He] at night and when you are at noon',
    source: {
      en: 'Surah Ar-Rum 30:17-18',
      ar: 'سورة الروم ٣٠:١٧-١٨',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-6-96',
    category: 'morning',
    kind: 'quran',
    arabic:
      'فَالِقُ ٱلۡإِصۡبَاحِ وَجَعَلَ ٱلَّيۡلَ سَكَنٗا وَٱلشَّمۡسَ وَٱلۡقَمَرَ حُسۡبَانٗاۚ ذَٰلِكَ تَقۡدِيرُ ٱلۡعَزِيزِ ٱلۡعَلِيمِ',
    translation:
      '[He is] the cleaver of daybreak and has made the night for rest and the sun and moon for calculation. That is the determination of the Exalted in Might, the Knowing',
    source: {
      en: "Surah Al-An'am 6:96",
      ar: 'سورة الأنعام ٦:٩٦',
    },
    theme: 'burgundy-gold',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'naskh',
  },
  {
    id: 'qv-78-9-11',
    category: 'morning',
    kind: 'quran',
    arabic:
      'وَجَعَلۡنَا نَوۡمَكُمۡ سُبَاتٗا ۝ وَجَعَلۡنَا ٱلَّيۡلَ لِبَاسٗا ۝ وَجَعَلۡنَا ٱلنَّهَارَ مَعَاشٗا',
    translation:
      'And made your sleep [a means for] rest And made the night as clothing And made the day for livelihood',
    source: {
      en: 'Surah An-Naba 78:9-11',
      ar: 'سورة النبإ ٧٨:٩-١١',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-93-1-2',
    category: 'morning',
    kind: 'quran',
    arabic: 'وَٱلضُّحَىٰ ۝ وَٱلَّيۡلِ إِذَا سَجَىٰ',
    translation: 'By the morning brightness And [by] the night when it covers with darkness',
    source: {
      en: 'Surah Ad-Duhaa 93:1-2',
      ar: 'سورة الضحى ٩٣:١-٢',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-91-1-4',
    category: 'morning',
    kind: 'quran',
    arabic:
      'وَٱلشَّمۡسِ وَضُحَىٰهَا ۝ وَٱلۡقَمَرِ إِذَا تَلَىٰهَا ۝ وَٱلنَّهَارِ إِذَا جَلَّىٰهَا ۝ وَٱلَّيۡلِ إِذَا يَغۡشَىٰهَا',
    translation:
      'By the sun and its brightness And [by] the moon when it follows it And [by] the day when it displays it And [by] the night when it covers it',
    source: {
      en: 'Surah Ash-Shams 91:1-4',
      ar: 'سورة الشمس ٩١:١-٤',
    },
    theme: 'rose-gold',
    decoration: 'none',
    background: 'mosque-sea',
    font: 'amiri',
  },
  {
    id: 'qv-30-21',
    category: 'occasions',
    kind: 'quran',
    headline: {
      en: 'For a marriage',
      ar: 'للزواج',
    },
    arabic:
      'وَمِنۡ ءَايَٰتِهِۦٓ أَنۡ خَلَقَ لَكُم مِّنۡ أَنفُسِكُمۡ أَزۡوَٰجٗا لِّتَسۡكُنُوٓاْ إِلَيۡهَا وَجَعَلَ بَيۡنَكُم مَّوَدَّةٗ وَرَحۡمَةًۚ إِنَّ فِي ذَٰلِكَ لَأٓيَٰتٖ لِّقَوۡمٖ يَتَفَكَّرُونَ',
    translation:
      'And of His signs is that He created for you from yourselves mates that you may find tranquillity in them; and He placed between you affection and mercy. Indeed in that are signs for a people who give thought',
    source: {
      en: 'Surah Ar-Rum 30:21',
      ar: 'سورة الروم ٣٠:٢١',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-25-74',
    category: 'occasions',
    kind: 'quran',
    headline: {
      en: 'For the family',
      ar: 'للأسرة',
    },
    arabic:
      'وَٱلَّذِينَ يَقُولُونَ رَبَّنَا هَبۡ لَنَا مِنۡ أَزۡوَٰجِنَا وَذُرِّيَّـٰتِنَا قُرَّةَ أَعۡيُنٖ وَٱجۡعَلۡنَا لِلۡمُتَّقِينَ إِمَامًا',
    translation:
      'And those who say, "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous',
    source: {
      en: 'Surah Al-Furqan 25:74',
      ar: 'سورة الفرقان ٢٥:٧٤',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-14-41',
    category: 'occasions',
    kind: 'quran',
    headline: {
      en: 'For our parents',
      ar: 'للوالدين',
    },
    arabic: 'رَبَّنَا ٱغۡفِرۡ لِي وَلِوَٰلِدَيَّ وَلِلۡمُؤۡمِنِينَ يَوۡمَ يَقُومُ ٱلۡحِسَابُ',
    translation: 'Our Lord, forgive me and my parents and the believers the Day the account is established',
    source: {
      en: 'Surah Ibrahim 14:41',
      ar: 'سورة ابراهيم ١٤:٤١',
    },
    theme: 'ivory-gold',
    decoration: 'none',
    background: 'cherry-blossom',
    font: 'amiri',
  },
  {
    id: 'qv-31-14',
    category: 'occasions',
    kind: 'quran',
    headline: {
      en: 'Gratitude to parents',
      ar: 'بر الوالدين',
    },
    arabic:
      'وَوَصَّيۡنَا ٱلۡإِنسَٰنَ بِوَٰلِدَيۡهِ حَمَلَتۡهُ أُمُّهُۥ وَهۡنًا عَلَىٰ وَهۡنٖ وَفِصَٰلُهُۥ فِي عَامَيۡنِ أَنِ ٱشۡكُرۡ لِي وَلِوَٰلِدَيۡكَ إِلَيَّ ٱلۡمَصِيرُ',
    translation:
      'And We have enjoined upon man [care] for his parents. His mother carried him, [increasing her] in weakness upon weakness, and his weaning is in two years. Be grateful to Me and to your parents; to Me is the [final] destination',
    source: {
      en: 'Surah Luqman 31:14',
      ar: 'سورة لقمان ٣١:١٤',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-2-250',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَلَمَّا بَرَزُواْ لِجَالُوتَ وَجُنُودِهِۦ قَالُواْ رَبَّنَآ أَفۡرِغۡ عَلَيۡنَا صَبۡرٗا وَثَبِّتۡ أَقۡدَامَنَا وَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ',
    translation:
      'And when they went forth to [face] Goliath and his soldiers, they said, "Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people',
    source: {
      en: 'Surah Al-Baqarah 2:250',
      ar: 'سورة البقرة ٢:٢٥٠',
    },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-3-147',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَمَا كَانَ قَوۡلَهُمۡ إِلَّآ أَن قَالُواْ رَبَّنَا ٱغۡفِرۡ لَنَا ذُنُوبَنَا وَإِسۡرَافَنَا فِيٓ أَمۡرِنَا وَثَبِّتۡ أَقۡدَامَنَا وَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ',
    translation:
      'And their words were not but that they said, "Our Lord, forgive us our sins and the excess [committed] in our affairs and plant firmly our feet and give us victory over the disbelieving people',
    source: {
      en: "Surah Ali 'Imran 3:147",
      ar: 'سورة آل عمران ٣:١٤٧',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    background: 'lavender-field',
    font: 'scheherazade',
  },
  {
    id: 'qv-7-126',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَمَا تَنقِمُ مِنَّآ إِلَّآ أَنۡ ءَامَنَّا بِـَٔايَٰتِ رَبِّنَا لَمَّا جَآءَتۡنَاۚ رَبَّنَآ أَفۡرِغۡ عَلَيۡنَا صَبۡرٗا وَتَوَفَّنَا مُسۡلِمِينَ',
    translation:
      'And you do not resent us except because we believed in the signs of our Lord when they came to us. Our Lord, pour upon us patience and let us die as Muslims [in submission to You]',
    source: {
      en: "Surah Al-A'raf 7:126",
      ar: 'سورة الأعراف ٧:١٢٦',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-7-151',
    category: 'dua',
    kind: 'dua',
    arabic: 'قَالَ رَبِّ ٱغۡفِرۡ لِي وَلِأَخِي وَأَدۡخِلۡنَا فِي رَحۡمَتِكَۖ وَأَنتَ أَرۡحَمُ ٱلرَّـٰحِمِينَ',
    translation:
      '[Moses] said, "My Lord, forgive me and my brother and admit us into Your mercy, for You are the most merciful of the merciful',
    source: {
      en: "Surah Al-A'raf 7:151",
      ar: 'سورة الأعراف ٧:١٥١',
    },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'amiri',
  },
  {
    id: 'qv-18-10',
    category: 'dua',
    kind: 'dua',
    arabic:
      'إِذۡ أَوَى ٱلۡفِتۡيَةُ إِلَى ٱلۡكَهۡفِ فَقَالُواْ رَبَّنَآ ءَاتِنَا مِن لَّدُنكَ رَحۡمَةٗ وَهَيِّئۡ لَنَا مِنۡ أَمۡرِنَا رَشَدٗا',
    translation:
      '[Mention] when the youths retreated to the cave and said, "Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance',
    source: {
      en: 'Surah Al-Kahf 18:10',
      ar: 'سورة الكهف ١٨:١٠',
    },
    theme: 'desert-dawn',
    decoration: 'none',
    background: 'wildflowers',
    font: 'naskh',
  },
  {
    id: 'qv-21-87',
    category: 'dua',
    kind: 'dua',
    headline: {
      en: 'Duaa of Yunus',
      ar: 'دعاء ذي النون',
    },
    arabic:
      'وَذَا ٱلنُّونِ إِذ ذَّهَبَ مُغَٰضِبٗا فَظَنَّ أَن لَّن نَّقۡدِرَ عَلَيۡهِ فَنَادَىٰ فِي ٱلظُّلُمَٰتِ أَن لَّآ إِلَٰهَ إِلَّآ أَنتَ سُبۡحَٰنَكَ إِنِّي كُنتُ مِنَ ٱلظَّـٰلِمِينَ',
    translation:
      'And [mention] the man of the fish, when he went off in anger and thought that We would not decree [anything] upon him. And he called out within the darknesses, "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers',
    source: {
      en: 'Surah Al-Anbya 21:87',
      ar: 'سورة الأنبياء ٢١:٨٧',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-21-89',
    category: 'dua',
    kind: 'dua',
    arabic: 'وَزَكَرِيَّآ إِذۡ نَادَىٰ رَبَّهُۥ رَبِّ لَا تَذَرۡنِي فَرۡدٗا وَأَنتَ خَيۡرُ ٱلۡوَٰرِثِينَ',
    translation:
      'And [mention] Zechariah, when he called to his Lord, "My Lord, do not leave me alone [with no heir], while you are the best of inheritors',
    source: {
      en: 'Surah Al-Anbya 21:89',
      ar: 'سورة الأنبياء ٢١:٨٩',
    },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-23-118',
    category: 'dua',
    kind: 'dua',
    arabic: 'وَقُل رَّبِّ ٱغۡفِرۡ وَٱرۡحَمۡ وَأَنتَ خَيۡرُ ٱلرَّـٰحِمِينَ',
    translation:
      'And, [O Muhammad], say, "My Lord, forgive and have mercy, and You are the best of the merciful',
    source: {
      en: "Surah Al-Mu'minun 23:118",
      ar: 'سورة المؤمنون ٢٣:١١٨',
    },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'river-valley',
    font: 'scheherazade',
  },
  {
    id: 'qv-25-65',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَٱلَّذِينَ يَقُولُونَ رَبَّنَا ٱصۡرِفۡ عَنَّا عَذَابَ جَهَنَّمَۖ إِنَّ عَذَابَهَا كَانَ غَرَامًا',
    translation:
      'And those who say, "Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering',
    source: {
      en: 'Surah Al-Furqan 25:65',
      ar: 'سورة الفرقان ٢٥:٦٥',
    },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'qv-26-83-85',
    category: 'dua',
    kind: 'dua',
    arabic:
      'رَبِّ هَبۡ لِي حُكۡمٗا وَأَلۡحِقۡنِي بِٱلصَّـٰلِحِينَ ۝ وَٱجۡعَل لِّي لِسَانَ صِدۡقٖ فِي ٱلۡأٓخِرِينَ ۝ وَٱجۡعَلۡنِي مِن وَرَثَةِ جَنَّةِ ٱلنَّعِيمِ',
    translation:
      '[And he said], "My Lord, grant me authority and join me with the righteous And grant me a reputation of honor among later generations And place me among the inheritors of the Garden of Pleasure',
    source: {
      en: "Surah Ash-Shu'ara 26:83-85",
      ar: 'سورة الشعراء ٢٦:٨٣-٨٥',
    },
    theme: 'royal-purple',
    decoration: 'crescent',
    font: 'naskh',
  },
  {
    id: 'qv-27-19',
    category: 'dua',
    kind: 'dua',
    arabic:
      'فَتَبَسَّمَ ضَاحِكٗا مِّن قَوۡلِهَا وَقَالَ رَبِّ أَوۡزِعۡنِيٓ أَنۡ أَشۡكُرَ نِعۡمَتَكَ ٱلَّتِيٓ أَنۡعَمۡتَ عَلَيَّ وَعَلَىٰ وَٰلِدَيَّ وَأَنۡ أَعۡمَلَ صَٰلِحٗا تَرۡضَىٰهُ وَأَدۡخِلۡنِي بِرَحۡمَتِكَ فِي عِبَادِكَ ٱلصَّـٰلِحِينَ',
    translation:
      'So [Solomon] smiled, amused at her speech, and said, "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents and to do righteousness of which You approve. And admit me by Your mercy into [the ranks of] Your righteous servants',
    source: {
      en: 'Surah An-Naml 27:19',
      ar: 'سورة النمل ٢٧:١٩',
    },
    theme: 'olive-sage',
    decoration: 'none',
    background: 'mountain-lake',
    font: 'amiri',
  },
  {
    id: 'qv-28-24',
    category: 'dua',
    kind: 'dua',
    arabic:
      'فَسَقَىٰ لَهُمَا ثُمَّ تَوَلَّىٰٓ إِلَى ٱلظِّلِّ فَقَالَ رَبِّ إِنِّي لِمَآ أَنزَلۡتَ إِلَيَّ مِنۡ خَيۡرٖ فَقِيرٞ',
    translation:
      'So he watered [their flocks] for them; then he went back to the shade and said, "My Lord, indeed I am, for whatever good You would send down to me, in need',
    source: {
      en: 'Surah Al-Qasas 28:24',
      ar: 'سورة القصص ٢٨:٢٤',
    },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'qv-59-10',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَٱلَّذِينَ جَآءُو مِنۢ بَعۡدِهِمۡ يَقُولُونَ رَبَّنَا ٱغۡفِرۡ لَنَا وَلِإِخۡوَٰنِنَا ٱلَّذِينَ سَبَقُونَا بِٱلۡإِيمَٰنِ وَلَا تَجۡعَلۡ فِي قُلُوبِنَا غِلّٗا لِّلَّذِينَ ءَامَنُواْ رَبَّنَآ إِنَّكَ رَءُوفٞ رَّحِيمٌ',
    translation:
      'And [there is a share for] those who came after them, saying, "Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts [any] resentment toward those who have believed. Our Lord, indeed You are Kind and Merciful',
    source: {
      en: 'Surah Al-Hashr 59:10',
      ar: 'سورة الحشر ٥٩:١٠',
    },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'qv-71-28',
    category: 'dua',
    kind: 'dua',
    arabic:
      'رَّبِّ ٱغۡفِرۡ لِي وَلِوَٰلِدَيَّ وَلِمَن دَخَلَ بَيۡتِيَ مُؤۡمِنٗا وَلِلۡمُؤۡمِنِينَ وَٱلۡمُؤۡمِنَٰتِۖ وَلَا تَزِدِ ٱلظَّـٰلِمِينَ إِلَّا تَبَارَۢا',
    translation:
      'My Lord, forgive me and my parents and whoever enters my house a believer and the believing men and believing women. And do not increase the wrongdoers except in destruction',
    source: {
      en: 'Surah Nuh 71:28',
      ar: 'سورة نوح ٧١:٢٨',
    },
    theme: 'teal-lagoon',
    decoration: 'none',
    background: 'forest-light',
    font: 'amiri',
  },
  {
    id: 'qv-3-16',
    category: 'dua',
    kind: 'dua',
    arabic:
      'ٱلَّذِينَ يَقُولُونَ رَبَّنَآ إِنَّنَآ ءَامَنَّا فَٱغۡفِرۡ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ ٱلنَّارِ',
    translation:
      'Those who say, "Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire',
    source: {
      en: "Surah Ali 'Imran 3:16",
      ar: 'سورة آل عمران ٣:١٦',
    },
    theme: 'desert-dawn',
    decoration: 'sunrise',
    font: 'naskh',
  },
  {
    id: 'qv-3-53',
    category: 'dua',
    kind: 'dua',
    arabic: 'رَبَّنَآ ءَامَنَّا بِمَآ أَنزَلۡتَ وَٱتَّبَعۡنَا ٱلرَّسُولَ فَٱكۡتُبۡنَا مَعَ ٱلشَّـٰهِدِينَ',
    translation:
      'Our Lord, we have believed in what You revealed and have followed the messenger Jesus, so register us among the witnesses [to truth]',
    source: {
      en: "Surah Ali 'Imran 3:53",
      ar: 'سورة آل عمران ٣:٥٣',
    },
    theme: 'rose-gold',
    decoration: 'none',
    font: 'amiri',
  },
  {
    id: 'qv-10-85-86',
    category: 'dua',
    kind: 'dua',
    arabic:
      'فَقَالُواْ عَلَى ٱللَّهِ تَوَكَّلۡنَا رَبَّنَا لَا تَجۡعَلۡنَا فِتۡنَةٗ لِّلۡقَوۡمِ ٱلظَّـٰلِمِينَ ۝ وَنَجِّنَا بِرَحۡمَتِكَ مِنَ ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ',
    translation:
      'So they said, "Upon Allah do we rely. Our Lord, make us not [objects of] trial for the wrongdoing people And save us by Your mercy from the disbelieving people',
    source: {
      en: 'Surah Yunus 10:85-86',
      ar: 'سورة يونس ١٠:٨٥-٨٦',
    },
    theme: 'emerald-night',
    decoration: 'none',
    background: 'ocean-sunrise',
    font: 'amiri',
  },
  {
    id: 'qv-14-35',
    category: 'dua',
    kind: 'dua',
    arabic:
      'وَإِذۡ قَالَ إِبۡرَٰهِيمُ رَبِّ ٱجۡعَلۡ هَٰذَا ٱلۡبَلَدَ ءَامِنٗا وَٱجۡنُبۡنِي وَبَنِيَّ أَن نَّعۡبُدَ ٱلۡأَصۡنَامَ',
    translation:
      'And [mention, O Muhammad], when Abraham said, "My Lord, make this city [Makkah] secure and keep me and my sons away from worshipping idols',
    source: {
      en: 'Surah Ibrahim 14:35',
      ar: 'سورة ابراهيم ١٤:٣٥',
    },
    theme: 'midnight-blue',
    decoration: 'stars',
    font: 'scheherazade',
  },
  {
    id: 'qv-3-193',
    category: 'dua',
    kind: 'dua',
    arabic:
      'رَّبَّنَآ إِنَّنَا سَمِعۡنَا مُنَادِيٗا يُنَادِي لِلۡإِيمَٰنِ أَنۡ ءَامِنُواْ بِرَبِّكُمۡ فَـَٔامَنَّاۚ رَبَّنَا فَٱغۡفِرۡ لَنَا ذُنُوبَنَا وَكَفِّرۡ عَنَّا سَيِّـَٔاتِنَا وَتَوَفَّنَا مَعَ ٱلۡأَبۡرَارِ',
    translation:
      "Our Lord, indeed we have heard a caller calling to faith, [saying], 'Believe in your Lord,' and we have believed. Our Lord, so forgive us our sins and remove from us our misdeeds and cause us to die with the righteous",
    source: {
      en: "Surah Ali 'Imran 3:193",
      ar: 'سورة آل عمران ٣:١٩٣',
    },
    theme: 'royal-purple',
    decoration: 'none',
    background: 'desert-dusk',
    font: 'naskh',
  },
];
