import type { Post } from '../../types';

export const ramadanPosts: Post[] = [
  {
    id: 'ramadan-greeting',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan Kareem', ar: 'رمضان كريم' },
    arabic: 'أَعادَهُ اللهُ عَلَيكُم بِالخَيرِ وَاليُمنِ وَالبَرَكات، وَتَقَبَّلَ صِيامَكُم وَقِيامَكُم',
    translation:
      'May Allah return it upon you with goodness and blessings, and accept your fasting and prayers.',
    translations: {
      fr: "Qu'Allah vous le ramène avec bien et bénédiction, et accepte votre jeûne et vos prières.",
      id: 'Semoga Allah mengembalikannya kepada Anda dengan kebaikan dan keberkahan, serta menerima puasa dan salat Anda.',
      ms: 'Semoga Allah mengembalikannya kepada anda dengan kebaikan dan keberkatan, serta menerima puasa dan solat anda.',
      th: 'ขออัลลอฮฺทรงนำมันกลับมาสู่ท่านพร้อมความดีและความจำเริญ และทรงตอบรับการถือศีลอดและการละหมาดของท่าน',
      ur: 'اللہ اسے آپ پر خیر و برکت کے ساتھ لوٹائے، اور آپ کے روزے اور نمازیں قبول فرمائے۔',
    },
    theme: 'emerald-night',
    decoration: 'lanterns',
    font: 'aref-ruqaa',
  },
  {
    id: 'ramadan-mubarak',
    category: 'ramadan',
    kind: 'greeting',
    headline: { en: 'Ramadan Mubarak', ar: 'رمضان مبارك' },
    arabic: 'اللَّهُمَّ بَلِّغْنا رَمَضانَ لا فاقِدينَ وَلا مَفقودين',
    translation: 'O Allah, let us reach Ramadan, neither missing anyone nor being missed.',
    translations: {
      fr: 'Ô Allah, fais que nous atteignions Ramadan, sans manquer personne et sans manquer à personne.',
      id: 'Ya Allah, sampaikanlah kami pada Ramadan, tanpa kehilangan siapa pun dan tanpa ada yang kehilangan kami.',
      ms: 'Ya Allah, sampaikanlah kami kepada Ramadan, tanpa kehilangan sesiapa pun dan tanpa ada yang kehilangan kami.',
      th: 'โอ้อัลลอฮฺ ขอให้เราได้พบรอมฎอน โดยไม่ขาดผู้ใดและไม่มีผู้ใดขาดเรา',
      ur: 'اے اللہ، ہمیں رمضان تک پہنچا، نہ ہم کسی کو کھوئیں اور نہ کوئی ہمیں۔',
    },
    theme: 'midnight-blue',
    decoration: 'none',
    background: 'mosque-courtyard',
    font: 'cairo',
  },
  {
    id: 'ramadan-verse',
    category: 'ramadan',
    kind: 'quran',
    arabic:
      'شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ هُدًى لِّلنَّاسِ وَبَيِّنَاتٍ مِّنَ الْهُدَىٰ وَالْفُرْقَانِ',
    translation:
      'The month of Ramadan is that in which the Quran was revealed, a guidance for mankind and clear proofs of guidance and the criterion.',
    source: { en: 'Surah Al-Baqarah 2:185', ar: 'سورة البقرة ٢:١٨٥' },
    theme: 'ivory-gold',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'ramadan-forgiveness',
    category: 'ramadan',
    kind: 'hadith',
    arabic: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    translation: 'Whoever fasts Ramadan out of faith and seeking reward, his previous sins will be forgiven.',
    source: { en: 'Sahih al-Bukhari 38, Sahih Muslim 760', ar: 'صحيح البخاري ٣٨، صحيح مسلم ٧٦٠' },
    theme: 'burgundy-gold',
    decoration: 'crescent',
    font: 'scheherazade',
  },
  {
    id: 'ramadan-gates',
    category: 'ramadan',
    kind: 'hadith',
    arabic:
      'إِذَا جَاءَ رَمَضَانُ فُتِّحَتْ أَبْوَابُ الْجَنَّةِ، وَغُلِّقَتْ أَبْوَابُ النَّارِ، وَصُفِّدَتِ الشَّيَاطِينُ',
    translation:
      'When Ramadan comes, the gates of Paradise are opened, the gates of Hell are closed, and the devils are chained.',
    source: { en: 'Sahih al-Bukhari 1899, Sahih Muslim 1079', ar: 'صحيح البخاري ١٨٩٩، صحيح مسلم ١٠٧٩' },
    theme: 'royal-purple',
    decoration: 'mosque',
    font: 'naskh',
  },
  {
    id: 'ramadan-iftar',
    category: 'ramadan',
    kind: 'dua',
    headline: { en: 'Duaa at iftar', ar: 'دعاء الإفطار' },
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    translation: 'The thirst is gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    source: { en: 'Abu Dawud 2357', ar: 'أبو داود ٢٣٥٧' },
    theme: 'desert-dawn',
    decoration: 'lanterns',
    font: 'amiri',
  },
];
