import type { Post } from '@/domain/types';

export const quranPosts: Post[] = [
  {
    id: 'quran-remember-me',
    category: 'quran',
    kind: 'quran',
    arabic: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
    translation: 'So remember Me; I will remember you. And be grateful to Me and do not deny Me.',
    source: { en: 'Surah Al-Baqarah 2:152', ar: 'سورة البقرة ٢:١٥٢' },
    theme: 'emerald-night',
    decoration: 'arch',
    font: 'amiri',
  },
  {
    id: 'quran-tawakkul',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
    translation: 'And whoever relies upon Allah, then He is sufficient for him.',
    source: { en: 'Surah At-Talaq 65:3', ar: 'سورة الطلاق ٦٥:٣' },
    theme: 'teal-lagoon',
    decoration: 'crescent',
    font: 'aref-ruqaa',
  },
  {
    id: 'quran-burden',
    category: 'quran',
    kind: 'quran',
    arabic: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
    translation: 'Allah does not burden a soul beyond what it can bear.',
    source: { en: 'Surah Al-Baqarah 2:286', ar: 'سورة البقرة ٢:٢٨٦' },
    theme: 'charcoal-minimal',
    decoration: 'none',
    font: 'scheherazade',
  },
  {
    id: 'quran-despair',
    category: 'quran',
    kind: 'quran',
    arabic:
      'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا',
    translation:
      'Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins.',
    source: { en: 'Surah Az-Zumar 39:53', ar: 'سورة الزمر ٣٩:٥٣' },
    theme: 'rose-gold',
    decoration: 'sunrise',
    font: 'amiri',
  },
  {
    id: 'quran-do-not-grieve',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ',
    translation: 'Do not weaken and do not grieve, for you will be superior if you are true believers.',
    source: { en: 'Surah Al Imran 3:139', ar: 'سورة آل عمران ٣:١٣٩' },
    theme: 'burgundy-gold',
    decoration: 'stars',
    font: 'naskh',
  },
  {
    id: 'quran-call-me',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ',
    translation: 'And your Lord says: Call upon Me; I will respond to you.',
    source: { en: 'Surah Ghafir 40:60', ar: 'سورة غافر ٤٠:٦٠' },
    theme: 'midnight-blue',
    decoration: 'crescent',
    font: 'aref-ruqaa',
  },
  {
    id: 'quran-patience',
    category: 'quran',
    kind: 'quran',
    arabic: 'وَاصْبِرْ وَمَا صَبْرُكَ إِلَّا بِاللَّهِ',
    translation: 'And be patient, and your patience is only through Allah.',
    source: { en: 'Surah An-Nahl 16:127', ar: 'سورة النحل ١٦:١٢٧' },
    theme: 'olive-sage',
    decoration: 'none',
    font: 'amiri',
  },
];
