/**
 * Translations for the transmitted story cards — hadith, duaa and dhikr — taken
 * from published editions.
 * Generated by scripts/gen-hadith-translations.mjs — do not edit by hand.
 *
 * Each card is matched to a hadith by its Arabic appearing as a run inside it,
 * not by the number it cites and not by scattered words. The Prophet's words are
 * then lifted out of the published narration, which carries its chain of
 * narrators, and anything still wildly longer or shorter than the English keeps
 * its English instead.
 *
 * Malay and Thai are absent: no edition of any of these collections exists for
 * them in this dataset.
 */
import type { Locale } from '../types';

export const HADITH_TRANSLATION_CREDITS: Partial<Record<Locale, string>> = {
  fr: 'hadith-api, éditions françaises',
  id: 'hadith-api, edisi Indonesia',
  ur: 'hadith-api، اردو ایڈیشن',
};

/** Card id to its translation in each locale that has an edition. */
export const HADITH_TRANSLATIONS: Record<string, Partial<Record<Locale, string>>> = {
  'dh-best-dhikr': {
    fr: 'Celui qui ment volontairement à mon sujet, qu’il prépare sa place en Enfer.',
    id: 'Barangsiapa yang sengaja melakukan kedustaan atas namaku, maka hendaklah dia menempati tempat duduknya dari neraka',
    ur: 'تھا : ’’جس نے عمداً مجھ پر جھوٹ بولا وہ آگ میں اپنا ٹھکانا بنا لے',
  },
  'dh-four-words': {
    fr: 'Ceux qui possèdent beaucoup de richesses ont obtenu les plus hauts rangs et le bonheur éternel.',
    id: 'Kalian bertasbih, bertakbir, dan bertahmid setiap habis shalat sebanyak tiga puluh tiga kali.',
  },
  'dh-hawqala': {
    fr: 'Informe-moi sur l’Heure (du Jugement).',
    id: 'Wahai Umar, apakah kamu tahu siapa penanya tersebut?',
    ur: '’’وہ جبرئیل تھے ، تمہارے پاس آئے تھے ، تمہیں تمہارا دین سکھا رہے تھے ۔ ‘ ‘',
  },
  'dh-istighfar-100': {
    fr: 'En effet, je l’ai vu lorsque ce verset a été révélé :',
  },
  'dh-ibrahimiyya': {
    fr: 'Allah nous a ordonné de prier pour toi. Messager d’Allah, comment devons-nous prier pour toi ?',
    id: "Katakanlah, 'ALLOOHUMMA SHOLLI 'ALAA MUHAMMAD WA'ALAA AALI MUHAMMAD, KAMAA SHOLLAITA 'ALAA AALI IBROOHIIMA WABAARIK 'ALAA MUHAMMAD WA'ALAA AALI MUHAMMAD KAMAA BAAROKTA 'ALAA AALI IBROOHIIMA FIL'AALAMIINA INNAKA HAMIIDUN MAJIID.",
    ur: '’’ کہو : اے اللہ! رحمت فرما محمد اور محمد کی آل پر ، جیسے تو نے رحمت فرمائی ابراہیم کی آل پر اور برکت نازل فرما محمد اور محمد کی آل پر ، جیسے تو نے سب جہانوں میں برکت نازل فرمائی ابراہیم کی آل پر ، بلاشبہ تو سزا وار حمد ہے ، عظمتوں والا ہے اور سلام اسی طرح ہے جیسے تم ( پہلے ) جان چکے ہو ۔ ‘ ‘',
  },
  'dh-allahu-akbar-kabira': {
    fr: 'Allah est vraiment le plus Grand, louange à Allah en abondance, gloire à Allah matin et soir.',
    id: 'Sungguh aku sangat kagum dengan ucapan tadi, sebab pintu-pintu langit dibuka karena kalimat itu.',
    ur: '’’مجھے ان پر بہت حیرت ہوئی ، ان کے لیے آسمان کے دروازے کھول دیے گئے ۔ ‘ ‘ ابن عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے کہا : میں نے جب سے آپ سے یہ بات سنی ، اس کےبعد سے ان کلمات کو کبھی ترک نہیں کیا ۔',
  },
  'dh-waking': {
    fr: 'Louange à Allah qui nous a redonné la vie après notre mort (le sommeil), et vers Toi est la résurrection.',
    id: 'ALLOOHUMMA, BISMIKALLOOHUMMA AHYAA WABISMIKA AMUUTU',
    ur: 'اے اللہ! میں تیرے نام سے جیتا ہوں اور تیرے نام سے وفات پاؤں گا',
  },
  'arafah-free': {
    fr: 'Il n’y a pas de jour où Allah affranchit plus de gens de l’Enfer que le jour de ‘Arafa. Il s’approche, puis fait leur éloge auprès des anges en disant : “Que veulent-ils ?”',
    ur: 'کوئی دن نہیں جس میں اللہ تعالیٰ عرفہ کے دن سے بڑھ کر بندوں کو آگ سے آزاد فرماتا ہو ، وہ ( اپنے بندوں کے ) قریب ہوتا ہے ۔ اور فرشتوں کے سامنے ان لوگوں کی بناء پر فخر کرتا ہے اور پوچھتا ہے : یہ لوگ کیا چاہتے ہیں؟',
  },
  'arafah-fast': {
    fr: 'Il n’a ni jeûné ni rompu son jeûne, ou il a dit : Il n’a ni jeûné ni arrêté.',
    id: 'Kami rela Allah sebagai Tuhan, Islam sebagai agama dan Muhammad sebagai Rasul. Kami berlindung kepada Allah, dari murka Allah dan Rasul-Nya.',
    ur: 'مجھے پسند ہے کہ مجھے اس کی طاقت مل جاتی ۔ پھر رسول اللہ صلی اللہ علیہ وسلم نے فرمایا :',
  },
  'arafah-dua': {
    fr: 'Il n’y a de dieu qu’Allah, Il est Seul, sans associé. À Lui appartient la royauté, à Lui la louange, et Il est capable de toute chose. Ô Allah ! Nul ne peut retenir ce que Tu donnes, ni donner ce que Tu retiens, et la richesse ne sert à rien à un riche devant Toi.',
    id: 'Lalu Mughirah mendiktekannya kepadaku dan aku tulis untuk Muawiyah.',
  },
  'dua-huda-tuqa': {
    fr: 'Ô Allah, je Te demande la bonne direction, la protection contre le mal, la chasteté et l’indépendance.',
    id: "ALLOOHUMMA INNII AS-ALUKALHUDAA WATTUQOO WAL'AFAAFA WALGHINAA",
    ur: 'کرتے تھے : " اے اللہ! میں تجھ سے ہدایت ، تقویٰ ، پاک دامنی ، اور ( دل کا ) غنا مانگتا ہوں ۔',
  },
  'evening-amsayna': {
    fr: 'Nous sommes entrés dans la soirée, et tout le Royaume d’Allah est aussi entré dans la soirée, et louange à Allah. Il n’y a pas de divinité en dehors d’Allah, l’Unique qui n’a pas d’associé.',
  },
  'evening-protection': {
    fr: 'Je cherche refuge dans la Parole Parfaite d’Allah contre le mal de ce qu’Il a créé',
  },
  'friday-best-day': {
    fr: 'Le meilleur jour sur lequel le soleil s’est levé est le vendredi : c’est ce jour-là qu’Adam a été créé, qu’il est entré au Paradis et qu’il en a été expulsé.',
    id: "Sebaik-baik hari adalah hari Jum'at, karena pada hari itulah Adam diciptakan. Pada hari itu pula ia dimasukkan ke dalam surga dan pada hari itu pula ia dikeluarkan daripadanya",
    ur: 'ابن شہاب نے کہا : مجھے عبد الرحمٰن اعرج نے خبر دی انھوں نے حضرت ابو ہریرۃ رضی اللہ تعالیٰ عنہ کو کہتے سنا کہ رسول اللہ صلی اللہ علیہ وسلم نے فر ما یا : " بہترین دن جس پر سورج طلوع ہو تا ہے جمعے کا دن ہے اسی دن آدم ؑپیدا کیے گئے اور اسی دن جنت میں داخل کیے گئے اور اسی دن اس سے نکا لے گئے ۔',
  },
  'friday-dua-hour': {
    fr: 'Il y a un moment le vendredi où aucun serviteur musulman ne prie et ne demande une chose bonne à Allah sans qu’Il ne la lui accorde.',
    id: 'Di dalamnya terdapat satu waktu, tidaklah seorang muslim mendapati waktu itu lalu berdoa memohon kebaikan kepada Allah, kecuali Allah akan mengabulkan permohonannya.',
  },
  'hadith-strong': {
    fr: 'Si je n’avais pas fait ceci, cela ne serait pas arrivé',
  },
  'h2-muslim-safe': {
    fr: 'Le musulman est celui dont les autres musulmans sont à l’abri de la main et de la langue.',
    id: "Saya mendengar [Jabir] berkata, 'Saya mendengar Nabi shallallahu 'alaihi wasallam bersabda:",
    ur: 'حضرت جابر ‌رضی ‌اللہ ‌عنہ ‌ ‌ بیان کرتے ہیں کہ میں نے رسول اللہ ﷺ کو یہ کہتے ہوئے سنا : ’’ مسلمان وہ ہے جس کی زبان اور ہاتھ سے دوسرے مسلمان محفوظ رہیں',
  },
  'h2-love-brother': {
    fr: 'Aucun de vous ne croit vraiment tant qu’il n’aime pas pour son frère – ou il a dit : pour son voisin – ce qu’il aime pour lui-même.',
    id: "Tidaklah salah seorang dari kalian beriman hingga dia mencintai untuk saudaranya, atau dia mengatakan, 'untuk tetangganya sebagaimana yang ia cintai untuk dirinya sendiri",
    ur: 'اپنے پڑوسی کے لیے بھی ) وہی پسند کرے جو وہ اپنے لیے پسند کرتا ہے ۔ ‘ ‘',
  },
  'h2-consistent-deeds': {
    fr: 'Les actes les plus aimés d’Allah sont ceux qui sont faits régulièrement, même s’ils sont petits.',
    id: 'Amalan yang paling dicintai Allah adalah yang terus-menerus (dilakukan) meskipun sedikit.',
  },
  'h2-hearts-deeds': {
    fr: 'En vérité, Allah ne regarde pas vos visages ni vos biens, mais Il regarde votre cœur et vos actions.',
    id: 'Sesungguhnya Allah tidak melihat kepada rupa dan harta kalian, tetapi Allah melihat kepada hati dan amal kalian',
    ur: 'اللہ تعالیٰ تمہاری صورتوں اور تمہارے اموال کی طرف نہیں دیکھتا ، لیکن وہ تمہارے دلوں اور اعمال کی طرف دیکھتا ہے ۔',
  },
  'h2-religion-ease': {
    fr: 'La religion, c’est la sincérité.',
    id: 'Agama itu adalah nasihat.',
  },
  'h2-two-words': {
    fr: 'Il y a deux expressions légères sur la langue, lourdes dans la balance, aimées du Tout Miséricordieux : “Gloire à Allah et louange à Lui” ; “Gloire à Allah, le Très Grand.”',
    id: "'Dua kalimat yang ringan diucapkan tetapi berat timbangannya dan disenangi oleh Allah Subhanahu wa Ta'ala Yang Maha Pengasih yaitu, Subhanallah wa bihamdihi subhaanallaahil azhim (Maha Suci Allah dengan segala pujian-Nya dan Maha Suci Allah Yang Maha Agung)",
    ur: 'دو کلمے ہیں جو زبان پر ہلکے ہیں اور میزان میں بھاری ہیں اور اللہ کو بہت محبوب ہیں :',
  },
  'h2-closest-sujud': {
    fr: 'Le moment où le serviteur est le plus proche de son Seigneur, c’est lorsqu’il est en prosternation, alors faites des invocations dans cet état.',
    id: 'Keadaan seorang hamba yang paling dekat dari Rabbnya adalah ketika dia sujud, maka perbanyaklah doa',
    ur: '’’بندہ اپنے رب کے سب سے زیادہ قریب اس حالت میں ہوتا ہے جب وہ سجدے میں ہوتا ہے ، لہٰذا اس میں کثرت سے دعا کرو ۔ ‘ ‘',
  },
  'h2-friday-expiation': {
    fr: 'Les cinq prières quotidiennes, d’un vendredi à l’autre, et de Ramadan à Ramadan, sont des expiations pour les péchés commis entre ces périodes, à condition d’éviter les grands péchés.',
    id: "Shalat lima waktu dan shalat Jum'at ke Jum'at berikutnya, dan Ramadlan ke Ramadlan berikutnya adalah penghapus untuk dosa antara keduanya apabila dia menjauhi dosa besar",
    ur: 'کرتے تھے : ’’جب ( انسان ) کبیرہ گناہوں سے اجتناب کر رہا ہو تو پانچ نمازیں ، ایک جمعہ ( دوسرے ) جمعہ تک اور ایک رمضان دوسرے رمضان تک ، درمیان کے عرصے میں ہونے والے گناہوں کو مٹانے کا سبب ہیں ۔ ‘ ‘',
  },
  'h2-qiyam-ramadan': {
    fr: 'Celui qui prie la nuit pendant le Ramadan, avec foi et en espérant la récompense d’Allah, ses péchés passés lui seront pardonnés.',
    id: 'Barangsiapa yang menunaikan shalat pada malam bulan Ramadlan (shalat tarawih) dengan penuh keimanan dan mengharap (pahala dari Allah), maka dosa-dosanya yang telah berlalu akan diampuni',
    ur: 'جس شخص کے ایمان ( کی حالت میں ) اور اجر طلب کرتے ہوئے رمضان کا قیام کیا اس کے گزشتہ تمام گناہ معاف کردیئے گئے ۔',
  },
  'h2-qiyam-qadr': {
    fr: 'Celui qui jeûne pendant le Ramadan avec foi et en espérant la récompense d’Allah, tous ses péchés passés seront pardonnés. Et celui qui prie la nuit du destin (Lailat-ul-Qadr) avec foi et en espérant la récompense d’Allah, tous ses péchés passés seront pardonnés.',
    ur: 'جس نے رمضان کے روزے ایمان ( کی حالت میں ) اور ثواب کے لئے رکھے ، اس کے گزشتہ سب گناہ معاف کردیئے جائیں گے اور جس نے لیلۃ القدر کا قیام ایمان کے ساتھ اور ثواب کے لئے کیا تو اس کے گزشتہ سارے گناہ معاف کردیئے جائیں گے ۔',
  },
  'h2-suhoor': {
    fr: 'Prenez un repas peu avant l’aube, car il y a une bénédiction dans ce repas.',
    id: 'Makan sahurlah kalian, karena (makan) di waktu sahur itu mengandung barakah',
    ur: 'کہ سحری کھایا کرو کیونکہ سحری کے کھانے میں برکت ہوتی ہے ۔',
  },
  'h2-hasten-iftar': {
    fr: 'Les gens continueront à aller bien tant qu’ils s’empresseront de rompre le jeûne.',
    id: 'Manusia akan senantiasa berada dalam kebaikan selama mereka menyegerakan untuk berbuka.',
    ur: 'لوگ ہمیشہ بھلائی کے ساتھ رہیں گے جب تک روزہ جلد افطار کرتے رہیں گے ۔',
  },
  'h2-fast-fisabilillah': {
    fr: 'Tout serviteur d’Allah qui jeûne un jour pour Allah, Allah éloignera son visage du Feu (de l’Enfer) d’une distance de soixante-dix ans grâce à ce jour.',
    id: 'Tidaklah seorang hamba berpuasa sehari di jalan Allah, kecuali Allah akan menjauhkan wajahnya dari api neraka sejauh tujuh puluh ribu musim.',
    ur: 'کوئی شخص نہیں جو اللہ کی راہ میں ایک دن کا روزہ رکھے مگر اللہ تعا لیٰ اس دن ( کے روزے ) بدلے اس کے چہرے کو ( جہنم کی ) آگ سے ستر سال کی مسافت تک دورکردے گا ۔',
  },
  'h2-umrah-expiation': {
    fr: 'Une ‘Umra efface les péchés commis entre elle et la suivante, et un Hajj accepté n’a d’autre récompense que le Paradis.',
    id: 'Umrah demi umrah berikutnya adalah masa penghapusan dosa. Dan tidak ada ganjaran bagi ibadah haji yang mabrur kecuali surga.',
    ur: 'ایک عمرہ دوسرے عمرے تک ( کےگناہوں ) کا کفارہ ہے اور حج مبرور ، اس کا بدلہ جنت کے سوا اور کوئی نہیں ۔',
  },
  'h2-building': {
    fr: 'Le croyant est pour un autre croyant comme une brique soutenant une autre brique.',
    id: 'Orang mukmin yang satu dengan mukmin yang lain bagaikan satu bangunan, satu dengan yang lainnya saling mengokohkan',
    ur: 'ایک مسلمان دوسرے مسلمان کے لیے ایک عمارت کے مانند ہے ، جس کی ایک ( اینٹ ) دوسری ( اینٹ ) کو مضبوط کرتی ہے ۔',
  },
  'h2-understanding-deen': {
    fr: 'Celui à qui Allah veut du bien, Il lui donne la compréhension de la religion.',
    id: 'Siapa yang dikehendaki Allah menjadi baik, maka akan dipahamkan-Nya dengan kepahaman yang dalam tentang agama.',
    ur: 'اللہ تعالیٰ جس کے ساتھ بھلا ئی کرنا چا ہتا ہے اسے دین میں گہرا فہم عطا فر ما دیتا ہے اور میں نے رسول اللہ صلی اللہ علیہ وسلم کو یہ فر ما تے ہو ئے بھی سنا :',
  },
  'h2-allah-beautiful': {
    fr: 'Mais une personne aime porter de beaux vêtements et de belles chaussures.',
    id: 'Tidak akan masuk surga, orang yang di dalam hatinya terdapat seberat biji sawi dari kesombongan.',
  },
  'h2-modesty': {
    fr: 'La pudeur n’apporte que du bien.',
  },
  'h2-sick-tahur': {
    fr: 'Ne veux-tu pas invoquer Allah pour moi, ô Ibn ‘Umar ?',
  },
  'h2-distress-dua': {
    fr: 'Il n’y a pas de divinité en dehors d’Allah, le Grand, le Tolérant. Il n’y a pas de divinité en dehors d’Allah, le Seigneur du Trône magnifique. Il n’y a pas de divinité en dehors d’Allah, le Seigneur des cieux et de la terre, le Seigneur du Trône sublime.',
    id: "LAA-ILAAHA ILLALLOOHUL 'AZHIIMUL HALIIM, LAA-ILAAHA ILLALLOOH ROBBUL'ARSYIL 'AZHIIM, LAA-ILAAHA ILLALLAH ROBBUSSAMAAWAATI WAROBBUL ARDHI WAROBBUL'ARSYIL KARIIMI",
    ur: 'معاذ بن ہشام نے کہا : مجھے میرے والد نے قتادہ سے حدیث بیان کی ، انہوں نے ابوعالیہ سے اور انہوں نے حضرت ابن عباس رضی اللہ عنہ سے روایت کی کہ نبی صلی اللہ علیہ وسلم کرب کے وقت یہ دعا کیا کرتے تھے : " اللہ کے سوا کوئی عبادت کے لائق نہیں جو سب سے عظیم ہے ، سب سے زیادہ حلم والا ہے ۔ اللہ کے سوا کوئی عبادت کے لائق نہیں جو عرش عظیم کا مالک ہے ۔ اللہ کے سوا کوئی عبادت کے لائق نہیں جو آسمانوں کا مالک ، زمینوں کا مالک اور عزت والے عرش کا مالک ہے ۔',
  },
  'h2-guidance-dua': {
    fr: 'Ô Allah, guide-moi vers le droit chemin et fais-moi persévérer sur la voie droite.',
    id: "Rasulullah shallallahu 'alaihi wasallam telah bersabda kepada saya:",
  },
  'h2-jazakallah': {
    fr: 'Qu’Allah te récompense ! Chaque fois que tu rencontres une difficulté, Allah en fait une bénédiction pour les musulmans.',
  },
  'qadr-seek': {
    fr: 'Cherchez (et selon les mots de Waki, recherchez) la Nuit du Destin dans les dix dernières nuits du Ramadan.',
    id: 'Cari dan tunggulah malam lailatul Qadr dalam sepuluh hari terakhir bulan Ramadlan.',
    ur: 'لیلۃالقدر کو رمضا ن کی آخری دس راتوں میں تلا ش کرو ۔',
  },
  'morning-radeetu': {
    fr: 'Celui qui dit, en entendant le muezzin, et en vérité j’atteste…',
  },
  'hadith-no-mercy': {
    fr: 'Ce n’est pas la menstruation, mais du sang provenant d’une veine. Prends un bain et fais la prière.',
    id: 'bahwa putrid Jahsy dahulu mengalami istihadhah selama tujuh tahun',
  },
  'hadith-anger': {
    fr: 'Le fort n’est pas celui qui lutte bien, mais le fort est celui qui se maîtrise lorsqu’il est en colère.',
    id: 'Orang yang paling kuat bukanlah orang yang tidak dapat dikalahkan oleh orang lain. Tetapi orang yang paling kuat adalah orang yang dapat menguasai dirinya ketika ia sedang marah',
    ur: '( کوئی شخص ) پچھاڑ دینے سے طاقت نہیں ہوتا ۔ طاقتور ( مضبوط ) وہ ہے جو غصے کے وقت خود کو قابو میں رکھتا ہے ۔',
  },
  'hadith-purity': {
    fr: '(Gloire à Allah) et',
    id: "Rasulullah shallallahu 'alaihi wasallam bersabda:",
  },
  'morning-asbahna': {
    fr: 'Nous sommes entrés dans la soirée, et tout le Royaume d’Allah est aussi entré dans la soirée. Louange à Allah. Il n’y a pas de divinité en dehors d’Allah, l’Unique qui n’a pas d’associé.',
    id: "Apabila sore hari, Rasulullah shallallahu 'alaihi wasallam mengucapkan do'a yang berbunyi: 'AMSAINAA WA AMSAL MULKU LILLAAH, WALHAMDULILLAAH, LAA-ILAAHA ILLALLAH, WAHDAHUU LAA SYARIIKA LAHU",
    ur: 'ہم اور سارا ملک شام کے وقت بھی اللہ کا ہوا ، سب حمد اللہ کے لیے ہے ، اللہ کے سوا کوئی عبادت کے لائق نہیں ، وہ اکیلا ہے ، اس کا کوئی شریک نہیں ۔',
  },
  'morning-tasbih': {
    fr: '. » Il répondit : « Mon Seigneur m’a informé que j’allais bientôt voir un signe dans ma communauté. Lorsque je l’ai vu, j’ai commencé à répéter fréquemment ces paroles :',
    id: "Dahulu Rasulullah Shallallahu'alaihiwasallam memperbanyak pertakataan, 'SUBHAANALLOOH WABIHAMDIHI ASTAGHFIRULLAH WA ATUUBU ILAIHI Mahasuci Allah dan dengan memujiNya, saya memohon ampunan kepada Allah dan saya bertaubat kepadaNya'.",
  },
  'muharram-fast': {
    fr: 'Le meilleur jeûne après Ramadan est celui du mois d’Allah, al-Mouharram, et la meilleure prière après les prières obligatoires est la prière de nuit.',
    id: 'Seutama-utama puasa setelah Ramadlan ialah puasa di bulan Muharram, dan seutama-utama shalat sesudah shalat Fardlu, ialah shalat malam',
    ur: 'رمضا ن کے بعد سب سے افضل روزے اللہ کے مہینے',
  },
  'ashura-fast': {
    fr: 'Il n’a ni jeûné ni rompu son jeûne, ou il a dit : Il n’a ni jeûné ni arrêté.',
    id: 'Wahai Rasulullah, bagaimana dengan orang yang berpuasa sepanjang tahun?',
    ur: 'مجھے پسند ہے کہ مجھے اس کی طاقت مل جاتی ۔ پھر رسول اللہ صلی اللہ علیہ وسلم نے فرمایا :',
  },
  'ramadan-forgiveness': {
    fr: 'Celui qui prie la nuit pendant le Ramadan, avec foi et en espérant la récompense d’Allah, ses péchés passés lui seront pardonnés.',
    id: 'Barangsiapa yang menunaikan shalat pada malam bulan Ramadlan (shalat tarawih) dengan penuh keimanan dan mengharap (pahala dari Allah), maka dosa-dosanya yang telah berlalu akan diampuni',
    ur: 'جس شخص کے ایمان ( کی حالت میں ) اور اجر طلب کرتے ہوئے رمضان کا قیام کیا اس کے گزشتہ تمام گناہ معاف کردیئے گئے ۔',
  },
  'ramadan-gates': {
    fr: 'Quand arrive le mois de Ramadan, les portes de la miséricorde s’ouvrent, les portes de l’Enfer se ferment et les démons sont enchaînés.',
    id: 'Bila bulan Ramadlan tiba, maka dibukalah pintu-pintu surga, pintu-pintu neraka ditutup dan syetan-syetan pun dibelenggu',
    ur: 'جب رمضان آتا ہے جنت کے دروازے کھول دیئے جاتے ہیں اور دوزخ کےدروازے بند کردیئے جاتے ہیں اور شیاطین بیڑیوں میں جکڑ دیئے جاتے ہیں ۔',
  },
  'dh-hamd-salihat': {
    fr: 'Al-hamdu lillahi ‘ala kulli hal (Louange à Allah en toute circonstance).',
    id: 'dan apabila melihat sesuatu yang dibenci, beliau mengucapkan:',
    ur: 'الحمد لله الذي بنعمته تتم الصالحات',
  },
  'dh-ilm-nafi': {
    fr: 'Allahumma inni as’aluka ‘ilman nafi’an, wa rizqan tayyiban, wa ‘amalan mutaqabbalan.',
    id: "Ketika salam dalam shalat subuh Nabi shallallahu 'alaihi wasallam mengucapkan;",
    ur: 'اللهم إني أسألك علما نافعا ورزقا طيبا وعملا متقبلا',
  },
  'dh-rabbi-ighfir': {
    fr: 'Mon Seigneur, pardonne-moi et accorde-moi Ton pardon ; Tu es Celui qui pardonne et qui efface les fautes.',
    id: "RABBIGHFIRLII WA TUB 'ALAYYA, INNAKAT TAWWAABUR RAHIIM",
    ur: 'رب اغفر لي وتب علي إنك أنت التواب الرحيم',
  },
  'dh-malik-quddus': {
    fr: 'Gloire au Roi, le Très Saint.',
    id: 'SUBHAANAL MALIKIL QUDDUUS',
    ur: 'سبحان الملك القدوس',
  },
  'friday-salawat-hadith': {
    fr: 'Allah, le Très-Haut, a interdit à la terre de consommer les corps des Prophètes.',
    ur: 'اللہ تعالیٰ نے زمین پر پیغمبروں کے بدن کو حرام کر دیا ہے ۔',
  },
  'morning-nimah': {
    fr: 'Ô Allah ! tout bienfait qui m’est parvenu vient de Toi seul, sans associé ; à Toi la louange et la reconnaissance',
    id: "Barangsiapa mengucapkan saat waktu pagi: ALLAHUMMA MAA ASHBAHA BII MIN NI'MATIN FAMINKA WAHDAKA LAA SYARIIKA LAKA FALAKAL HAMDU WA LAKASY SYUKRU (Ya Allah, pagi ini tidak ada nikmat yang ada padaku kecuali dari-Mu semata, tidak ada sekutu bagi-Mu. Maka bagi-Mu lah segala puji dan syukur).",
    ur: 'اللهم ما أصبح بي من نعمة فمنك وحدك لا شريك لك فلك الحمد ولك الشكر',
  },
  'evening-afini': {
    fr: 'J’ai entendu le Messager d’Allah ﷺ utiliser ces paroles comme invocation et j’aime suivre sa pratique.',
    ur: 'اللهم إني أعوذ بك من الكفر والفقر اللهم إني أعوذ بك من عذاب القبر لا إله إلا أنت',
  },
  'dua-help-remember': {
    fr: 'Ô Allah, aide-moi à me souvenir de Toi, à Te remercier et à T’adorer de la meilleure façon.',
    id: "Wahai Mu'adz, demi Allah, aku mencintaimu.",
    ur: 'اللهم أعني على ذكرك وشكرك وحسن عبادتك',
  },
  'morning-afiyah': {
    fr: 'C’est-à-dire être englouti par la terre.',
    id: "Belum pernah Rasulullah shallallahu 'alaihi wasallam meninggalkan doa-doa tersebut saat tiba waktu sore dan pagi hari:",
    ur: 'عوراتي وآمن روعاتي اللهم احفظني من بين يدى ومن خلفي وعن يميني وعن شمالي ومن فوقي وأعوذ بعظمتك أن أغتال من تحتي',
  },
  'ramadan-iftar': {
    fr: 'La soif est partie, les veines sont humidifiées, et la récompense est assurée, si Allah le veut.',
    ur: 'ذهب الظمأ وابتلت العروق وثبت الأجر إن شاء الله',
  },
  'dh-sleep': {
    fr: 'Allahumma bismika amutu wa ahya.',
    ur: 'اے اللہ! تیرے نام کے ساتھ مرتا ہوں اور زندہ ہوتا ہوں۔',
  },
  'dh-sayyid-istighfar': {
    fr: "La meilleure façon de demander pardon à Allah est : ‘Allahumma anta Rabbi la ilaha illa anta, Khalaqtani wa ana `Abduka, wa ana `ala `ahdika wa wa`dika mastata`tu, A`udhu bika min Sharri ma sana`tu, abu'u Laka bini`matika `alaiya, wa abu'u laka bidhanbi faghfir lee fa innahu la yaghfiru adhdhunuba illa anta.’",
    id: "Sesungguhnya istighfar yang paling baik adalah; kamu mengucapkan: 'ALLAHUMMA ANTA RABBI LAA ILAAHA ILLA ANTA KHALAQTANI WA ANA 'ABDUKA WA ANA 'ALA 'AHDIKA WA WA'DIKA MASTATHA'TU A'UUDZU BIKA MIN SYARRI MAA SHANA'TU ABUU`U LAKA BIDZANBI WA ABUU`U LAKA BINI'MATIKA 'ALAYYA FAGHFIRLI FA INNAHU LAA YAGHFIRU ADZ DZUNUUBA ILLA ANTA (Ya Allah, Engkau adalah Tuhanku, tidak ada Tuhan yang berhak diibadahi selain Engkau. Engkau telah menciptakanku dan aku adalah hamba-Mu. Aku menetapi perjanjian-Mu dan janji-Mu sesuai dengan kemampuanku. Aku berlindung kepada-Mu dari keburukan perbuatanku, aku mengakui dosaku kepada-Mu dan aku akui nikmat-Mu kepadaku, maka ampunilah aku. Sebab tidak ada yang dapat mengampuni dosa selain-Mu) '.",
    ur: 'اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں۔ تو نے ہی مجھے پیدا کیا اور میں تیرا ہی بندہ ہوں میں اپنی طاقت کے مطابق تجھ سے کئے ہوئے عہد اور وعدہ پر قائم ہوں۔ ان بری حرکتوں کے عذاب سے جو میں نے کی ہیں تیری پناہ مانگتا ہوں مجھ پر نعمتیں تیری ہیں اس کا اقرار کرتا ہوں۔ میری مغفرت کر دے کہ تیرے سوا اور کوئی بھی گناہ نہیں معاف کرتا۔',
  },
  'hadith-best-quran': {
    fr: 'Les meilleurs parmi vous sont ceux qui apprennent le Coran et l’enseignent.',
    id: 'Orang yang paling baik di antara kalian adalah seorang yang belajar Al Qur`an dan mengajarkannya.',
  },
  'ashura-musa': {
    fr: 'C’est un bon jour, le jour où Allah a sauvé les Enfants d’Israël de leur ennemi. Moïse a donc jeûné ce jour-là.',
    id: "Ketika Nabi shallallahu 'alaihi wasallam telah sampai dan tinggal di Madinah, Beliau melihat orang-orang Yahudi melaksanakan puasa hari 'Asyura' lalu Beliau bertanya:",
    ur: 'پھر موسیٰ علیہ السلام کے ( شریک مسرت ہونے میں ) ہم تم سے زیادہ مستحق ہیں۔ چنانچہ آپ صلی اللہ علیہ وسلم نے اس دن روزہ رکھا اور صحابہ رضی اللہ عنہم کو بھی اس کا حکم دیا۔',
  },
  'dua-anxiety': {
    fr: "Choisis un de tes jeunes serviteurs pour m'accompagner lors de mon expédition à Khaybar.",
    id: '(Ya Allah aku berlindung kepada-Mu dari (sifat) gelisah, sedih, lemah, malas, kikir, pengecut, terlilit hutang dan dari keganasan orang',
    ur: 'اللهم إني أعوذ بك من الهم والحزن والعجز والكسل والبخل والجبن وضلع الدين وغلبة الرجال',
  },
  'h2-rain-dua': {
    fr: 'Allahummaj’alhu sayyiban nafi‘a. (Ô Allah, fais-en une pluie bénéfique.)',
    ur: '‏اللہم اجعله صيبا نافعا',
  },
  'hijjah-ten-days': {
    id: 'Tidak ada hari-hari untuk berbuat amal shalih yang lebih Allah cintai kecuali sepuluh hari pertama bulan Dzul Hijjah,',
    ur: '، لوگوں نے عرض کیا: اللہ کے رسول! اللہ کی راہ میں جہاد کرنا بھی نہیں؟ آپ صلی اللہ علیہ وسلم نے فرمایا:',
  },
  'dua-muqallib': {
    id: 'Wahai Rasulullah, kami beriman kepadamu dan kepada apa yang Anda bawa. Lalu apakah Anda masih khawatir kepada kami?',
    ur: 'عن الأعمش عن أبي سفيان عن جابر عن النبي صلى الله عليه وسلم',
  },
  'evening-bika-amsayna': {
    id: 'Apabila salah seorang di antara kalian berada pada pagi hari maka hendaknya mengucapkan; ALLAAHUMMA BIKA ASHBAHNAA WA BIKA AMSAINAA WA BIKA NAHYAA WA BIKA NAMUUTU WA ILAIKAN NUSYUUR.',
    ur: '، اور آپ نے اپنے صحابہ کو سکھایا جب تم میں سے کسی کی شام ہو تو اسے چاہیئے کہ کہے «اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك النشور»',
  },
  'h2-taqwa-wherever': {
    id: 'Bertakwalah kamu kepada Allah dimana saja kamu berada dan ikutilah setiap keburukan dengan kebaikan yang dapat menghapuskannya, serta pergauilah manusia dengan akhlak yang baik.',
    ur: 'جہاں بھی رہو اللہ سے ڈرو، برائی کے بعد ( جو تم سے ہو جائے ) بھلائی کرو جو برائی کو مٹا دے ۱؎ اور لوگوں کے ساتھ حسن اخلاق سے پیش آؤ',
  },
  'h2-thank-people': {
    id: 'Siapa yang tidak pandai bersyukur (berterima kasih) kepada manusia, berarti ia belum bersyukur kepada Allah.',
    ur: 'جو لوگوں کا شکر یہ ادا نہ کرے وہ اللہ کا شکر ادا نہیں کرے گا',
  },
  'h2-travel-farewell': {
    id: "ISTAUDI'ILLAAHA DIINAKA WA AMAANATAKA WA AAKHIRA 'AMALIKA",
    ur: 'میں تیرا دین، تیری امانت، ایمان اور تیری زندگی کا آخری عمل ( سب ) اللہ کی سپردگی و حوالگی میں دیتا ہوں',
  },
  'h2-after-food': {
    id: "Al HAMDULILLAAHILLADZII ATH'AMANAA WA SAQAANAA WA JA'ALANAA MUSLIMIIN",
    ur: 'سب تعریفیں اس اللہ کے لیے ہیں جس نے ہمیں کھلایا پلایا اور ہمیں مسلمان بنایا',
  },
  'ramadan-feed-fasting': {
    id: 'Barangsiapa yang memberi makan orang yang berbuka, dia mendapatkan seperti pahala orang yang berpuasa tanpa mengurangi pahala orang yang berpuasa sedikitpun',
    ur: 'جس نے کسی روزہ دار کو افطار کرایا تو اسے بھی اس کے برابر ثواب ملے گا، بغیر اس کے کہ روزہ دار کے ثواب میں سے ذرا بھی کم کیا جائے',
  },
  'morning-bika-asbahna': {
    id: 'Apabila salah seorang di antara kalian berada pada pagi hari maka hendaknya mengucapkan; ALLAAHUMMA BIKA ASHBAHNAA WA BIKA AMSAINAA WA BIKA NAHYAA WA BIKA NAMUUTU WA ILAIKAN NUSYUUR.',
    ur: '، اور آپ نے اپنے صحابہ کو سکھایا جب تم میں سے کسی کی شام ہو تو اسے چاہیئے کہ کہے «اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك النشور»',
  },
  'occasion-wedding': {
    id: "Hadits semakna diriwayatkan dari 'Aqil bin Abu Thalib.",
    ur: 'اللہ تجھے برکت عطا کرے، اور تجھ پر برکت نازل فرمائے اور تم دونوں کو خیر پر جمع کرے',
  },
  'dh-palm-tree': {
    ur: 'دو کلمے ہیں جو زبان پر ہلکے ہیں اور میزان میں بھاری ہیں اور اللہ کو بہت محبوب ہیں :',
  },
  'dh-hasbi-allah': {
    ur: 'لقد جاءكم رسول من أنفسكم عزيز عليه ما عنتم حريص عليكم بالمؤمنين رءوف رحيم فإن تولوا فقل حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم',
  },
  'dh-bismillah-protect': {
    ur: 'ایسا کوئی شخص نہیں ہے جو ہر روز صبح و شام کو «بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم»',
  },
  'dua-istighfar': {
    ur: 'أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه',
  },
  'hadith-mercy': {
    ur: 'رحم کرنے والوں پر رحمن رحم کرتا ہے، تم لوگ زمین والوں پر رحم کرو تم پر آسمان والا رحم کرے گا، رحم رحمن سے مشتق ( نکلا ) ہے، جس نے اس کو جوڑا اللہ اس کو ( اپنی رحمت سے ) جوڑے گا اور جس نے اس کو توڑا اللہ اس کو اپنی رحمت سے کاٹ دے گا',
  },
  'h2-dua-worship': {
    ur: 'وقال ربكم ادعوني أستجب لكم',
  },
  'h2-leaving-home': {
    ur: 'بسم الله توكلت على الله لا حول ولا قوة إلا بالله',
  },
  'qadr-dua': {
    ur: 'اللهم إنك عفو كريم تحب العفو فاعف عني',
  },
  'occasion-recovery': {
    ur: 'أسأل الله العظيم رب العرش العظيم أن يشفيك',
  },
};
